### PR TITLE
Fix too early light initialization (fixes #4723)

### LINKED ISSUE #4723: Initial skylight and relighting area loaded checks disagree (vanilla, performance)
Chunk.checkLight() is responsible for computing the skylight values in a newly generated/decorated chunk for locations that aren't directly exposed to the sky. It does so by calling World.checkLight(BlockPos) for each xz column in the chunk.

Chunk.checkLight() requires the 9 surrounding chunks to be loaded to do anything (+- 1 chunk).

World.checkLight(BlockPos) however requires +- 17 blocks from the operating position to be loaded, which at the extremes equals (0-17) >> 4 = -2 .. (15+17) >> 4 = +2 chunks.

If World.checkLight detects that the operating area is not fully loaded, it'll return false, which in turn causes Chunk.checkLight to abort the light initialization to be retried the next tick.

Since World.checkLight only checks +- 17 blocks from its current position and Chunk.checkLight calls it for all 256 xz positions in a chunk, light values for almost all positions may have already been computed before it bails out to start over another time.

This is a very significant waste of time that continues indefinitely until the required adjacent chunks happen to be loaded by some means. I've observed < 10 TPS for over 20 minutes on a fresh Twilight Forest world, 90% of the server thread CPU time were spent in Chunk.checkLight.

There are two ways to fix this:

a) Require a larger area to be loaded before Chunk.checkLight does something:

Replace `blockpos.add(-1, 0, -1), blockpos.add(16, this.world.getSeaLevel(), 16)` with `blockpos.add(-17, 0, -17), blockpos.add(32, this.world.getSeaLevel(), 32)` in Chunk.checkLight().

This shouldn't have any side effects besides no longer doing the partial light updates. World.checkLight shouldn't abort anymore.

b) Lower the range of World.checkLight to stay within +- 1 chunks, adjusting the area check:

Replace the three instances of 17 with 16 in World.checkLightFor(EnumSkyBlock, BlockPos).

The real range a light source can affect is only 14, but Minecraft recomputes light in a larger range as part of its "deglitching" routine that fixes incorrect light values. While 14 should be sufficient for a light update in a perfect world, decreasing the range from 17 severely lowers the effectiveness of repairing the many inaccuracies MC's light propagation leaves behind.

I recommend approach a.

### PR DESCRIPTION
**Pull request by Player3324**
This fixes the linked issue.

With the change applied Twilight Forest snaps right back to 20 TPS with 10 ms tick time after the initial lag spike instead of spending over 30 minutes at less than 10 TPS.

There should be no user observable behavior changes besides better performance, none were observed during testing.

### CODE REVIEW

**Comment by PhiProven** [comment]
IIRC this "results" in a (very rare) potential bug (I had this problem in #4430):
When a chunk `c` is initialized, some of its neighbors are still not yet initialized. This means that the light for `c` may not be correct as some contributions from the neighbors are missing (Their skylight is calculated via `generateSkylightMap` which is quite crude). The only way to really fix this problem (with the vanilla lighting engine) is to make initialization in two steps: first run the initialization code and then wait until the code has also completed for all the neigbors. Unfortunately, this gets quite messy.
The convoluted vanilla logic seems to get around this issue (certainly not on purpose). I guess this is because the initialization code starts when all neighbors are loaded and corrects all the bugs on its way. But it requires additional chunks to be loaded before it completes the process, which imitates the solution I described above.

IMHO the increased performance justifies this potential bug as it seems to be extremely rare. Just wanted to state it for completeness.

Edit: Let me also mention, that this bug is purely clientside: It is fixed serverside as soon as the neighbor chunks are initialized. The broken chunk `c` was sent to the client beforehand, so it is still wrong on the client. Reloading will therefore fix the issue, which makes it even less important.

Here is an instance of this bug (at least I suspect it's caused by it) that @mrgrim found on #4430:

**Comment by PhiProven** [comment]
After flying around for 30 minutes I was able to reproduce the bug I described above with this PR.



Because it is so rare, I can't tell for sure that it's caused (or at least its chance is increased) by this PR, since you had to look for it in a vanilla environment for quite a long time to have satisfying statistics.

**Comment by Player3324** [comment]
MC won't send chunks with isLightPopulated=false to clients and this PR doesn't change when this happens. It effectively just moves the abort condition earlier to not waste time on redundant computations, but doesn't change whether checkLight aborts overall.

Something as shown in https://github.com/MinecraftForge/MinecraftForge/pull/4430#issuecomment-333279687 is what I'd expect if you set isLightPopulated to true even if checkLight didn't finish completely. I believe Sponge's async light code may be a potential cause there.

Inter-chunk skylight propagation is supposed to be handled by Chunk.recheckGaps instead. This is already the two pass approach you are proposing, although it indeed lacks either delaying for isGapLightingUpdated=false or serializing isGapLightingUpdated and continuing on the client. The comment https://github.com/MinecraftForge/MinecraftForge/pull/4729#issuecomment-363098087 is exactly what I'd expect if a chunk without "gap light" was sent too soon. Another PR to also check `!isGapLightingUpdated` in Chunk.isPopulated() should fix this, but that's a different bug and not fundamentally affected by the change I'm proposing here.

**Comment by PhiProven** [comment]
You can do the following to reproduce the bug:
* create a world with seed `-1952261387849470895`
* `/tp -1250 90 350`
* fly 100 blocks in -x direction

You will get the following picture:



Using the forge 1.12 branch without this PR yields the following:



This indicates that the bug is indeed amplified by this PR.
If you tp to `-1450 90 350` the bug is not present even with this PR, indicating that it's indeed caused by what I described.

But as stated above, I would not care too much about this bug as it is hard to find an instance of it even if you know what to look for.

**Comment by Player3324** [comment]
This is a great test case, reproduces very reliably. It shows a lack of (proper) gap light update as expected.

Patching recheckGaps() to only run if the 3x3 were lit and isPopulated() to check isGapLightingUpdated resolves it according my testing. I'll update this PR with the additional bug fixes to not regress those corner cases.

**Comment by PhiProven** [comment]
Are you sure `isGapLightingUpdated` is the right flag to use?
* It is set for every `setBlockState`, meaning `isPopulated()` will switch back to `false` quite often.
* It is initialized with `false`. Hence the bug will not be fixed if no additional `setBlockState()` is called during terrain population (though this is quite unlikely). **Edit**: `setSkylightUpdated()`, which is called during `checkLight()`, doesn't set the flag.
* `recheckGaps()` seems to be more like a Mojang-style fix to lighting bugs in general than something fundamentally needed.
* `recheckGaps()` doesn't need to run in order to resolve the bug; it's enough to delay `isPopulated()` until `checkLight()` has completed for the neighbors. **Edit**: Well, `recheckGaps()` is used to initialize skylight during `checkLight()`. Anyway, it suffices to delay setting `isPopulated()` to `true`; `recheckGaps()` could run immediately.

I'd rather add a new flag (like I did in #4430). Not sure though if this flag should be saved (which makes the patch more invasive) or just be checked every time the chunk is loaded.

**Edit again**: ~In general, `recheckGaps()` suffers from the issue that the vanilla code doesn't require surrounding chunks to be loaded, whereas `World.checkLight(...)` requires a radius of 17 blocks to be loaded, so some checks may be discarded; hence the added loaded-checks would actually be needed. However, for the call inside `checkLight()` we know that enough chunks are loaded, so we could remove the checks in this case, at least. (Just wanted to argue, why `recheckGaps()` doesn't need to be delayed inside `checkLight()`)~ Just saw that you deleted the vanilla loaded-check. (Only looking at the patched source code but not the patch itself was a bad idea :P)

**Comment by PhiProven** [comment]
Just ignore my convoluted monologue above.

I think it would make the patch nicer if you do the following:
* add some `isLightReady` field
* Move your code from `recheckGaps()` to `onTick()` and set the `isLightReady` field accordingly. (This requires only the 3x3 instead of the 5x5 check)
* Replace `isLightPopulated` by `isLightReady` inside `isPopulated()`

This should produce a similar result as your current code but IMHO it's better not to overload the `isGapLightingUpdated` flag.

**Comment by Player3324** [comment]
The general reason behind requiring isGapLightingUpdated == false - which should really be called needGapLightingUpdate - is that the client won't be aware of the light values being dirty. The client always expects a fully lit chunk, so the server has to wait until this is the case.

recheckGaps(false) runs shortly before isPopulated() gets called from the player chunk handler, only random block ticks and ice/snow formation could call setBlockState() in between. The situation where isGapLightingUpdated is true during isPopulated() and all neighbors are ready (as in my recheckGaps() edit) should be very rare and resolve itself quickly.

I agree with having to set isGapLightingUpdated to true to be safe, probably in Chunk.setSkylightUpdated().

IMO changing more is too invasive/risky for Forge's scope.

File: patches/minecraft/net/minecraft/world/chunk/Chunk.java.patch [hunk 1]
```diff
@@ -26,7 +26,32 @@
...
+-        if (this.field_76637_e.func_175697_a(new BlockPos(this.field_76635_g * 16 + 8, 0, this.field_76647_h * 16 + 8), 16))
++        // FORGE: require 5x5 chunks to be loaded and 3x3 chunks to be lit
++        boolean skip = !this.field_150814_l;
++
++        for (int dz = -2; dz <= 2 && !skip; dz++)
+         {
++            for (int dx = -2; dx <= 2 && !skip; dx++)
++            {
++                Chunk chunk;
++                if ((dz != 0 || dx != 0) && ((chunk = field_76637_e.func_72863_F().func_186026_b(field_76635_g + dx, field_76647_h + dz)) == null || Math.abs(dz) != 2 && Math.abs(dx) != 2 && !chunk.field_150814_l))
```
Comment (mezz) [inline patches/minecraft/net/minecraft/world/chunk/Chunk.java.patch]: Please move this logic into a helper function in `net.minecraftforge.common.ForgeHooks` so that it is not in the patch and can be written more simply.

**Review by mezz — CHANGES_REQUESTED** [review]
This looks like a good change.

**Comment by mezz** [comment]
Linking here in a comment for Github. This fixes #4723

**Comment by PhiProven** [comment]
As far as I can tell, `recheckGaps()` is not really neeed outside `checkLight()` (It probably randomly fixes some lighting glitches, but I don't think that it fixes any particular bug purposfully). Hence, it shouldn't be required to wait for `isGapLightingUpdated == false`repeatedly; satisfying it once after `checkLight()` should be fine (Afterall, Vanilla doesn't check for this either).

I think my proposal is a bit less invasive, as it doesn't switch back `isPopulated()` to false. Vanilla uses this only to determine when a chunk should be sent to the client, but maybe some mod could use it for something else.

**Comment by bs2609** [comment]
Will link this if people want to contribute name suggestions: https://github.com/ModCoderPack/MCPBot-Issues/issues/595

**Comment by Player3324** [comment]
I dropped the second commit after we decided that it's safer, less intrusive and not much more correct overall.

The glitches caused by chunks being sent out too early also happen to a somewhat lesser degree without this PR, are only clientside, affect only completely new chunks, heal themselves after revisiting the area and are rare.

**Review by mezz — APPROVED** [review]

**Comment by LexManos** [comment]
Make it configurable in some way. Drull is working on making the world Provider control it in https://github.com/MinecraftForge/MinecraftForge/pull/4835.
We've discussed on IRC about making it a per-world config entry. 
Introducing bugs to everyone because some mods have odd world gen is not going to be accepted.

**Comment by PhiProven** [comment]
Profiled it in a Vanilla world:
It took up ~4ms per tick for render distance 12 and ~10 ms for render distance 32. This is quite some wasted time, so I think this fix is definitely useful in any case.
Not sure though, why it caused such massive TPS drop in the situation described in the initial post.

Instead of making the fix optional, we could of course fix the glitch properly.
As I described above, this would require to do the initial lighting in two steps:
* Running the current lighting code as soon as the 5x5 neighborhood is loaded and marking the chunk as `lightInitialized`
* Waiting with marking the chunk as `lightPopulated` until the 3x3 neighborhood is marked `lightInitialized`

This has the drawback that either:
* If only the `lightInitialized` flag is saved, the outermost chunks will almost never be `lightReady`, effectively decreasing the render distance by 1.
* If only the `lightPopulated` flag is saved, the outermost chunks may be `lightInitialized` but not `lightPopulated`, causing the lighting code to run again the next time they are loaded. While running it once per loaded chunk is much better than running it once per tick, it's still not perfect.
* Saving both requires to extend the chunk save format by an additional flag.

Also, the semantics of the `lightPopulated` flag is slightly altered, so we have to replace some of the occurrences by `lightInitialized`.

@LexManos Do you think it's worth implementing one of these options, or would you go with the config solution?

**Comment by Player3324** [comment]
This change doesn't really introduce new bugs, the same effect occurs in vanilla depending on where the unloaded chunks are relative to the chunk to be lit. It only removes a narrow case where vanilla happens to yield better results by accident.

Lighting checks covered by the extended loaded area check visit the chunk in a certain order (starting at x=0, z=0). The first few positions may not reach into/detect unloaded chunks in the positive x or z directions, so vanilla will pull light in from the neighbors. It however still fails if there is an unloaded chunk in the negative x or z directions, i.e. near the start position instead of the end position. Getting those first few positions in is what can sometimes produce a better result early without this PR.

Follow-up "gap" light updates will eventually fix missing inter-chunk lighting, but MC doesn't wait until they are done before sending chunks to the client and the client doesn't do them itself.

The performance impact is too substantial to ignore the issue, while the additional glitches are temporary, rare and situational:
- there have to be unloaded chunks only in the x+/z+ direction to make a difference
- only very specific terrain shapes are affected: area in a chunk not directly exposed to the sky, but through a neighbor with low enough light decay
- the sky exposed neighbor chunk has to not yet be initially lit while processing the current chunk
- the user needs to be able to notice it: no random light update in time, large enough light level drop and not too occluded by the terrain shape
- the actual light propagation code has to be inherently broken (which it is)
- MC corrects the lighting over time through "gap" and random light updates, so the chunk has to be new

A config only makes sense if the default is on due to lack of user awareness. The data PhiPro provided about the vanilla performance impact is roughly in line with my own observations. Assumptions that it's specific to certain mods don't hold, it's only a matter of unplayable vs wasting more tick time than most lesser optimized mods for nothing. The performance difference will disappear with bordering not generated chunks, but so do the glitches.

Although all concerns should be already sufficiently answered as is, I don't mind a default-on config and/or fixing the immediate glitches as described by PhiPro. The additional fixes target the 3rd precondition I mentioned above by introducing more explicit ordering. Mojang will likely resolve the bug in 1.13 on their side.

I'm waiting for an agreement on the approach before further adjusting the PR.

**Comment by Player3324** [comment]
We have developed a less functionally invasive approach that avoids extending the loaded area precondition and still maintains the usual light correction performance in cases where it matters.

The PR drops the light update range near the border to require only 3x3 chunks, which is still enough to fully update light even from the most extreme positions. MC's random light "de-glitching", which is sensitive to the light update range, works around the player locations. Players are inherently far away from unloaded chunks, so the random light updates retain their effectiveness with the new approach.

We are still waiting for a decision that considers my last explanation on whether the PR is good as is, it needs a way to turn off or a good replacement for the accidental better vanilla behavior in corner cases.

**Comment by PhiProven** [comment]
To move on the discussion, I have implemented the solution described above, so you can see what it looks like:
https://github.com/OverengineeredCodingDuo/MinecraftForge/tree/initial-skylight-areacheck-fix
Still would like to know if this is actually needed or if the PR can be accepted in its current state.

This fix effectively decreases the render distance for newly generated regions by 1, as it holds back the boundary chunks until their neighbors are initialized. This is necessarily true for any proper solution of the glitch.
However, the previous commit, ie. reducing the range requirement for the lighting engine 17 -> 16, increases the render distance by 1 compared to Vanilla, since it requires only a 3x3 neighborhood to do the initial lighting, whereas Vanilla indirectly needs a 5x5 neighborhood.
So, all in all, it leaves the render distance the same as Vanilla.

I also want to emphasize again that the glitch already occurs in Vanilla, I can show examples of that if desired.

**Comment by Niko-sk2x** [comment]
~~The 17 blocks range is required for a very good reason. If you don't require it, spreading light out may cause some of the outermost chunks to be loaded by checkLightFor when getting a light value or a heightmap value. It's very annoying value but it must be there if you don't want to load chunks in that method.~~ I didn't see the fix for the above. This is a change I really needed myself to fox some performance issues. I still don't know if there are edge cases where that last blocks of radius is needed. Also if updateRange is 17, it's very likely to load new chunks.

**Comment by LexManos** [comment]
There will always be edgecases, MC's light coding is horrible.
I'm tired of fighting for the simple 'Yes we can fix things, but make it configurable' So whatever, the almighty player says this fixes it so when shit breaks yell at him.

**Comment by Player3324** [comment]
I am far from almighty, but we are prepared to fix any issues that arise. Thanks.
