### PR TITLE
1.17 Fix InitGuiEvent

### LINKED ISSUE #7902: [1.17.1] InitGuiEvent "add" consumer is actually removing GuiEventListeners
**Minecraft Version:** 1.17.1
**Forge Version:** 37.0.0

**Description of issue:**
The "add" consumer is removing instead of adding to the children of the Screen.  The "added" widget is rendering but not recieving input (such as mouse click) since it hasn't been added as a child.
https://github.com/MinecraftForge/MinecraftForge/blob/1.17.x/patches/minecraft/net/minecraft/client/gui/screens/Screen.java.patch#L103

### PR DESCRIPTION
**Pull request by Cyborgmas**
Fixes #7902 
seems like a simple mistake made in porting patches.

### CODE REVIEW

File: patches/minecraft/net/minecraft/client/gui/screens/Screen.java.patch [hunk 1]
```diff
@@ -88,19 +88,16 @@
...
++         if (b instanceof Widget)
 +            this.f_169369_.add((Widget)b);
-+         }
-+
-+         if (b instanceof NarratableEntry) {
++         if (b instanceof NarratableEntry)
 +            this.f_169368_.add((NarratableEntry)b);
-+         }
-+         f_96540_.remove(b);
++         f_96540_.add(b);
```
Comment (SizableShrimp) [inline patches/minecraft/net/minecraft/client/gui/screens/Screen.java.patch:100]: This is Java 16, these can use pattern matching
