### PR TITLE
Rendering tweaks and fixes: Part 4

### LINKED ISSUE #9059: Model Transforms dont work for ObjModels
**Minecraft Version:** 1.19.2

**Forge Version:** 43.1.23

**Steps to Reproduce:**
 1. Update a mode that was using those obj models with transformations from 1.18 to 1.19 and the transformation wont be applied

**Description of issue:**
Seems like the actual transformation gets parsed fine as the syntax for the json didnt change, however its not applied on the model

### PR DESCRIPTION
**Pull request by amadornes**
After a few months, it's time for another round of small miscellaneous fixes, tweaks and community requests.

### Fix awkward root transform on elements models and unify baking

This one isn't exactly a bug. The original implementation of root transforms (prior to the client refactor) caused vanilla elements models to look rather broken, creating gaps and deforming quads in odd ways due to vanilla's quad generation logic not being designed to support arbitrary transforms. I kept this logic because I figured gigaherz was aware of it and deemed it okay. Developers, however, have requested that these transforms look correct for some time now, so this commit fixes it.

### Add support for root transforms to OBJ models (Fixes #9059)

Fixes OBJ models not using root transforms.

### Ensure OBJ components are stored in the order they are defined in disk

Switches OBJs from hash-based ordering (HashMap) to insertion-based ordering (LinkedHashMap). This guarantees that geometry is in the same order as in the OBJ file. Existing models should not rely on this behavior, and as such this is not a breaking change.  
Requested by Soaryn. Approved ahead of time by gigaherz.

### Allow children of composite models to update ModelData as needed

Fixes composite models not overriding the `getModelData(...)` method to allow their children to modify the data object.

### Add buffered quad-baking vertex consumer to simplify basic use cases

Adds a new buffered implementation of `QuadBakingVertexConsumer` that simplifies baking quads manually.  
Requested by tterrag.

### Fix normal handling in built-in quad transformer

Fixes the computed normals being ignored, as well as the test for the presence of any normal value.

### Add missing synchronized in ItemBlockRenderTypes

Adds `synchronized` to `ItemBlockRenderTypes#setRenderLayer(Fluid, RenderType)` to match the others and fix potential concurrency issues.

### CODE REVIEW

**Review by marchermans — APPROVED** [review]

File: src/main/java/net/minecraftforge/client/model/geometry/UnbakedGeometryHelper.java [hunk 1]
```diff
@@ -98,17 +99,28 @@ public static BakedModel bake(BlockModel blockModel, ModelBakery modelBakery, Bl
...
+    }
+
+    /**
+     * Helper for baking vanilla {@link BlockModel} instances.
+     *
+     * @deprecated Merge into the method above in 1.20 once the call from {@link BlockModel} is gone.
+     */
+    @ApiStatus.Internal
+    @Deprecated(forRemoval = true, since = "1.19.2")
+    public static BakedModel bakeVanilla(BlockModel blockModel, ModelBakery modelBakery, BlockModel owner, Function<Material, TextureAtlasSprite> spriteGetter, ModelState modelState, ResourceLocation modelLocation) {
```
Comment (eerussianguy) [inline src/main/java/net/minecraftforge/client/model/geometry/UnbakedGeometryHelper.java]: Brackets on newlines

Comment (amadornes) [reply src/main/java/net/minecraftforge/client/model/geometry/UnbakedGeometryHelper.java]: Completely missed this since it was copy-pasted from another place. Fixed!

**Review by sciwhiz12 — APPROVED** [review]
I have limited experience with the rendering API as a whole, but given Orion's approval, (by the PR description's admission) gigaherz's approval, and the lack of anything looking out of place to me, I'll assign this to the core team for now.

**Comment by SquidDev** [comment]
One other thing it might be worth fixing is that normal transformations in `QuadTransformers` doesn't appear to do anything. It creates the vector and transforms it, but writes back the original values.

https://github.com/MinecraftForge/MinecraftForge/blob/e1017a4c7e4331f591c5f89dff1215556e83f046/src/main/java/net/minecraftforge/client/model/QuadTransformers.java#L77-L80

**Comment by nikita488** [comment]
> One other thing it might be worth fixing is that normal transformations in `QuadTransformers` doesn't appear to do anything. It creates the vector and transforms it, but writes back the original values.
> 
> https://github.com/MinecraftForge/MinecraftForge/blob/e1017a4c7e4331f591c5f89dff1215556e83f046/src/main/java/net/minecraftforge/client/model/QuadTransformers.java#L77-L80

Yeah, normal transformation doesn't seems right.
Firstly, why is there `if ((normalIn >> 8) != 0)` check? Isn't it should be something like `if (x != 0 || y != 0 || z != 0)` or just `normal != 0`? See `IForgeVertexConsumer#applyBakedNormals`.
~~Secondly, why unpack and pack normal as `zyx` instead of just `xyz`? Again see `IForgeVertexConsumer#applyBakedNormals`. Also `QuadBakingVertexConsumer#normal` method needs to be swapped in this case too.~~ I'm dumb
Finally, `pos.normalize()` is not needed because pos is normalized already inside `IForgeTransformation#transformNormal` method. And `pos.perspectiveDivide()` is unnecessary too for position transform, because it's just divide xyz by 1.0F.
P.S. Also it will be a bit more readable to use `BufferVertexConsumer#normalIntValue` method when packing back, it already multiplies by 127.0F & 0xFF and casts to byte.

**Comment by amadornes** [comment]
> One other thing it might be worth fixing is that normal transformations in `QuadTransformers` doesn't appear to do anything. It creates the vector and transforms it, but writes back the original values.

Oh wow that's a major oversight on my part. I should've been taking the values from the vector 😅  
I'll add another commit for that later today.

As for Nikita's comments:
1. The check validates that there is a normal at all. The discarded byte (`>> 8`) is padding, and mods are known to mess with it to send their own info to shaders, so it should be ignored in a situation like this.
2. No you're not. But yes, it's packed with an unusual (for us) endianness.
3. Good point on normalization, we should indeed not need to do it twice. For position transforms, though, doing perspective divide is necessary. Generally it doesn't do anything, but for certain kinds of transforms it will matter, and a lot (namely projections).
4. The point of doing it manually is that it's as fast as possible. There is no buffer consumer in this context, and it wouldn't really make sense to create one just to avoid having to pack this, since it adds unnecessary overhead to other vertex data.

**Comment by sciwhiz12** [comment]
> 1. The discarded byte (`>> 8`) is padding, and mods are known to mess with it to send their own info to shaders, so it should be ignored in a situation like this.

Hmmm, sounds like something that should be noted in a comment next to that piece of code. :thinkies:

**Comment by nikita488** [comment]
> 3\. For position transforms, though, doing perspective divide is necessary. Generally it doesn't do anything, but for certain kinds of transforms it will matter, and a lot (namely projections).

Oh, i think i missed that `w` won't be always 1.0F because it transforms it before applying `perspectiveDivide`. Sorry!

> 4\. The point of doing it manually is that it's as fast as possible. There is no buffer consumer in this context, and it wouldn't really make sense to create one just to avoid having to pack this, since it adds unnecessary overhead to other vertex data.

The `BufferVertexConsumer#normalIntValue` is just a static helper method which is exactly this: `return (byte)((int)(Mth.clamp(pNum, -1.0F, 1.0F) * 127.0F) & 255);` It doesn't matter really, maybe will just help to reduce magic numbers inside code :P

**Review by marchermans — APPROVED** [review]
