### PR TITLE
Replace outdated Slider class with a more modern implementation

### LINKED ISSUE #8485: The forge-provided Slider does not stop when releasing the cursor outside the slider
**Minecraft Version:** 1.16.5, 1.18.1

**Forge Version:** 36.2.29, 39.0.88

**Steps to Reproduce:**
1. Create a screen with a slider using the forge-provided `Slider` class (`net.minecraftforge.(fml.)client.gui.widget.Slider`)
2. Open said screen, move the slider and keep holding
3. Move the cursor outside the slider box
4. Release the cursor

[Small mods for ease of reproduction](https://gist.github.com/PlatinPython/70443135e678142f77c5d77e55c2be60)

**Description of issue:**
When one releases the cursor outside of a slider's box the slider does not stop changing it's value, to stop it from moving one has to again click on the slider. This also allows moving multiple sliders at once.
[Video](https://streamable.com/e/9wcp5v)

### PR DESCRIPTION
**Pull request by PlatinPython**
This PR provides a replacement for the existing Slider class which has a couple issues (See #8485).
The existing class was deprecated and marked for removal, since it will no longer be required.
The replacement class includes a couple changes/additions, namely:
- Usage of `DecimalFormat` instead of manually creating the value String
- Addition of the `stepSize` field which allows input of discontinuous values
- Discontinuation of the `ISlider` callback, if needed, `applyValue` can be overriden to achieve a similar effect

Resolves and closes #8485

### CODE REVIEW

File: src/main/java/net/minecraftforge/client/gui/widget/ForgeSlider.java [hunk 1]
```diff
@@ -0,0 +1,209 @@
...
+        this.suffix = suffix;
+        this.minValue = minValue;
+        this.maxValue = maxValue;
+        this.stepSize = Math.abs(stepSize);
+        this.value = this.snapToNearest((currentValue - minValue) / (maxValue - minValue));
+        this.drawString = drawString;
+
+        if (stepSize == 0D)
+        {
+            precision = Math.min(precision, 4);
```
Comment (Alpvax) [inline src/main/java/net/minecraftforge/client/gui/widget/ForgeSlider.java:61]: Can we note this in the javadoc so that people aren't confused when >4 fails to work

Comment (PlatinPython) [reply src/main/java/net/minecraftforge/client/gui/widget/ForgeSlider.java:61]: Yeah, sure, was a late addition, so I forgot, will add the docs later.

File: src/main/java/net/minecraftforge/client/gui/widget/ForgeSlider.java [hunk 2]
```diff
@@ -0,0 +1,209 @@
...
+    /** Allows input of discontinuous values with a certain step */
+    protected double stepSize;
+
+    protected boolean drawString;
+
+    private final DecimalFormat format;
+
+    /**
+     * @param precision Only used when {@code stepSize} is 0. Limited to a maximum of 4 (inclusive).
+     */
```
Comment (marchermans) [inline src/main/java/net/minecraftforge/client/gui/widget/ForgeSlider.java]: Please document all params or none at all.

**Review by marchermans — CHANGES_REQUESTED** [review]
Generally good, but you need to give it another pass for the JDoc

File: src/main/java/net/minecraftforge/client/gui/widget/ForgeSlider.java (hunk 2 above)
Comment (PlatinPython) [reply src/main/java/net/minecraftforge/client/gui/widget/ForgeSlider.java]: My reasoning was that the rest of the parameters were pretty self explanatory, but sure, I can add the rest.

Comment (marchermans) [reply src/main/java/net/minecraftforge/client/gui/widget/ForgeSlider.java]: Maybe to you, but the point of JDoc is not that the values don't need documentation if they are self-explanatory, but you know to document them.

File: src/main/java/net/minecraftforge/client/gui/widget/ForgeSlider.java [hunk 3]
```diff
@@ -0,0 +1,220 @@
...
+     * @param suffix {@link Component} displayed after the value string
+     * @param minValue Minimum (left) value of slider
+     * @param maxValue Maximum (right) value of slider
+     * @param currentValue Starting value when widget is first displayed
+     * @param stepSize Size of step used. Precision will automatically be calculated based on this value if this value is not 0.
+     * @param precision Only used when {@code stepSize} is 0. Limited to a maximum of 4 (inclusive).
+     * @param drawString Should text be displayed on the widget
+     */
+    public ForgeSlider(int x, int y, int width, int height, Component prefix, Component suffix, double minValue, double maxValue, double currentValue, double stepSize, int precision, boolean drawString)
+    {
```
Comment (marchermans) [inline src/main/java/net/minecraftforge/client/gui/widget/ForgeSlider.java:49]: Although this is still not a very nice javadoc, I will take it for now.

**Review by marchermans — APPROVED** [review]
