### PR TITLE
[1.19.4+] Revamp and fix spawn events

### LINKED ISSUE #8404: Canceling LivingSpawnEvent.SpecialSpawn does not prevent mob spawn
**Minecraft Version:** 1.18.1

**Forge Version:** 39.0.44

**Steps to Reproduce:**
 1. Create a LivingSpawnEvent.SpecialSpawn listener method. Have it cancel.

    @SubscribeEvent
    public static void livingSpawnEvent$SpecialSpawnListener(final LivingSpawnEvent.SpecialSpawn event){
        event.setCanceled(true);
    }

Issue:
All spawns that should be prevented by canceling this event still occur.

I originally noticed this while canceling skeleton spawns and noticing they were still spawning, just without bows, presumably because the finalizeSpawn function where the bow is given to skeleton wasn't being reached.

### LINKED ISSUE #9117: [1.18.2] [1.19.2] Scope for call to ForgeEventFactory.doSpecialSpawn in NaturalSpawner seems wrong
**Minecraft Version:** 1.18.2 and 1.19.2

**Forge Version:** 40.1.80 for 1.18.2 and 43.1.32 for 1.19.2

**Logs:**
n.a.

**Steps to Reproduce:**
n.a.

**Description of issue:**
It appears like the insertion of the ForgeEventFactory.doSpecialSpawn call in NaturalSpawner is wrong. It looks like this:

```
                           if (!net.minecraftforge.event.ForgeEventFactory.doSpecialSpawn(mob, (LevelAccessor) p_47040_, (float)d0, (float)i, (float)d1, null, MobSpawnType.NATURAL))
                           spawngroupdata = mob.finalizeSpawn(p_47040_, p_47040_.getCurrentDifficultyAt(mob.blockPosition()), MobSpawnType.NATURAL, spawngroupdata, (CompoundTag)null);
                           ++j;
                           ++l1;
                           p_47040_.addFreshEntityWithPassengers(mob);
                           p_47044_.run(mob, p_47041_);
                           if (j >= net.minecraftforge.event.ForgeEventFactory.getMaxSpawnPackSize(mob)) {
                              return;
                           }
```

So when the special spawn is canceled by a mod only the finalizeSpawn will not be executed. The rest of the code is still executed as if the mob should spawn. This seems wrong

### PR DESCRIPTION
**Pull request by Shadows-of-Fire**
## Purpose
This PR seeks to accomplish the following goals:
1. Increase the scope of actions that modders can take based on when entities spawn.
2. Increase the scope of actions that modders can take based on the type of spawn an entity originated from.
3. Provide a simple pipeline for modders to cancel specific spawns, without resorting to multi-event chaining by the modder.
4. Reduce the maintenance burden of the spawn events.
5. Increase the reliability that all mob spawns can be detected in an event-driven manner, while adhering to (4).

## Motivation
The current spawn events, `SpecialSpawn` and `CheckSpawn`, are lacking in various areas, and have a high maintenance burden.  Specifically, they do not meet the contracts that they outline (`SpecialSpawn` does not fire in all locations, `CheckSpawn` does not permit changing the spawn rules as it stipulates in all but one case), and they require extensive patches to implement correctly, as each location in the vanilla code base that spawns an entity must be patched with both of these events.  Additionally, `SpecialSpawn`, the primary driver for spawn events, does not receive all the context of `Mob#finalizeSpawn`, which is the relevant data for the spawn occuring.

##  Solution
This PR proposes the new event `FinalizeSpawn`, which receives all the context of `Mob#finalizeSpawn`, with the means to mutate that data, and cancel the spawn without resorting to multi-event chaining on the modder's side.  Importantly, this event allows modders to differentiate between cancellation of the `Mob#finalizeSpawn` call, and cancellation of the actual spawn.  The former is critical for adding additional gear to entities, as if the finalize cannot be cancelled, vanilla _may_ override added gear with base gear items. This is not currently possible due to the incorrect implementation of `SpecialSpawn`, where in some instances, cancellation fully cancels the spawn.

Addition of the missing context objects (noting that `MobSpawnType` and `BaseSpawner` were already present), `DifficultyInstance`, `SpawnGroupType`, `CompoundTag`, allow modders to change certain aspects of an entity spawn based on external factors. What can be changed with these fields is different for each entity.
For example, we can utilize these new fields to guarantee that zombies spawn as baby zombies, or forcibly enable chicken spawn jockeys.

Finally, there will be an additional field on `Mob`, which will hold the spawn type for the lifetime of the entity.  This allows for processing based on the entity's spawn type later in the lifetime of the entity, such as adding specific entity drops if the mob was naturally spawned. Implementing a feature like this currently requires manually recording the spawn type on every entity, and it is not reliable, due to the issues outlined earlier.

The `FinalizeSpawn` event is injected with a coremod, and has the injection targets determined automatically with a gradle plugin. This means the patch surface is drastically reduced, and new injection targets will be found as they are added.  This means there will be no missed targets, and each new version will not require manual scrubbing of call sites to ensure coverage.

## Footnotes
Fixes https://github.com/MinecraftForge/MinecraftForge/issues/8404 
Fixes https://github.com/MinecraftForge/MinecraftForge/issues/9117

### CODE REVIEW

File: src/main/java/net/minecraftforge/event/ForgeEventFactory.java [hunk 1]
```diff
@@ -185,18 +189,41 @@ public static void onPlayerDestroyItem(Player player, @NotNull ItemStack stack,
         MinecraftForge.EVENT_BUS.post(new PlayerDestroyItemEvent(player, stack, hand));
     }
 
-    public static Result canEntitySpawn(Mob entity, LevelAccessor level, double x, double y, double z, BaseSpawner spawner, MobSpawnType spawnReason)
+    /**
+     * Vanilla calls to {@link Mob#finalizeSpawn} are replaced with calls to this method via coremod.<p>
+     * Mods should call this method in place of calling {@link Mob#finalizeSpawn}. Super calls (from within overrides) should not be wrapped.
```
Comment (Thelnfamous1) [inline src/main/java/net/minecraftforge/event/ForgeEventFactory.java:194]: So to clarify, modders should still override finalizeSpawn for their own mobs as the coremod will automatically wrap vanilla calls of it, and if they ever manually call finalizeSpawn anywhere in their implementation, they should change it to call this hook instead?

Comment (Shadows-of-Fire) [reply src/main/java/net/minecraftforge/event/ForgeEventFactory.java:194]: Correct.

File: patches/minecraft/net/minecraft/world/entity/npc/CatSpawner.java.patch [hunk 2]
```diff
@@ -1,11 +1,10 @@
 --- a/net/minecraft/world/entity/npc/CatSpawner.java
 +++ b/net/minecraft/world/entity/npc/CatSpawner.java
-@@ -86,8 +_,9 @@
+@@ -86,8 +_,8 @@
        if (cat == null) {
           return 0;
        } else {
 +         cat.m_20035_(p_35334_, 0.0F, 0.0F); // Fix MC-147659: Some witch huts spawn the incorrect cat
```
Comment (eerussianguy) [inline patches/minecraft/net/minecraft/world/entity/npc/CatSpawner.java.patch:7]: Re: this discussion in discord.
https://discord.com/channels/313125603924639766/852298000042164244/1006758427491586209

We are not sure that this comment is valid anymore

**Comment by Shadows-of-Fire** [comment]
PR Rebased to 1.19.3.  Additionally, a new method of blocking spawns via `FinalizeSpawn` has been implemented, such that users will not need to resort to a "flag-and-cancel" workflow between `FinalizeSpawn` and `EntityJoinLevelEvent`.

**Comment by Shadows-of-Fire** [comment]
Conflicts resolved again

File: src/main/java/net/minecraftforge/event/entity/living/MobSpawnEvent.java [hunk 3]
```diff
@@ -0,0 +1,236 @@
...
+ * The subclasses of this event are fired whenever a mob performs a spawning-related action.
+ */
+public abstract class MobSpawnEvent extends EntityEvent
+{
+    private final ServerLevelAccessor level;
+    private final double x;
+    private final double y;
+    private final double z;
+
+    public MobSpawnEvent(Mob mob, ServerLevelAccessor level, double x, double y, double z)
```
Comment (sciwhiz12) [inline src/main/java/net/minecraftforge/event/entity/living/MobSpawnEvent.java:39]: Mark this event constructor with `@ApiStatus.Internal`.

File: src/main/resources/coremods/method_redirector.js [hunk 4]
```diff
@@ -0,0 +1,77 @@
...
+        "onFinalizeSpawn", 
+        "(Lnet/minecraft/world/entity/Mob;Lnet/minecraft/world/level/ServerLevelAccessor;Lnet/minecraft/world/DifficultyInstance;Lnet/minecraft/world/entity/MobSpawnType;Lnet/minecraft/world/entity/SpawnGroupData;Lnet/minecraft/nbt/CompoundTag;)Lnet/minecraft/world/entity/SpawnGroupData;", 
+        false);
+}
+
+function contains(list, target) {
+	for(var i = 0; i < list.length; i++) {
+		if(list[i] == target) return true;
+	}
+	return false;
```
Comment (sciwhiz12) [inline src/main/resources/coremods/method_redirector.js]: Formatting: 4 spaces for indentation.
```suggestion
    for(var i = 0; i < list.length; i++) {
        if(list[i] == target) return true;
    }
    return false;
```

File: src/main/resources/coremods/method_redirector.js [hunk 5]
```diff
@@ -0,0 +1,77 @@
...
+
+function initializeCoreMod() {
+    var mergedTargets = [];
+    for(var i = 0; i < replacements.length; i++){
+        var r = replacements[i];
+		r.targets = ASMAPI.loadData(r.targets);
+		for(var k = 0; k < r.targets.length; k++){
+			mergedTargets.push(r.targets[k]);
+		}
+	}
```
Comment (sciwhiz12) [inline src/main/resources/coremods/method_redirector.js]: Formatting: 4 spaces for indentation.
```suggestion
        r.targets = ASMAPI.loadData(r.targets);
        for(var k = 0; k < r.targets.length; k++){
            mergedTargets.push(r.targets[k]);
        }
    }
```

**Review by sciwhiz12 — CHANGES_REQUESTED** [review]

File: src/main/java/net/minecraftforge/event/entity/living/MobSpawnEvent.java [hunk 6]
```diff
@@ -0,0 +1,238 @@
...
+
+        /**
+         * This method can be used to fully cancel the spawn of this mob.<p>
+         * This method must be used if you want to block the spawn, as canceling the event only blocks the call to {@link Mob#finalizeSpawn}.<p>
+         * Note that if this is cancelled, but the event is not, than {@link Mob#finalizeSpawn} will still be called, but the entity will not be spawned.
+         * Usually that has no side effects, but callers should be aware.
+         * @param cancel If the spawn should be cancelled (or not).
+         */
+        public void setSpawnCancelled(boolean cancel) {
+        	this.getEntity().setSpawnCancelled(cancel);
```
Comment (sciwhiz12) [inline src/main/java/net/minecraftforge/event/entity/living/MobSpawnEvent.java]: Formatting: 4 spaces, not tabs.
```suggestion
            this.getEntity().setSpawnCancelled(cancel);
```

File: src/main/java/net/minecraftforge/event/entity/living/MobSpawnEvent.java [hunk 7]
```diff
@@ -0,0 +1,238 @@
...
+        }
+
+        /**
+         * Returns the current spawn cancellation status, which can be changed via {@link FinalizeSpawn#setSpawnCancelled(boolean)}.
+         * @return If this mob's spawn is cancelled or not.
+         */
+        public boolean isSpawnCancelled() {
+        	return this.getEntity().isSpawnCancelled();
```
Comment (sciwhiz12) [inline src/main/java/net/minecraftforge/event/entity/living/MobSpawnEvent.java]:
```suggestion
        Formatting: 4 spaces, not tabs.return this.getEntity().isSpawnCancelled();
```

**Review by sciwhiz12 — CHANGES_REQUESTED** [review]

**Comment by Shadows-of-Fire** [comment]
Formatting fixed

File: src/main/java/net/minecraftforge/common/ForgeInternalHandler.java [hunk 8]
```diff
@@ -135,5 +136,14 @@ public void resourceReloadListeners(AddReloadListenerEvent event)
         event.addListener(TierSortingRegistry.getReloadListener());
         event.addListener(CreativeModeTabRegistry.getReloadListener());
     }
+
+    @SubscribeEvent(priority = EventPriority.HIGHEST)
+    public void builtinMobSpawnBlocker(EntityJoinLevelEvent event)
+    {
+        if(event.getEntity() instanceof Mob mob && mob.isSpawnCancelled())
```
Comment (sm00ter) [inline src/main/java/net/minecraftforge/common/ForgeInternalHandler.java:143]: This may be incorrect. `mob` is being assigned to the boolean value of the instance check. Then calling `isSpawnCancelled()`. I don't have the repo locally, nor any Java experience, but I do have 10 years of PHP experience. Got an error and this is where it lead me.

I'd imagine something like this should do the trick

```java
var mob = event.getEntity();
if (mob instanceof Mob && mob.isSpawnCancelled()) {
    event.setCanceled(true);
}
```

**Review by sm00ter — COMMENTED** [review]
[crash-2023-03-23_16.03.37-server.txt](https://github.com/MinecraftForge/MinecraftForge/files/11056821/crash-2023-03-23_16.03.37-server.txt)

Potentially found the solution to this error I received after installing forge 45.0.23

File: src/main/java/net/minecraftforge/common/ForgeInternalHandler.java (hunk 8 above)
Comment (sm00ter) [reply src/main/java/net/minecraftforge/common/ForgeInternalHandler.java:143]:
```suggestion
    var mob = event.getEntity();
    if (mob instanceof Mob && mob.isSpawnCancelled())
```

Comment (Shadows-of-Fire) [reply src/main/java/net/minecraftforge/common/ForgeInternalHandler.java:143]: Given the statement `event.getEntity() instanceof Mob mob`, mob will be equivalent to `event.getEntity()` if the `instanceof` check passes, but with the cast already applied. If the `instanceof` fails, then `mob` will never be assigned, and the if statement will short-circuit.

Comment (tmvkrpxl0) [reply src/main/java/net/minecraftforge/common/ForgeInternalHandler.java:143]: No, this syntax is shorthand version of your suggestion. They are functionally same.

Comment (TheCurle) [reply src/main/java/net/minecraftforge/common/ForgeInternalHandler.java:143]: The problem is Optifine undoing this change.

Remove it.
