### PR TITLE
Fixed forge rendering pipeline and shape based light occulsion.

### LINKED ISSUE #6174: Forge Render Pipeline doesn't work with shape based light occlusion.
When the `forgeLightPipelineEnabled` is enabled, Blocks that use shape based light don't render correctly. 

## Testing
Result when `forgeLightPipelineEnabled` is true:
image

Result when `forgeLightPipelineEnabled` is false:
image

### PR DESCRIPTION
**Pull request by Wyn-Price**
Fixes #6174

The logic behind `doesSideBlockRendering` doesn't really work with shape based light occlusion. It currently just returns whether the block is an opaque cube, which now doesn't necessarily mean it blocks light. A stone slab isn't an opaque cube, but may not block, depending on what shapes are around it. 

The new logic is esssentially what the light engines use for checking whether a side lets light through or not. 

`doesSideBlockRendering` isn't actually used anymore, so I've put a `@Deprecated` on it.

### CODE REVIEW

File: src/main/java/net/minecraftforge/common/extensions/IForgeBlockState.java [hunk 1]
```diff
@@ -113,6 +113,7 @@ default boolean isLadder(IWorldReader world, BlockPos pos, LivingEntity entity)
      * @param face The side to check
      * @return True if the block is opaque on the specified side.
      */
+    @Deprecated
```
Comment (ichttt) [inline src/main/java/net/minecraftforge/common/extensions/IForgeBlockState.java:118]: Maybe stick a comment here to explain why this is no longer needed, and a TODO to remove this in 1.15

**Review by ichttt — COMMENTED** [review]
This looks good, just a minor nitpick

**Comment by LexManos** [comment]
So, looking into this, removing the doesSideBlockRendering does not seem to be the proper solution.
According to vanilla code it checks LightEngine.getBlockAndOpacity, and then uses the block opacity, combined with the voxel shape to determine if light should propagate. 
There are cases, such as glass, where the voxel shape would be solid on the side, but light should still get through.

Also, in this case, screenshots illustrating the cases in which you are attempting to fix, would be useful.

**Comment by Wyn-Price** [comment]
So from what I can tell, to determin shape based occlusion is essentially:
 - If the states opacity is 15 (fully transparent), then don't bother checking the shapes. 
 - Get both the state and the offset state, and check  `isSolid` and `func_215704_f (useShapeForLightOcclusion)`. If true, then use the given state for shape checking, otherwise use air.
 - If the voxel shapes of the states combine to fully fill the side (`VoxelShapes.func_223416_b (faceShapeOccludes)`), then that side is considered solid.

I've modified the code to reflect this.

Vanilla Pipeline:
image
Current Forge Pipeline:
image
Changes with this PR:
image
