### PR TITLE
Merge values of defaulted optional tags

### LINKED ISSUE #7570: Add toString method to vanilla Tag class
Because this error is not verbose is suggest adding some information to the Tag instance:

```
java.lang.IllegalStateException: Duplicate key net.minecraft.tags.Tag@35be503c
	at java.util.stream.Collectors.lambda$throwingMerger$0(Unknown Source) ~[?:1.8.0_211] {}
	at java.util.HashMap.merge(Unknown Source) ~[?:1.8.0_211] {}
	at java.util.stream.Collectors.lambda$toMap$58(Unknown Source) ~[?:1.8.0_211] {}
	at java.util.stream.ReduceOps$3ReducingSink.accept(Unknown Source) ~[?:1.8.0_211] {}
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_211] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_211] {}
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_211] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_211] {}
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_211] {}
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_211] {}
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_211] {}
	at net.minecraft.tags.TagRegistry.reinjectOptionalTags(TagRegistry.java:89) ~[forge-1.16.4-35.1.7_mapped_snapshot_20201028-1.16.3-recomp.jar:?] {re:classloading}
	at net.minecraft.tags.ITagCollectionSupplier.reinjectOptionalTags(ITagCollectionSupplier.java:66) ~[forge-1.16.4-35.1.7_mapped_snapshot_20201028-1.16.3-recomp.jar:?] {re:classloading}
```

### PR DESCRIPTION
**Pull request by sciwhiz12**
This PR fixes #7570 by merging the default values of a defaulted optional tag when defined in multiple places (whether within the same mod or across multiple mods). For more details as why the linked issue happens and why this solution fixes it, see my comment at https://github.com/MinecraftForge/MinecraftForge/issues/7570#issuecomment-978902329.

### CODE REVIEW

File: patches/minecraft/net/minecraft/tags/StaticTagHelper.java.patch [hunk 1]
```diff
@@ -63,7 +63,7 @@
 +         OptionalNamedTag<T> optionalNamedTag = (OptionalNamedTag<T>) namedTag;
 +         optionalNamedTag.defaulted = true;
 +         return optionalNamedTag.resolveDefaulted();
-+      }));
++      }, (existingTag, newTag) -> SetTag.m_13222_(com.google.common.collect.ImmutableSet.<T>builder().addAll(existingTag.m_6497_()).addAll(newTag.m_6497_()).build())));
```
Comment (pupnewfster) [inline patches/minecraft/net/minecraft/tags/StaticTagHelper.java.patch]: Part of me wonders if it might be worthwhile to only create a new tag if both tags are not empty and otherwise just use the one that isn't empty or just return either one if they are both empty, though honestly that might not really matter.

On another note something that definitely should be changed on this line for readability, is there is no need to be using the FQN for ImmutableSet as it is already imported due to vanilla using it in this class.

Comment (sciwhiz12) [reply patches/minecraft/net/minecraft/tags/StaticTagHelper.java.patch]: That would be worthwhile if we expect an optional tag to be referenced many times (by multiple mods) and be defaulted, as currently this would make N-1 `SetTag` instances for N (defaulted) optional tag references. But it doesn't seem to be a big enough problem to warrant optimizing that.

And I didn't notice that MC already imports `ImmutableSet`. :eyes: (I've been bitten by silent auto-importing of those in the past while adding to patched files, so I wanted to head off that trouble.)
