### PR TITLE
[1.19]: Fix performance issue and logging when resource caching is enabled

### LINKED ISSUE #9032: [1.19.2] - `cachePackAccess = true` increase (~1.8x) loading time of mod packs / debug.log spam
This is related to https://github.com/MinecraftForge/MinecraftForge/issues/8962 , there was the assumption that this is a 1.18.2 specific error.

It seems that this affects 1.19.2 as well, as I notice during some troubleshooting for an unrelated mod specific issue.

**Steps to Reproduce:**
 1. Load a huge mod pack with `cachePackAccess = true` and stop the client loading time / world loading
 2. Change `cachePackAccess = false` and stop the client loading time / world loading
 3. Compare the two loading times.

**Description of issue:**
`cachePackAccess = true` ~ 00:04:27.575 min client loading + 00:02:11.218 min world loading
`cachePackAccess = false` ~ 00:02:28.233 min client loading + 00:02:41.922 min world loading

**Example Mod Pack:**
https://www.curseforge.com/minecraft/modpacks/friends-united

**Symphtoms:**
Loading client / overall time is increased, not the same like for 1.18.2, but still very noticeable.

Same log spam in the debug.log like:
```
[11Sep2022 17:49:35.352] [Worker-Main-12/DEBUG] [net.minecraftforge.resource.ResourceCacheManager$NamespacedResourceCacheManager/]: Failed to cache resources, the directory does not exist!
cpw.mods.niofs.union.UnionFileSystem$NoSuchFileException: /data/comforts
[11Sep2022 17:49:35.352] [Worker-Main-1/DEBUG] [net.minecraftforge.resource.ResourceCacheManager$NamespacedResourceCacheManager/]: Failed to cache resources, the directory does not exist!
cpw.mods.niofs.union.UnionFileSystem$NoSuchFileException: /assets/comforts
[11Sep2022 17:49:35.352] [Worker-Main-6/DEBUG] [net.minecraftforge.resource.ResourceCacheManager$NamespacedResourceCacheManager/]: Failed to cache resources, the directory does not exist!
cpw.mods.niofs.union.UnionFileSystem$NoSuchFileException: /data/comforts
[11Sep2022 17:49:35.352] [Worker-Main-10/DEBUG] [net.minecraftforge.resource.ResourceCacheManager$NamespacedResourceCacheManager/]: Failed to cache resources, the directory does not exist!
cpw.mods.niofs.union.UnionFileSystem$NoSuchFileException: /assets/comforts
[11Sep2022 17:49:35.352] [Worker-Main-13/DEBUG] [net.minecraftforge.resource.ResourceCacheManager$NamespacedResourceCacheManager/]: Failed to cache resources, the directory does not exist!
cpw.mods.niofs.union.UnionFileSystem$NoSuchFileException: /data/comforts
[11Sep2022 17:49:35.352] [Worker-Main-6/DEBUG] [net.minecraftforge.resource.ResourceCacheManager$NamespacedResourceCacheManager/]: Failed to cache resources, the directory does not exist!
cpw.mods.niofs.union.UnionFileSystem$NoSuchFileException: /assets/configured
[11Sep2022 17:49:35.352] [Worker-Main-7/DEBUG] [net.minecraftforge.resource.ResourceCacheManager$NamespacedResourceCacheManager/]: Failed to cache resources, the directory does not exist!
cpw.mods.niofs.union.UnionFileSystem$NoSuchFileException: /assets/comforts
[11Sep2022 17:49:35.352] [Worker-Main-8/DEBUG] [net.minecraftforge.resource.ResourceCacheManager$NamespacedResourceCacheManager/]: Failed to cache resources, the directory does not exist!
cpw.mods.niofs.union.UnionFileSystem$NoSuchFileException: /assets/comforts
[11Sep2022 17:49:35.352] [Worker-Main-1/DEBUG] [net.minecraftforge.resource.ResourceCacheManager$NamespacedResourceCacheManager/]: Failed to cache resources, the directory does not exist!
cpw.mods.niofs.union.UnionFileSystem$NoSuchFileException: /data/configured
[11Sep2022 17:49:35.352] [Worker-Main-12/DEBUG] [net.minecraftforge.resource.ResourceCacheManager$NamespacedResourceCacheManager/]: Failed to cache resources, the directory does not exist!
cpw.mods.niofs.union.UnionFileSystem$NoSuchFileException: /assets/configured
[11Sep2022 17:49:35.352] [Worker-Main-12/DEBUG] [net.minecraftforge.resource.ResourceCacheManager$NamespacedResourceCacheManager/]: Failed to cache resources, the directory does not exist!
cpw.mods.niofs.union.UnionFileSystem$NoSuchFileException: /data/configured
[11Sep2022 17:49:35.352] [Worker-Main-12/DEBUG] [net.minecraftforge.resource.ResourceCacheManager$NamespacedResourceCacheManager/]: Failed to cache resources, the directory does not exist!
cpw.mods.niofs.union.UnionFileSystem$NoSuchFileException: /assets/configured
[11Sep2022 17:49:35.352] [Worker-Main-11/DEBUG] [net.minecraftforge.resource.ResourceCacheManager$NamespacedResourceCacheManager/]: Failed to cache resources, the directory does not exist!
cpw.mods.niofs.union.UnionFileSystem$NoSuchFileException: /assets/configured
[11Sep2022 17:49:35.352] [Worker-Main-14/DEBUG] [net.minecraftforge.resource.ResourceCacheManager$NamespacedResourceCacheManager/]: Failed to cache resources, the directory does not exist!
cpw.mods.niofs.union.UnionFileSystem$NoSuchFileException: /assets/comforts
[11Sep2022 17:49:35.352] [Worker-Main-4/DEBUG] [net.minecraftforge.resource.ResourceCacheManager$NamespacedResourceCacheManager/]: Failed to cache resources, the directory does not exist!
cpw.mods.niofs.union.UnionFileSystem$NoSuchFileException: /data/comforts
[11Sep2022 17:49:35.352] [Worker-Main-9/DEBUG] [net.minecraftforge.resource.ResourceCacheManager$NamespacedResourceCacheManager/]: Failed to cache resources, the directory does not exist!
cpw.mods.niofs.union.UnionFileSystem$NoSuchFileException: /data/comforts
[11Sep2022 17:49:35.352] [Worker-Main-3/DEBUG] [net.minecraftforge.resource.ResourceCacheManager$NamespacedResourceCacheManager/]: Failed to cache resources, the directory does not exist!
cpw.mods.niofs.union.UnionFileSystem$NoSuchFileException: /assets/comforts
[11Sep2022 17:49:35.352] [Worker-Main-4/DEBUG] [net.minecraftforge.resource.ResourceCacheManager$NamespacedResourceCacheManager/]: Failed to cache resources, the directory does not exist!
cpw.mods.niofs.union.UnionFileSystem$NoSuchFileException: /assets/configured
[11Sep2022 17:49:35.352] [Worker-Main-5/DEBUG] [net.minecraftforge.resource.ResourceCacheManager$NamespacedResourceCacheManager/]: Failed to cache resources, the directory does not exist!
cpw.mods.niofs.union.UnionFileSystem$NoSuchFileException: /assets/comforts
```

The issue should be easy to reproduce over the provided mod pack (was able to reproduce it on 2 different PC's), haven't tested other mod packs because I my own mods packs are still 1.18.2 yet.

**Notes:**
The mod pack use some world biomes mod which increases the loading time of the world data / world generation.
But because these mods delay time should be the same regardless of the `cachePackAccess` setting, this should be less relevant in this case.

### PR DESCRIPTION
**Pull request by marchermans**
### Fix:
- This fixes large `debug.log` files when resource caching is enabled.
- Performance degradation that occurs due to double indexing of the resource packs.

### Implemented:
- A new config loading system that properly loads the resource cache configuration data during the boot sequence
- A new logging marker to handle the large flow of potential logging data

### Changed:
- The logging infrastructure now logs all data using this marker.
- All internal classes should now be marked as being internal, making future changes easier.
- Configurations are now only registered if they are not empty.

### Removed:
- The fallback resource manager does invoke indexing when packs are pushed onto its ordered stack. The caller is responsible for enabling the pack resource initialization. _(By default vanilla does this now ahead of time anyway, just something modders need to pay attention to if they ever use the push methods on the fallback resource manager.)_

### Performance improvement
This PR fixes a major bug that relates to the fact that the index was forcefully created twice.
This was caused by the `FallBackResourceManager` invoking the initialize system twice. Once during initial registration and then once during sorting.

#### Resulting performance analysis:
After this change the numbers provided by @MarkusBordihn, which were verifyable, are now not anymore.
Using the pack he provided in #9032 I was able to verify that this fix now actually works:
**Startup time with caching disabled: 04:49**
**Startup time with caching enabled:  03:55**
Both tests were performed with several warmup runs before to filter out things like config creation etc.

### Log marker
A log marker was added to enable easy management of the logging data that is generated by the system.
By default this marker is disabled.

Closes #9032

### CODE REVIEW

File: src/main/java/net/minecraftforge/common/ForgeConfig.java [hunk 1]
```diff
@@ -109,6 +110,11 @@ public static class Common {
                     .worldRestart()
                     .define("indexModPackCachesOnThread", false);
 
+            logMissingDirectoriesToDebugDuringResourceCaching = builder
+                    .comment("Set this to true to log missing directories (found during resource caching) to debug, instead of discarding the information. Note this can cause large log files in large mod packs.")
+                    .translation("forge.configgui.logMissingDirectoriesToDebugDuringResourceCaching")
+                    .worldRestart()
+                    .define("logMissingDirectoriesToDebugDuringResourceCaching", false);
```
Comment (sciwhiz12) [inline src/main/java/net/minecraftforge/common/ForgeConfig.java]: What is the usefulness of this logging statement to debugging? As in, is this useful enough that it would merit its own dedicated config entry? 

I do not think it would be appropriate to elevate this to a Forge config setting if there is no significant usefulness for users to modify this setting. Even then, why would it not be more appropriate to use a logging marker, with the logging configuration adjusted to allow a system property to control it, [as we already do for 14 other markers](https://github.com/MinecraftForge/MinecraftForge/blob/b0caea8e204a7f026646396558d6d58a02bff9d6/fmlloader/src/main/resources/log4j2.xml#L5-L18)?

**Review by sciwhiz12 — CHANGES_REQUESTED** [review]

File: src/main/java/net/minecraftforge/common/ForgeConfig.java (hunk 1 above)
Comment (marchermans) [reply src/main/java/net/minecraftforge/common/ForgeConfig.java]: Changed it now to a marker and a different setup anyway.

**Comment by marchermans** [comment]
@sciwhiz12 Should be ready for review now.

File: fmlloader/src/main/resources/log4j2.xml [hunk 2]
```diff
@@ -13,6 +13,8 @@
         <MarkerFilter marker="REGISTRIES" onMatch="${sys:forge.logging.marker.registries:-DENY}" onMismatch="NEUTRAL"/>
         <MarkerFilter marker="REGISTRYDUMP" onMatch="${sys:forge.logging.marker.registrydump:-DENY}" onMismatch="NEUTRAL"/>
         <MarkerFilter marker="SPLASH" onMatch="${sys:forge.logging.marker.splash:-DENY}" onMismatch="NEUTRAL"/>
+        <MarkerFilter marker="BOOT-CONFIG" onMatch="${sys:forge.logging.marker.boot.config:-DENY}" onMismatch="NEUTRAL"/>
```
Comment (sciwhiz12) [inline fmlloader/src/main/resources/log4j2.xml]: Where is the boot config now?

File: src/main/java/net/minecraftforge/common/ForgeConfig.java [hunk 3]
```diff
@@ -82,29 +82,34 @@ public static class Server {
     /**
      * General configuration that doesn't need to be synchronized but needs to be available before server startup
      */
+    @Deprecated(since = "1.19", forRemoval = true)
```
Comment (sciwhiz12) [inline src/main/java/net/minecraftforge/common/ForgeConfig.java]: This is being deprecated in 1.19.2 (and same comment for the rest of the deprecations in here).
```suggestion
    @Deprecated(since = "1.19.2", forRemoval = true)
```

File: src/main/java/net/minecraftforge/common/ForgeConfig.java [hunk 4]
```diff
@@ -82,29 +82,34 @@ public static class Server {
...
         public final BooleanValue cachePackAccess;
+        @Deprecated(since = "1.19", forRemoval = true)
         public final BooleanValue indexVanillaPackCachesOnThread;
+        @Deprecated(since = "1.19", forRemoval = true)
         public final BooleanValue indexModPackCachesOnThread;
 
+        @Deprecated(since = "1.19", forRemoval = true)
         Common(ForgeConfigSpec.Builder builder) {
-            builder.comment("General configuration settings")
+            builder.comment("[DEPRECATED]:General configuration settings")
```
Comment (sciwhiz12) [inline src/main/java/net/minecraftforge/common/ForgeConfig.java]: Changing the comments would cause the configs to be corrected I believe...? Also, the comments should reflect somewhere that these config options have no effect now, and that the configuration for resource caching has been moved to a separate config file.

File: src/main/java/net/minecraftforge/resource/ResourceCacheManager.java [hunk 5]
```diff
@@ -6,32 +6,32 @@
...
 import java.nio.file.NoSuchFileException;
 import java.nio.file.Path;
-import java.util.ArrayList;
-import java.util.Collection;
-import java.util.Collections;
-import java.util.List;
-import java.util.Map;
-import java.util.Set;
+import java.nio.file.StandardOpenOption;
+import java.util.*;
```
Comment (sciwhiz12) [inline src/main/java/net/minecraftforge/resource/ResourceCacheManager.java]: No wildcard imports.

File: src/main/java/net/minecraftforge/resource/ResourceCacheManager.java [hunk 6]
```diff
@@ -40,8 +40,12 @@
  * <p>
  * This class handles caching the resource listing calls on a pack, pack type and namespace level.
  */
-public class ResourceCacheManager
-{
+@ApiStatus.Internal
+public class ResourceCacheManager {
```
Comment (sciwhiz12) [inline src/main/java/net/minecraftforge/resource/ResourceCacheManager.java]: Please fix all of these unwanted brace changes in this class, as well as the braces in newly-added code.

File: src/main/java/net/minecraftforge/resource/ResourceCacheManager.java [hunk 7]
```diff
@@ -69,54 +73,81 @@
...
+                                "# This file is read by the Forge boot loader, and is not used by the game itself.",
+                                "#",
+                                "# Set this to false to disable the resource cache. This will cause the game to scan the resource packs everytime it needs a list of resources.",
+                                "cacheResources=true",
+                                "",
+                                "# Set this to false to forge the caching of vanilla resources to happen on the main thread.",
+                                "indexVanillaPackCachesOnThread=false",
+                                "",
+                                "# Set this to false to forge the caching of mod resources to happen on the main thread.",
+                                "indexModPackCachesOnThread=false"
```
Comment (sciwhiz12) [inline src/main/java/net/minecraftforge/resource/ResourceCacheManager.java]: Hardcoding this to be in the manager itself and written out instead of storing a text file resource to be copied is a bit... dirty to me. [We use a resource for the FML config](https://github.com/MinecraftForge/MinecraftForge/blob/b0caea8e204a7f026646396558d6d58a02bff9d6/fmlloader/src/main/java/net/minecraftforge/fml/loading/FMLConfig.java#L40), so why not here as well?

File: src/main/java/net/minecraftforge/resource/ResourceCacheManager.java [hunk 8]
```diff
@@ -69,54 +73,81 @@
...
+                        ),
+                        StandardOpenOption.CREATE_NEW);
+            } catch (IOException e) {
+                throw new RuntimeException("Failed to create the default boot configuration file.", e);
+            }
+        }
+
+        final List<String> lines;
+        try {
+            lines = Files.readAllLines(configPath);
```
Comment (sciwhiz12) [inline src/main/java/net/minecraftforge/resource/ResourceCacheManager.java]: This would mean we read the config file each time in full every time we query it. How many times do we query the config file?

File: src/main/java/net/minecraftforge/resource/ResourceCacheManager.java [hunk 9]
```diff
@@ -69,54 +73,81 @@
...
+        } catch (IOException e) {
+            throw new RuntimeException("Failed to read the boot configuration file.", e);
         }
+
+        for (final String line : lines) {
+            final String trimmedLine = line.trim().replace(" ", "");
+            if (trimmedLine.startsWith(configKey)) {
+                return Boolean.parseBoolean(trimmedLine.substring(trimmedLine.indexOf('=') + 1));
+            }
+        }
```
Comment (sciwhiz12) [inline src/main/java/net/minecraftforge/resource/ResourceCacheManager.java]: This manual parsing of a config file pains me. Do we have no other preferred alternative?

File: src/main/java/net/minecraftforge/resource/ResourceCacheManager.java [hunk 10]
```diff
@@ -69,54 +73,81 @@
...
+        try {
+            lines = Files.readAllLines(configPath);
+        } catch (IOException e) {
+            throw new RuntimeException("Failed to read the boot configuration file.", e);
         }
+
+        for (final String line : lines) {
+            final String trimmedLine = line.trim().replace(" ", "");
+            if (trimmedLine.startsWith(configKey)) {
+                return Boolean.parseBoolean(trimmedLine.substring(trimmedLine.indexOf('=') + 1));
```
Comment (sciwhiz12) [inline src/main/java/net/minecraftforge/resource/ResourceCacheManager.java]: What would happen if the line does not contain an equals sign?

File: src/main/java/net/minecraftforge/resource/ResourceCacheManager.java [hunk 11]
```diff
@@ -187,21 +214,28 @@ public Set<String> getNamespaces(final PackType type)
...
     }
 
+    /**
+     * Functional callback interface to get a walkable stream of paths.
+     * Supports throwing {@link IOException} if the stream can not be created.
+     */
+    @FunctionalInterface
+    private interface PathWalkerFactory {
+        Stream<Path> createWalkingStream(Path path) throws IOException;
+    }
```
Comment (sciwhiz12) [inline src/main/java/net/minecraftforge/resource/ResourceCacheManager.java]: Why was this moved?

File: src/main/java/net/minecraftforge/resource/ResourceCacheManager.java [hunk 12]
```diff
@@ -257,35 +289,31 @@ private record ResourceCacheEntry(PackType packType, String namespace, Path path
...
+         * @param pathBuilder         The path builder to use.
+         * @param pathFinder          The path walker stream factory to use.
          */
-        private NamespacedResourceCacheManager(final PackType packType, final String namespace, final boolean indexOffThread, BiFunction<PackType, String, Path> pathBuilder, final PathWalkerFactory pathFinder)
-        {
+        private NamespacedResourceCacheManager(final PackType packType, final String namespace, final boolean shouldIndexOnThread, BiFunction<PackType, String, Path> pathBuilder, final PathWalkerFactory pathFinder) {
             this.packType = packType;
             this.namespace = namespace;
-            this.indexOffThread = indexOffThread;
+            this.indexOnThread = shouldIndexOnThread;
```
Comment (sciwhiz12) [inline src/main/java/net/minecraftforge/resource/ResourceCacheManager.java]: Why do the field and parameter not match in names?

File: src/main/java/net/minecraftforge/resource/ResourceCacheManager.java [hunk 13]
```diff
@@ -40,8 +40,12 @@
...
  * This class handles caching the resource listing calls on a pack, pack type and namespace level.
  */
-public class ResourceCacheManager
-{
+@ApiStatus.Internal
+public class ResourceCacheManager {
+    /**
+     * Logging marker to handle the hiding of the entries from the debug file.
+     */
+    private static final Marker RESOURCE_CACHE_MARKER = MarkerFactory.getMarker("RESOURCE-CACHE");
```
Comment (sciwhiz12) [inline src/main/java/net/minecraftforge/resource/ResourceCacheManager.java]: The marker does not need to be suffixed with `_MARKER`, as is done for all other markers in Forge code.
```suggestion
    private static final Marker RESOURCE_CACHE = MarkerFactory.getMarker("RESOURCE-CACHE");
```

File: src/fmllauncher/resources/log4j2.xml [hunk 14]
```diff
@@ -13,6 +13,8 @@
         <MarkerFilter marker="REGISTRIES" onMatch="${sys:forge.logging.marker.registries:-DENY}" onMismatch="NEUTRAL"/>
         <MarkerFilter marker="REGISTRYDUMP" onMatch="${sys:forge.logging.marker.registrydump:-DENY}" onMismatch="NEUTRAL"/>
         <MarkerFilter marker="SPLASH" onMatch="${sys:forge.logging.marker.splash:-DENY}" onMismatch="NEUTRAL"/>
+        <MarkerFilter marker="BOOT-CONFIG" onMatch="${sys:forge.logging.marker.boot-config:-DENY}" onMismatch="NEUTRAL"/>
```
Comment (sciwhiz12) [inline src/fmllauncher/resources/log4j2.xml]: Aside from the comment about the existence (or lack thereof) of the boot config, I do note that we should really remove this `fmllauncher` folder, since I believe this is leftover from pre-PEEL.

File: patches/minecraft/net/minecraft/server/packs/resources/FallbackResourceManager.java.patch [hunk 15]
```diff
@@ -1,12 +0,0 @@
---- a/net/minecraft/server/packs/resources/FallbackResourceManager.java
-+++ b/net/minecraft/server/packs/resources/FallbackResourceManager.java
-@@ -53,6 +_,9 @@
- 
-    private void m_215395_(String p_215396_, @Nullable PackResources p_215397_, @Nullable Predicate<ResourceLocation> p_215398_) {
-       this.f_10599_.add(new FallbackResourceManager.PackEntry(p_215396_, p_215397_, p_215398_));
-+      if (p_215397_ != null) {
-+         p_215397_.initForNamespace(this.f_10602_);
-+      }
```
Comment (sciwhiz12) [inline patches/minecraft/net/minecraft/server/packs/resources/FallbackResourceManager.java.patch:9]: Why was this patch removed?

**Review by sciwhiz12 — CHANGES_REQUESTED** [review]

File: src/main/java/net/minecraftforge/resource/ResourceCacheManager.java (hunk 7 above)
Comment (marchermans) [reply src/main/java/net/minecraftforge/resource/ResourceCacheManager.java]: This was what was requested by lex, not sure if it is such a good idea to hardcode.

The basic idea is to hide the fact that forge needs configs (and loads them) before mod loading as much as possible from modders, so that they do not try to load their own configs before registries are loaded.

I can make it a file, I don't care.

File: src/main/java/net/minecraftforge/resource/ResourceCacheManager.java (hunk 8 above)
Comment (marchermans) [reply src/main/java/net/minecraftforge/resource/ResourceCacheManager.java]: Yes that is correct 🤔 
It might be worth while to cache this, but I am not 100% on that.

The invocation count is very limited and it is already faster then without caching so not sure.
If I have the time I will look into it, but that would also mean that it would only update after a reboot of the game.

File: src/main/java/net/minecraftforge/resource/ResourceCacheManager.java (hunk 9 above)
Comment (marchermans) [reply src/main/java/net/minecraftforge/resource/ResourceCacheManager.java]: I had the ForgeBootConfigurationManager here which just made this an ForgeConfigSpec, but lex rejected that, because it was too obvious, this was his own recommendation.

File: src/main/java/net/minecraftforge/resource/ResourceCacheManager.java (hunk 11 above)
Comment (marchermans) [reply src/main/java/net/minecraftforge/resource/ResourceCacheManager.java]: I originally removed the interface, and then added it back.

File: src/fmllauncher/resources/log4j2.xml (hunk 14 above)
Comment (marchermans) [reply src/fmllauncher/resources/log4j2.xml]: Both config files are identical, and I am unable to determine effectively which is used at runtime, so I think it is better to keep them in sync until somebody checks them

File: patches/minecraft/net/minecraft/server/packs/resources/FallbackResourceManager.java.patch (hunk 15 above)
Comment (marchermans) [reply patches/minecraft/net/minecraft/server/packs/resources/FallbackResourceManager.java.patch:9]: See PR message, it was what was causing the performance degradation.
It is not needed, since the packs are already initialized when they get to this point, causing double initialization.

File: src/main/java/net/minecraftforge/resource/ResourceCacheManager.java (hunk 7 above)
Comment (marchermans) [reply src/main/java/net/minecraftforge/resource/ResourceCacheManager.java]: I will leave it a hardcode for now, should prevent people from being nut jobs and messing with it.

File: src/main/java/net/minecraftforge/resource/ResourceCacheManager.java (hunk 8 above)
Comment (marchermans) [reply src/main/java/net/minecraftforge/resource/ResourceCacheManager.java]: I will leave it like this for now.
Invocation count in a typical gameplay loop is minimal (less then 10 if you just start the game and open a world).

This allows hot reloads in case you refresh your resource packs with F3, without requiring additional code to handle it.

If specifically requested I can build it in, but I consider that overkill for the benefit it would get.

File: src/main/java/net/minecraftforge/resource/ResourceCacheManager.java (hunk 7 above)
Comment (sciwhiz12) [reply src/main/java/net/minecraftforge/resource/ResourceCacheManager.java]: Could you please elaborate on what you mean by "people [...] messing with it"? Additionally, please avoid the use of language such as "nut jobs", as it can be seen as disrespectful.

File: fmlcore/src/main/java/net/minecraftforge/fml/ModLoadingContext.java [hunk 16]
```diff
@@ -46,10 +51,24 @@ public <T extends Record & IExtensionPoint<T>> void registerExtensionPoint(Class
...
     }
 
     public void registerConfig(ModConfig.Type type, IConfigSpec<?> spec, String fileName) {
+        if (spec.isEmpty())
+        {
+            // This handles the case where a mod tries to register a config, without any options configured inside it.
+            LOGGER.debug("Attempted to register an empty config for type {} on mod {} using file name {}", type, getActiveContainer().getModId(), fileName);
+            return;
+        }
+
```
Comment (Matyrobbrt) [inline fmlcore/src/main/java/net/minecraftforge/fml/ModLoadingContext.java:71]: These changes *can* and most probably will be considered breaking changes, so including it in an unrelated PR is not a good idea. We should try to avoid cases like #9061.

File: src/main/java/net/minecraftforge/common/ForgeConfig.java [hunk 17]
```diff
@@ -83,28 +83,31 @@ public static class Server {
...
+        @Deprecated(since = "1.19.2", forRemoval = true)
         public final BooleanValue cachePackAccess;
+        @Deprecated(since = "1.19.2", forRemoval = true)
         public final BooleanValue indexVanillaPackCachesOnThread;
+        @Deprecated(since = "1.19.2", forRemoval = true)
         public final BooleanValue indexModPackCachesOnThread;
 
         Common(ForgeConfigSpec.Builder builder) {
-            builder.comment("General configuration settings")
+            builder.comment("[DEPRECATED / NO EFFECT]:General configuration settings")
```
Comment (Matyrobbrt) [inline src/main/java/net/minecraftforge/common/ForgeConfig.java]:
```suggestion
            builder.comment("[DEPRECATED / NO EFFECT]: General configuration settings")
```
Spacing for readability.

File: src/main/java/net/minecraftforge/common/ForgeConfig.java [hunk 18]
```diff
@@ -83,28 +83,31 @@ public static class Server {
...
                     .push("general");
 
             cachePackAccess = builder
-                    .comment("Set this to true to cache resource listings in resource and data packs")
+                    .comment("[DEPRECATED / NO EFFECT] [NOW IN BOOT CONFIG]:Set this to true to cache resource listings in resource and data packs")
```
Comment (Matyrobbrt) [inline src/main/java/net/minecraftforge/common/ForgeConfig.java]:
```suggestion
                    .comment("[DEPRECATED / NO EFFECT] [NOW IN BOOT CONFIG]: Set this to true to cache resource listings in resource and data packs")
```
Spacing for readability.

File: src/main/java/net/minecraftforge/common/ForgeConfig.java [hunk 19]
```diff
@@ -83,28 +83,31 @@ public static class Server {
...
                     .translation("forge.configgui.cachePackAccess")
                     .worldRestart()
                     .define("cachePackAccess", true);
 
             indexVanillaPackCachesOnThread = builder
-                    .comment("Set this to true to index vanilla resource and data packs on thread")
+                    .comment("[DEPRECATED / NO EFFECT] [NOW IN BOOT CONFIG]:Set this to true to index vanilla resource and data packs on thread")
```
Comment (Matyrobbrt) [inline src/main/java/net/minecraftforge/common/ForgeConfig.java]:
```suggestion
                    .comment("[DEPRECATED / NO EFFECT] [NOW IN BOOT CONFIG]: Set this to true to index vanilla resource and data packs on thread")
```
Spacing for readability.

File: src/main/java/net/minecraftforge/resource/ResourceCacheManager.java [hunk 20]
```diff
@@ -51,7 +71,7 @@
     /**
      * Indicates if the indexing of the file-tree should happen off-thread or on-thread and block the process accordingly.
```
Comment (Matyrobbrt) [inline src/main/java/net/minecraftforge/resource/ResourceCacheManager.java]: Javadoc no longer matches field usage.

File: src/main/java/net/minecraftforge/resource/ResourceCacheManager.java [hunk 21]
```diff
@@ -69,35 +89,39 @@
...
+        this.supportsReloading = supportsReloading;
+        this.indexOnThreadConfigurationKey = indexOnThreadConfigurationKey;
+        this.pathBuilder = pathBuilder;
     }
 
+    /**
+     * Indicates if the caching system is enabled or not.
+     *
+     * @return {@code true} if the caching system is enabled, {@code false} otherwise.
+     */
```
Comment (Matyrobbrt) [inline src/main/java/net/minecraftforge/resource/ResourceCacheManager.java:108]:
```suggestion
    /**
     * {@return if the caching system is enabled}
     */
```

File: src/main/java/net/minecraftforge/resource/ResourceCacheManager.java [hunk 22]
```diff
@@ -235,7 +259,7 @@ private record ResourceCacheEntry(PackType packType, String namespace, Path path
         /**
          * Indicates if the indexing should run off-thread.
```
Comment (Matyrobbrt) [inline src/main/java/net/minecraftforge/resource/ResourceCacheManager.java]: Javadoc no longer matches field usage.

File: src/main/java/net/minecraftforge/resource/ResourceCacheManager.java [hunk 23]
```diff
@@ -413,6 +446,178 @@ public boolean cacheLoaded()
...
+                    //Reset the key, and continue.
+                    key.reset();
+                }
+            }
+            catch (IOException | InterruptedException e)
+            {
+                //Some generic failure occurred, that is not good. Let's kill it!
+                throw new RuntimeException("Failed to read boot configuration contents on update.", e);
+            }
+        }
```
Comment (Matyrobbrt) [inline src/main/java/net/minecraftforge/resource/ResourceCacheManager.java]: This can be changed to use the nightconfig-provided `FileWatcher`, reinventing the wheel is not needed.

File: src/main/java/net/minecraftforge/resource/ResourceCacheManager.java [hunk 24]
```diff
@@ -413,6 +446,178 @@ public boolean cacheLoaded()
...
+        private boolean getConfigValue(final String configKey, final boolean defaultValue)
+        {
+            //Get all lines.
+            final List<String> lines = getConfigFileContent();
+
+            for (final String line : lines)
+            {
+                //For each line: Remove all strings, and then check if it is the line with the requested key value.
+                final String trimmedLine = line.trim().replace(" ", "");
+                if (trimmedLine.startsWith("%s=".formatted(configKey))) //We look for key=value combindation in the trimmed
```
Comment (Matyrobbrt) [inline src/main/java/net/minecraftforge/resource/ResourceCacheManager.java]: ~~According to the [TOML Spec](https://toml.io/en/v1.0.0#keyvalue-pair), which as it stands, this bare-bones reader does not follow:
Whitespace is ignored around key names and values.
Additionally, if as you said, the reading of the file happens few times, I do not see a problem with using nightconfig to read it.~~
Disregard, didn't see the `replace` call.

**Review by Matyrobbrt — CHANGES_REQUESTED** [review]

File: fmlcore/src/main/java/net/minecraftforge/fml/ModLoadingContext.java (hunk 16 above)
Comment (KnightMiner) [reply fmlcore/src/main/java/net/minecraftforge/fml/ModLoadingContext.java:71]: what mod is creating an empty config? I cannot see any practical usecase.

Comment (marchermans) [reply fmlcore/src/main/java/net/minecraftforge/fml/ModLoadingContext.java:71]: This was requested by lex.

File: src/main/java/net/minecraftforge/resource/ResourceCacheManager.java (hunk 24 above)
Comment (marchermans) [reply src/main/java/net/minecraftforge/resource/ResourceCacheManager.java]: Misread by @Matyrobbrt Tested the base file in toml lint.
Works.

File: src/main/java/net/minecraftforge/resource/ResourceCacheManager.java [hunk 25]
```diff
@@ -69,35 +89,39 @@
...
+    @Deprecated(since = "1.19.2", forRemoval = true)
     public ResourceCacheManager(final boolean supportsReloading, final ForgeConfigSpec.BooleanValue indexOffThreadConfig, final BiFunction<PackType, String, Path> pathBuilder)
     {
         this.supportsReloading = supportsReloading;
-        this.indexOffThreadConfigOption = indexOffThreadConfig;
+        this.indexOnThreadConfigurationKey = Iterators.getLast(indexOffThreadConfig.getPath().iterator());
         this.pathBuilder = pathBuilder;
     }
 
-    public boolean shouldIndexOffThread()
```
Comment (Matyrobbrt) [inline src/main/java/net/minecraftforge/resource/ResourceCacheManager.java:79]: Removal of this method is a binary breaking change, as previously the class had not been considered internal. It should get re-added, `@Deprecated(forRemoval)` and it would return the inversed value of `shouldIndexOnThread`

Comment (eerussianguy) [reply src/main/java/net/minecraftforge/resource/ResourceCacheManager.java:79]: fwiw this was not considered public api when it was reverted in 1.18. So the core team may be taking the same view here.

Comment (KnightMiner) [reply src/main/java/net/minecraftforge/resource/ResourceCacheManager.java:79]: That whole revert was a breaking change. This PR sounds like its fixing a bug, not making a revert.

File: src/main/java/net/minecraftforge/resource/ResourceCacheManager.java (hunk 21 above)
Comment (marchermans) [reply src/main/java/net/minecraftforge/resource/ResourceCacheManager.java:108]: There is a significant difference between the returns and the method body documentation in that it describes the returned values.

**Review by Matyrobbrt — APPROVED** [review]
