### PR TITLE
Fix up torch placement logic to handle more vanilla special-casing

### LINKED ISSUE #5423: [BUG] Torches on tree leaves
Forge 2800

Torches can be placed on tree leaves, with no other mods installed aside from MCP and the other stuff that comes bundled with forge. Torches should not be able to be placed on tree leaves, same for redstone torches.

### PR DESCRIPTION
**Pull request by bs2609**
Fixes #5423.

Should better match the vanilla logic while still providing a good default for modded blocks. The fallthrough logic is similar to the logic in `BlockButton.canPlaceBlock`, but also accepting fence/wall shapes.

For reference, the vanilla `BlockTorch.canPlaceOn`:
```java
private boolean canPlaceOn(World worldIn, BlockPos pos)
{
    Block block = worldIn.getBlockState(pos).getBlock();
    boolean flag = block == Blocks.END_GATEWAY || block == Blocks.LIT_PUMPKIN;
    if (worldIn.getBlockState(pos).isTopSolid())
    {
        return !flag;
    }
    else
    {
        boolean flag1 = block instanceof BlockFence || block == Blocks.GLASS || block == Blocks.COBBLESTONE_WALL || block == Blocks.STAINED_GLASS;
        return flag1 && !flag;
    }
}
```

The following cases are all consistent with vanilla now:

Currently, a torch can be placed on all the blocks there with Forge.

### CODE REVIEW

File: patches/minecraft/net/minecraft/block/Block.java.patch [hunk 1]
```diff
@@ -837,13 +837,18 @@
 +     */
 +    public boolean canPlaceTorchOnTop(IBlockState state, IBlockAccess world, BlockPos pos)
 +    {
-+        if (state.func_185896_q() || state.func_193401_d(world, pos, EnumFacing.UP) == BlockFaceShape.SOLID)
++        if (this == Blocks.field_185775_db || this == Blocks.field_150428_aP)
 +        {
-+            return this != Blocks.field_185775_db && this != Blocks.field_150428_aP;
++            return false;
```
Comment (mvlabat) [inline patches/minecraft/net/minecraft/block/Block.java.patch]: This line will never be executed

File: patches/minecraft/net/minecraft/block/Block.java.patch [hunk 2]
```diff
@@ -837,13 +837,18 @@
...
++        }
++        else if (state.func_185896_q() || this instanceof BlockFence || this == Blocks.field_150359_w || this == Blocks.field_150463_bK || this == Blocks.field_150399_cn)
++        {
++            return true;
 +        }
 +        else
 +        {
-+            return this instanceof BlockFence || this == Blocks.field_150359_w || this == Blocks.field_150463_bK || this == Blocks.field_150399_cn;
++            BlockFaceShape shape = state.func_193401_d(world, pos, EnumFacing.UP);
++            return (shape == BlockFaceShape.SOLID || shape == BlockFaceShape.CENTER || shape == BlockFaceShape.CENTER_BIG) && !func_193384_b(this);
```
Comment (mvlabat) [inline patches/minecraft/net/minecraft/block/Block.java.patch]: These two lines will never be executed as well

**Comment by liach** [comment]
@mvlabat the patches affect the vanilla blocks directly

**Comment by mvlabat** [comment]
@liach, sorry? Is it addressed to me (regarding my comments)? Not sure how it's related..

File: patches/minecraft/net/minecraft/block/Block.java.patch (hunk 1 above)
Comment (SamboyCoding) [reply patches/minecraft/net/minecraft/block/Block.java.patch]: @mvlabat No, this is removing the `return this...` line and adding `return false` instead.

File: patches/minecraft/net/minecraft/block/Block.java.patch (hunk 2 above)
Comment (SamboyCoding) [reply patches/minecraft/net/minecraft/block/Block.java.patch]: Same here, the `return this instanceof...` is being removed.

File: patches/minecraft/net/minecraft/block/Block.java.patch (hunk 1 above)
Comment (mvlabat) [reply patches/minecraft/net/minecraft/block/Block.java.patch]: Oh, I'm sorry. Is it some kind of github UI update? The line is still highlighted with green, I was totally confused by it

**Comment by Daomephsta** [comment]
@mvlabat Yes, liach was talking to you. You're not reading the patch file diffs correctly. Patch files are formatted a lot like git diffs, so a diff of a patch file can have a removal of a removal, an addition of a removal, a removal of an addition, etc.

**Comment by vladbat00** [comment]
I'm sorry, disregard my last comments, I was just confused with the github UI: misread line removal as line addition.. :) Excuse me for this mess again

**Review by tterrag1098 — APPROVED** [review]

**Comment by ghost** [comment]
In reply to the OP, torches should place on fences and walls, this is vanilla behavior. Please re-check findings against unmodded vanilla 1.12.2!

**Comment by tterrag1098** [comment]
I think you've misunderstood the proposed change, fences and walls are still valid as per the screenshot.

**Comment by ghost** [comment]
That seems to be the case -drinks more coffee-
