### PR TITLE
[1.21.4] Re-introduce IForgeItem.damageItem when an item takes damage

### LINKED ISSUE #10344: [1.20.1] [Regression] Fix for MC-168573 potentially deletes "broken" item stacks which are not empty
**Minecraft Version:** 1.20.1

Patch making the change no longer exists in 1.20.x branch or later

**Forge Version:** 47.3.22

**Description of issue:**

It is often desired for a mod to have an item that instead of disappearing simply enters a broken state. To accomplish this, you usually just need to ensure `ItemStack#getDamageValue` never exceeds `ItemStack#getMaxDamage`. To accomplish this with maximum vanilla compatibility, you often override `IForgeItem#damageItem` to return `0` for its damage value, then handle the damaging yourself including calling the callback passed into the consumer.

In #9344, shields were fixed to call `LivingEntity#stopUsingItem` in `LivingEntity#hurtCurrentlyUsedShield` when the shield breaks via the callback to fix a vanilla bug that causes the wrong item to be used visually and prevents the forge `IForgeItem#stopUsingItem` hook from being fired.

The relevant Forge patch is not present in the 1.20.x branch or later, seems the fix was removed during the 1.20.6 update. I have no confirmed whether that brings back the vanilla issue or the vanilla issue was fixed by other code.

The problem is `LivingEntity#stopUsingItem` causes `LivingEntity#useItem` to be set to `ItemStack#EMPTY`, and directly after the callback vanilla has code to delete the mainhand or offhand item if `LivingEntity#useItem` is empty, which is normally meant to cleanup stack size 0 stack instances that are not `ItemStack#EMPTY` along with a queue to play the breaking sound. In this case, it overwrites a stack that is "broken" but not empty.

**Steps to Reproduce:**
 1. Create a shield which in its `IForgeItem#damageItem` hook calls the consumer without having its damage > max damage. 
 2. Observe that breaking it while blocking will cause the item to be deleted.
 3. Create an item with the same logic in `IForgeItem#damageItem` that is damaged through other means.
 4. Observe that it will play the breaking animation without the stack being lost.

**Proposed Fix:**

Simplest fix is to cache the use item stack before the hurt callback in `LivingEntity#hurtCurrentlyUsedShield` in a local variable, and use that cache for the if statement. This has the sideeffect that the shield sound will not play for items that are broken without being made empty.

Alternatively, you could protecting the `this.setItemSlot` code in `LivingEntity#hurtCurrentlyUsedShield` below the callback to only set the slot if the instance is the same as the original item stack (by shallow comparison).

Another potential fix would be to no-op the entire if statement and move the sound up to the callback, but this has the side-effect of leaving empty instances that are not the same as `ItemStack#EMPTY` in the player hand.

A fourth option would be to backport what is done on 1.20.6 and later (which might simply be removing the fix or might be an alternative solution).

**Alternatives considered:**

I could in my code simply bypass calling the broken callback, but that breaks a lot of other usages of damaging items, and prevents my code from calling the forge event.

I could also reintroduce the vanilla bug on my items by starting to use the item after it stops to prevent the item from being deleted as well, but that leads to undesired behavior when using a shield in the mainhand.

### PR DESCRIPTION
**Pull request by Jonathing**
`IForgeItem.damageItem()` allows the modder to override the amount of damage that would've been dealt to an item when it takes damage. This PR also fixes an issue where the player's `this.useItem` could be pre-emptively set to `ItemStack.EMPTY` and disallow any "broken item" variants.

- Fixes #10344 for 1.21.4

### CODE REVIEW

**Comment by Jonathing** [comment]
Without patches:
Screenshot_20250128_175611

With patches:
Screenshot_20250128_175424

File: src/test/java/net/minecraftforge/debug/gameplay/item/PreventItemDamageTest.java [hunk 1]
```diff
@@ -0,0 +1,79 @@
+package net.minecraftforge.debug.gameplay.item;
+
```
Comment (LexManos) [inline src/test/java/net/minecraftforge/debug/gameplay/item/PreventItemDamageTest.java:7]: License header

File: src/test/java/net/minecraftforge/debug/gameplay/item/PreventItemDamageTest.java [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+        // setup enemy
+        var enemy = helper.spawnWithNoFreeWill(EntityType.HUSK, new BlockPos(2, 0, 2));
+        player.lookAt(EntityAnchorArgument.Anchor.EYES, enemy.position());
+
+        // hit the player
+        player.hurtServer(helper.getLevel(), enemy.damageSources().mobAttack(enemy), 5.0F);
+
+        // shield on cooldown?
+        helper.assertTrue(initialDamage == shield.getDamageValue(), "Fake shield took damage! Expected: " + initialDamage + ", Actual: " + shield.getDamageValue());
+        helper.succeed();
```
Comment (LexManos) [inline src/test/java/net/minecraftforge/debug/gameplay/item/PreventItemDamageTest.java:133]: You need to check that the itemstack in the main hand is still the shield.
Thats the whole 'bug'

Also, probably worth making the damage == 1 and make sure the current == inital -l so we know that the damage hook was called. Or add a Flag and have it flipped in damageItem

**Comment by Jonathing** [comment]
Finally fully finished. Everything's been rebased and squashed into easily digestible commits.

**Comment by LexManos** [comment]
Just a note from our discussions, this is a bad name for this method. It doesn't actually damage the item, that is done by the applyDamage else ware. We'll have to figure out a better name/potential hook for those methods later.
