### PR TITLE
[1.19.x] Homogenize and/or holdersets when serializing to prevent serializing to NBT from crashing

### LINKED ISSUE #9043: `CompositeHolderSet` crashing while serializing to NBT
**Minecraft Version:** 1.19.2
**Forge Version:** 1.19.2-43.1.2

if you try to make for example an `AndHolderSet` that contains a tag and a `NotHolderSet` you'll end up with the following json:
```json
{
    "type": "forge:and",
    "values": [
      "#my_mod:tag1",
      {
        "type": "forge:not",
        "value": "#my_mod:tag2"
      }
    ]
  }
```

If you serialize it to NBT you will get the following `UnsupportedOperationException`: `Trying to add tag of type 10 to list of 8`. This is because the first element that was placed in the `ListTag` is `#my_mod:tag1` so it's a string (NBT type 8) but the second one is a `CompondTag` (NBT type 10).

There is a simple solution to this issue for modders: simply wrap tags in an `OrHolderSet`:
```json
{
    "type": "forge:and",
    "values": [
      {
        "type": "forge:or",
        "values": [
          "my_mod:tag1"
        ]
      },
      {
        "type": "forge:not",
        "value": "#my_mod:tag2"
      }
    ]
  }
```

### PR DESCRIPTION
**Pull request by Commoble**
Fixes #9043 

Serializing and/or holdersets to NBT crashes if the list is non-homogenous, due to list NBT being strongly typed. This can primarily occur when holdersets are declared in custom chunk generators or biome sources, since the server saves these in the level.dat nbt file after loading them from jsons.

To prevent this, this PR converts any vanilla holdersets present in and/or holdersets to single-element or holderset if the and/or's list of sub-holdersets has more than one element. Since or holdersets and all other non-vanilla holdersets serialize as objects (CompoundTag), this will prevent serializing to NBT from crashing.

This only affects serialization and datagen, it does not change deserialization and existing json files with non-homogenous and/or holdersets will still be valid and be parsed in the existing manner.

To reproduce the issue, I temporarily added the following code to ForgeMod#gatherData and ran forge_data:

```java
        HolderSet<Block> blocks = new AndHolderSet<>(List.<HolderSet<Block>>of(
            new HolderSet.Named<Block>(Registry.BLOCK, BlockTags.ACACIA_LOGS),
            new NotHolderSet<Block>(Registry.BLOCK, HolderSet.direct(ForgeRegistries.BLOCKS.getHolder(Blocks.DIRT).get()))));
        
        RegistryAccess registryAccess = RegistryAccess.builtinCopy();
        DynamicOps<JsonElement> jsonOps = RegistryOps.create(JsonOps.INSTANCE, registryAccess);
        DynamicOps<Tag> nbtOps = RegistryOps.create(NbtOps.INSTANCE, registryAccess);
        Codec<HolderSet<Block>> blockHolderSetCodec = HolderSetCodec.create(Registry.BLOCK_REGISTRY, RegistryFileCodec.create(Registry.BLOCK_REGISTRY, Registry.BLOCK.byNameCodec(), false), false);
        
        // simulate serializing to nbt
        blockHolderSetCodec.encodeStart(nbtOps, blocks)
            .resultOrPartial(LOGGER::error)
            .ifPresent(LOGGER::info);
        
        // actually serialize to json so we can see the output format
        DataProvider blockHolderSetProvider = new JsonCodecProvider<HolderSet<Block>>(
            gen,
            existingFileHelper,
            "forge",
            jsonOps,
            PackType.SERVER_DATA,
            "block_holderset_jsons",
            blockHolderSetCodec,
            Map.of(new ResourceLocation("forge", "acacia_logs_and_not_dirt"), blocks));
        gen.addProvider(event.includeServer(), blockHolderSetProvider);
```

The attempt to serialize the nbt crashed as described in the issue.

After applying the changes in this PR, the NBT and JSON both serialize in the sanitized format:

NBT output as logged:
```
{type:"forge:and",values:[{type:"forge:or",values:["#minecraft:acacia_logs"]},{type:"forge:not",value:"minecraft:dirt"}]} 
```

JSON output:
```json
{
  "type": "forge:and",
  "values": [
    {
      "type": "forge:or",
      "values": [
        "#minecraft:acacia_logs"
      ]
    },
    {
      "type": "forge:not",
      "value": "minecraft:dirt"
    }
  ]
}
```

### CODE REVIEW

**Review by marchermans — APPROVED** [review]

File: src/main/java/net/minecraftforge/registries/holdersets/CompositeHolderSet.java [hunk 1]
```diff
@@ -161,4 +162,35 @@ public Iterator<Holder<T>> iterator()
...
+        List<HolderSet<T>> outputs = new ArrayList<>();
+        for (HolderSet<T> holderset : components)
+        {
+            if (holderset instanceof ICustomHolderSet<T>) // serializes to object already
+            {
+                outputs.add(holderset);
+            }
+            else // serializes to string or list
+            {
+                outputs.add(new OrHolderSet<>(List.of(holderset)));
```
Comment (KnightMiner) [inline src/main/java/net/minecraftforge/registries/holdersets/CompositeHolderSet.java:202]: Would it be worth only wrapping it if there is at least one custom holder set? Something like

```json
[ "#some:tag", "#some:othertag" ]
```
is not problematic afterall, its just a list of strings. The problem is strings and compounds together

Comment (Commoble) [reply src/main/java/net/minecraftforge/registries/holdersets/CompositeHolderSet.java:202]: We could but then we'd also have to check if it contains a mix of strings and lists

Direct holderset with one element -> serializes as string
Direct holderset with 0 or 2 or more elements -> serializes as list
Named holderset (tag) -> serializes as string
ICustomHolderset -> serializes as object

or we could just say "don't use list holdersets with tags, just make another tag"

File: src/main/java/net/minecraftforge/registries/holdersets/CompositeHolderSet.java [hunk 2]
```diff
@@ -161,4 +162,35 @@ public Iterator<Holder<T>> iterator()
...
+     * each element of the list will serialize as an object.
+     * Prevents crashes from trying to serialize non-homogenous lists to NBT.
+     * @return List of holdersets with homogenous serialization behavior.
+     * Returns a new List if size > 1, otherwise returns the composite's existing List.
+     */
+    public List<HolderSet<T>> homogenize()
+    {
+        List<HolderSet<T>> components = this.getComponents();
+        
+        if (components.size() <= 1) // avoid infinitely looping on single-element holdersets
```
Comment (sciwhiz12) [inline src/main/java/net/minecraftforge/registries/holdersets/CompositeHolderSet.java]: Could you explain this comment, please?

**Review by sciwhiz12 — COMMENTED** [review]
Testing confirms this works. Just need some clarification on a comment.

File: src/main/java/net/minecraftforge/registries/holdersets/CompositeHolderSet.java (hunk 2 above)
Comment (KnightMiner) [reply src/main/java/net/minecraftforge/registries/holdersets/CompositeHolderSet.java]: Holder sets tags are turned into 1 element holder sets. Which would in turn replace the tag with a 1 element holder set and so on

Comment (sciwhiz12) [reply src/main/java/net/minecraftforge/registries/holdersets/CompositeHolderSet.java]: Okay, after a few minutes of looking at the code, some experimenting, and a bit of help from @SizableShrimp, I finally understand what the comment means. For posterity of self and others:

When serializing, `homogenize` is called on the `CompositeHolderSet` (which may be `AndHolderSet` or `OrHolderSet`), to produce the list of values stored in the `values` key. Without this code, this will wrap a vanilla `HolderSet` (usually representing a tag) with an `OrHolderSet`. 
That new wrapping `OrHolderSet` will then itself be serialized by calling `homogenize` on it (to produce the `values`), which (without this code) would again wrap the vanilla `HolderSet` with an `OrHolderSet` which will be serialized via `homogenize`, and so on and so forth until the stack overflows and the JVM errors out.

Took a bit of rubber-ducking to make it click for me, but now it does. 😄

**Review by sciwhiz12 — APPROVED** [review]

File: src/main/java/net/minecraftforge/registries/holdersets/CompositeHolderSet.java [hunk 3]
```diff
@@ -161,4 +162,35 @@ public Iterator<Holder<T>> iterator()
...
     }
+    
+    /**
+     * Maps the sub-holdersets of this composite such that,if the list contains more than one element,
+     * each element of the list will serialize as an object.
+     * Prevents crashes from trying to serialize non-homogenous lists to NBT.
+     * @return List of holdersets with homogenous serialization behavior.
+     * Returns a new List if size > 1, otherwise returns the composite's existing List.
+     */
+    public List<HolderSet<T>> homogenize()
```
Comment (sciwhiz12) [inline src/main/java/net/minecraftforge/registries/holdersets/CompositeHolderSet.java:184]: The core team requests that this method be changed to avoid the use of the `OrHolderSet`-wrapping strategy when possible, by checking first if the list of components is homogeneous, akin to @KnightMiner's [comment](https://github.com/MinecraftForge/MinecraftForge/pull/9048/files#r973666496).

**Review by sciwhiz12 — CHANGES_REQUESTED** [review]

**Comment by KnightMiner** [comment]
As a thought related to this PR, would it be worth making the decoder for an `OrHolderSet` automatically "unwrap" single element holder sets? That is, if `OrHolderSet` is decoded with a list of size 1, it returns the first element from the list.

File: src/main/java/net/minecraftforge/registries/holdersets/CompositeHolderSet.java [hunk 4]
```diff
@@ -171,17 +169,22 @@ public Iterator<Holder<T>> iterator()
...
      * each element of the list will serialize as an object.
      * Prevents crashes from trying to serialize non-homogenous lists to NBT.
+     * 
+     * Lists are considered non-homogenous if it contains more than one serialization type of holderset.
+     * Holdersets may be serialized as strings, lists, or maps.
      * @return List of holdersets with homogenous serialization behavior.
-     * Returns a new List if size > 1, otherwise returns the composite's existing List.
+     * Returns a new List if size > 1 and serialization would be non-homogenous,
+     * otherwise returns the composite's existing List.
      */
```
Comment (sciwhiz12) [inline src/main/java/net/minecraftforge/registries/holdersets/CompositeHolderSet.java]: This javadoc should have a `@see` tag to `#isHomogenous`.

File: src/main/java/net/minecraftforge/registries/holdersets/CompositeHolderSet.java [hunk 5]
```diff
@@ -200,4 +203,40 @@ public List<HolderSet<T>> homogenize()
...
+        SerializationType firstType = holderSets.get(0).serializationType();
+        
+        // If any holderset has an unknown type, then we cannot assume we are homogenous
+        if (firstType == SerializationType.UNKNOWN)
+        {
+            return false;
+        }
+        
+        final int size = holderSets.size();
+        for (int i=1; i<size; i++)
```
Comment (sciwhiz12) [inline src/main/java/net/minecraftforge/registries/holdersets/CompositeHolderSet.java]: Formatting: spaces between operators.
```suggestion
        for (int i = 1; i < size; i++)
```

**Review by sciwhiz12 — CHANGES_REQUESTED** [review]

**Comment by sciwhiz12** [comment]
Could you please provide an updated version of the test code in the PR description that works in 1.19.3?

**Review by sciwhiz12 — APPROVED** [review]
Tested to work with cobbled together test code based on the author's test code:

**`ForgeMod.gatherData`:**
```java
public void gatherData(GatherDataEvent event)
{
    DataGenerator gen = event.getGenerator();
    PackOutput packOutput = gen.getPackOutput();
    CompletableFuture<HolderLookup.Provider> lookupProvider = event.getLookupProvider();

    ExistingFileHelper existingFileHelper = event.getExistingFileHelper();

    // ...

    final RegistryAccess.Frozen registryAccess = RegistryAccess.fromRegistryOfRegistries(BuiltInRegistries.REGISTRY);
    DynamicOps<JsonElement> jsonOps = RegistryOps.create(JsonOps.INSTANCE, registryAccess);
    DynamicOps<Tag> nbtOps = RegistryOps.create(NbtOps.INSTANCE, registryAccess);
    Codec<HolderSet<Block>> blockHolderSetCodec = HolderSetCodec.create(Registries.BLOCK, RegistryFileCodec.create(Registries.BLOCK, BuiltInRegistries.BLOCK.byNameCodec(), false), false);

    Function<HolderLookup.Provider, HolderSet<Block>> creator = lookup -> {
        final HolderLookup.RegistryLookup<Block> blockLookup = lookup.lookupOrThrow(Registries.BLOCK);

        return new AndHolderSet<>(List.of(
                HolderSet.emptyNamed(blockLookup, BlockTags.ACACIA_LOGS),
                new NotHolderSet<>(blockLookup, HolderSet.direct(ForgeRegistries.BLOCKS.getHolder(Blocks.DIRT).orElseThrow()))
        ));
    };

    lookupProvider.thenAccept(lookup -> {
        final HolderSet<Block> blocks = creator.apply(lookup);

        // simulate serializing to nbt
        blockHolderSetCodec.encodeStart(nbtOps, blocks)
                .resultOrPartial(LOGGER::error)
                .ifPresent(LOGGER::info);
    });

    // actually serialize to json so we can see the output format
    DataProvider jsonProvider = new JsonCodecProvider.NewJsonCodecProvider<HolderSet<Block>>(
            gen.getPackOutput(),
            lookupProvider,
            existingFileHelper,
            "forge",
            jsonOps,
            PackType.SERVER_DATA,
            "block_holderset_jsons",
            blockHolderSetCodec)
    {
        @Override
        protected void gather(HolderLookup.Provider lookup, BiConsumer<ResourceLocation, HolderSet<Block>> consumer)
        {
            consumer.accept(new ResourceLocation("forge", "acacia_logs_and_not_dirt"), creator.apply(lookup));
        }
    };
    gen.addProvider(event.includeServer(), jsonProvider);
}
```

The above snippet uses `JsonCodecProvider.NewJsonCodecProvider`, which is a subclass of `JsonCodecProvider` specially made to use `CompletableFuture<HolderLookup.Provider>` and an abstract method (requiring subclassing, anonymous or otherwise). See the following collapsible for the full subclass code.

<details>
<summary><code>JsonCodecProvider.NewJsonCodecProvider</code></summary>

```java

    public static abstract class NewJsonCodecProvider<T> extends JsonCodecProvider<T>
    {
        private final CompletableFuture<HolderLookup.Provider> lookupProvider;

        public NewJsonCodecProvider(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider,
                                    ExistingFileHelper existingFileHelper, String modid,
                                    DynamicOps<JsonElement> dynamicOps, PackType packType, String directory,
                                    Codec<T> codec)
        {
            super(output, existingFileHelper, modid, dynamicOps, packType, directory, codec, Map.of());
            this.lookupProvider = lookupProvider;
        }


        @Override
        public CompletableFuture<?> run(final CachedOutput cache)
        {
            final Path outputFolder = this.output.getOutputFolder(this.packType == PackType.CLIENT_RESOURCES
                    ? PackOutput.Target.RESOURCE_PACK
                    : PackOutput.Target.DATA_PACK);
            ImmutableList.Builder<CompletableFuture<?>> futuresBuilder = new ImmutableList.Builder<>();

            return this.lookupProvider.thenCompose(lookup -> {
                gather(lookup, LamdbaExceptionUtils.rethrowBiConsumer((id, value) -> {
                    final Path path = outputFolder.resolve(id.getNamespace()).resolve(this.directory).resolve(id.getPath() + ".json");
                    JsonElement encoded = this.codec.encodeStart(this.dynamicOps, value)
                            .getOrThrow(false, msg -> LOGGER.error("Failed to encode {}: {}", path, msg));
                    ICondition[] conditions = this.conditions.get(id);
                    if (conditions != null && conditions.length > 0)
                    {
                        if (encoded instanceof JsonObject obj)
                        {
                            obj.add("forge:conditions", CraftingHelper.serialize(conditions));
                        }
                        else
                        {
                            LOGGER.error("Attempted to apply conditions to a type that is not a JsonObject! - Path: {}", path);
                        }
                    }
                    futuresBuilder.add(DataProvider.saveStable(cache, encoded, path));
                }));

                return CompletableFuture.allOf(futuresBuilder.build().toArray(CompletableFuture[]::new));
            });
        }

        @Deprecated
        @Override
        protected final void gather(BiConsumer<ResourceLocation, T> consumer)
        {
            throw new IllegalCallerException("Do not call this method");
        } // Do not use.

        protected abstract void gather(HolderLookup.Provider lookup, BiConsumer<ResourceLocation, T> consumer);
    }
```

</details>

I may or may not make a follow-up PR which modifies `JsonCodecProvider` to work similarly to the subclass provided above (within the boundaries of binary compatibility).
