### PR TITLE
[1.19.x] Fix mods' worldgen data not being loaded when creating new singleplayer worlds

### LINKED ISSUE #8676: [1.19] Mods' datapack registry (worldgen) jsons are not loaded when creating new singleplayer worlds
**Minecraft Version:** {Minecraft version} 1.19

**Forge Version:** 41.0.1

**Steps to Reproduce:**
 1. Start singleplayer with any mods that add datapack registry jsons (biomes, placedfeatures, etc) via the mod's builtin datapack.
 2. Create a fresh world (not an existing one).
 3. The mod's datapack registry jsons have not been loaded and do not exist on the server.

**Description of issue:**
Mods' datapack registries (worldgen jsons) are not automatically loaded when creating a new singleplayer world. Reordering datapacks via the datapack order screen in the create world menu, spinning up an existing world, and starting a new dedicated server world all cause datapack registries to load correctly.

This seems to arise from the fact that, in vanilla, global/builtin datapacks are not a thing, therefore there is no need to attempt to load datapacks for new singleplayer worlds in vanilla unless the user adds one via the datapack screen (causing datapacks to be (re)loaded and validated). Evidence of this is present in CreateWorldScreen#openFresh (invoked when creating new worlds), which loads builtin registries, but doesn't load datapacks into them.

### PR DESCRIPTION
**Pull request by Commoble**
Fixes #8676.

Vanilla doesn't load datapack registries (worldgen jsons) when creating a new world unless the user adds datapacks via the datapack arrangement menu. This isn't really a vanilla bug because vanilla doesn't have global/builtin datapacks, so there is no need to load datapacks immediately; however, forge mods are effectively global datapacks, so we need to fix this for forge mods.

This fix is implemented by patching CreateWorldScreen such that when the create world screen is opened, we force datapacks to be loaded and validated. We also ensure that the pack selection screen reverts to vanilla pack selection after invalid datapacks are encountered.

### CODE REVIEW

File: patches/minecraft/net/minecraft/client/gui/screens/worldselection/CreateWorldScreen.java.patch [hunk 1]
```diff
@@ -1,5 +1,29 @@
...
+ 
+    public static CreateWorldScreen m_205426_(@Nullable Screen p_205427_, WorldStem p_205428_, @Nullable Path p_205429_) {
+@@ -436,7 +_,10 @@
+          return !list.contains(p_232927_);
+       }).collect(ImmutableList.toImmutableList());
+       DataPackConfig datapackconfig = new DataPackConfig(list, list1);
+-      if (list.equals(this.f_100846_.m_45850_())) {
++      // FORGE: Force load and validate worldgen data when creating new world or rearranging datapacks.
++      // Force load on new world is necessary to ensure mods' worldgen  is loaded.
++      // Force load when leaving datapack rearrange screen is necessary to ensure invalid datapacks from the other force load continue to be recognized as invalid.
```
Comment (SizableShrimp) [inline patches/minecraft/net/minecraft/client/gui/screens/worldselection/CreateWorldScreen.java.patch]: Can you explain a bit more why this force load when leaving the datapack rearrange screen is necessary? Don't really get it.

Comment (GirafiStudios) [reply patches/minecraft/net/minecraft/client/gui/screens/worldselection/CreateWorldScreen.java.patch]: So currently (without this fix), anything that any mod adds in data/worldgen is simply not loaded at all. This also includes the new BiomeModifiers. So mob spawns and similar does not work either in Forge currently. 
You can force it to load by re-arranging the datapacks in the datpack menu, when creating a new world.
Hope that simplifies it a bit :)

Comment (SizableShrimp) [reply patches/minecraft/net/minecraft/client/gui/screens/worldselection/CreateWorldScreen.java.patch]: I understand the issue and that this fixes it. I do not understand the comment in this patch.

Comment (LexManos) [reply patches/minecraft/net/minecraft/client/gui/screens/worldselection/CreateWorldScreen.java.patch]: Better fix here would be to change the `DataPackConfig.DEFAULT` in `openFresh` to be `new DataPackConfig(ImmutableList.of("vanilla"), ImmutableList.of())`  which is what the completable future atually does.
The reason you have to noop this if is because DEFAULT has our mods in it. 
IF it is possible, killing the entire completable future thing in openFresh would be the best option as it's just a waste of time.

Comment (Commoble) [reply patches/minecraft/net/minecraft/client/gui/screens/worldselection/CreateWorldScreen.java.patch]: Attempted lex's solution re: DataPackConfig and it does indeed work better than what I previously had.

Wasn't able to find way to kill the completable future thing in openFresh; if reloadable data isn't loaded (which the completable future seems to do), then if the user has invalid datapacks and reverts to vanilla, then the game crashes when they conclude the create world screen because reloadable data wasn't loaded.

Comment (LexManos) [reply patches/minecraft/net/minecraft/client/gui/screens/worldselection/CreateWorldScreen.java.patch]: Alright, wasn't sure if it would be a pain to do but it would be better.

**Comment by GirafiStudios** [comment]
Shouldn't this be good to go now? As the requested changes have been made (At least the main one)

**Comment by SizableShrimp** [comment]
Needs testing by a team member but yeah.

**Comment by gohkenytp** [comment]
Is is fixed? I guess that we waited for 5 days or so.

**Comment by TheCurle** [comment]
This hasn't yet been independently tested by someone that isn't the PR author.

If it has, they haven't got in touch with us yet.

We don't yet know if this fix actually works, once we do it'll be merged.

We won't rush that.

**Comment by SizableShrimp** [comment]
Tested and confirmed working with my own simple test mod here (zip of src/main based off MDK): [main.zip](https://github.com/MinecraftForge/MinecraftForge/files/8889254/main.zip).

Seed: 7728047913115364842
Location: Right around 0, 0
Before the fix, creating the world for the first time: 
After the fix, creating the world again with the same seed:

**Review by sciwhiz12 — APPROVED** [review]

**Comment by moninformateur** [comment]
Is there any reason this isn't backported to 1.18?

**Comment by sciwhiz12** [comment]
We have no knowledge of the bug addressed by this PR being present on the latest versions of Forge 1.18.2.

If you have a confirmed minimal and reproducible report that this issue is present on 1.18.2, please make your own issue and leave a comment on the linked issue. Otherwise, you may seek support for your issue at the [Forge Support Forums](https://forums.minecraftforge.net/) or [Forge Discord](https://discord.gg/forge).
