### PR TITLE
Fix launch handler minecraft classpath locator

### LINKED ISSUE #9098: Forge launch handler incorrectly identifies the minecraft jar
**Minecraft Version:** 1.19.2
**Forge Version:** 43.1.43

## The issue

This issue occurs when `CommonUserdevLaunchHandler` searches the classpath, looking for a jar containing minecraft classes. The matcher method, [`CommonUserdevLaunchHandler#findJarOnClasspath`](https://github.com/MinecraftForge/MinecraftForge/blob/0e66b7b21757e510aef706ca320881b9eb268822/fmlloader/src/main/java/net/minecraftforge/fml/loading/targets/CommonUserdevLaunchHandler.java#L45), returns the first element on the classpath (`String[]`) that contains the desired file name (`String`).

https://github.com/MinecraftForge/MinecraftForge/blob/0e66b7b21757e510aef706ca320881b9eb268822/fmlloader/src/main/java/net/minecraftforge/fml/loading/targets/CommonUserdevLaunchHandler.java#L45-L47

In userdev, this is the forge jar that is located by `ForgeUserdevLaunchHandler` using a `forge-<version>` string pattern. In our case, this string equals `forge-1.19.2-43.1.43`. I'll refer to it as the "forge pattern".

https://github.com/MinecraftForge/MinecraftForge/blob/0e66b7b21757e510aef706ca320881b9eb268822/fmlloader/src/main/java/net/minecraftforge/fml/loading/targets/ForgeUserdevLaunchHandler.java#L17

However, `findJarOnClasspath` has a flaw - it tests the entire path string for the desired name, rather than just the file name part. So if the classpath contains a path that has the forge pattern in it and comes before the actual forge jar, that path will be wrongly selected as the minecraft jar.

To trigger this bug, 2 conditions must be met:

#### 1. The MDK path must contain the forge pattern string

The forge pattern is commonly found in MDK instances. A freshly extracted MDK folder will usually follow the pattern of `forge-<version>-mdk` (in our case `forge-1.19.2-43.1.43-mdk`), which contains the exact pattern forge is looking for when locating minecraft.

#### 2. A subpath of the MDK must be present on the `minecraft_classpath`

There are multiple reasons why a path in our own MDK might end up on the boot classpath, for example:
1. Using a local `minecraftLibrary` dependency
2. Adding the project's output to the `minecraft_classpath` for in-dev testing of `SERVICE` layer libraries, namely `IModLocator`s, `IDependencyLocator`s and `ITransformationService`s

Paths added to the `minecraft_classpath` via `lazyToken` are **always prepended** to the classpath list. That meets our other condition - our jar's path must come before the forge jar's path.  
This bug affects fmlonly and client-extra lookups as well. 

### Consequences

All usages of the minecraft jar path are prone to this bug, which will ultimately lead to a crash as the game cannot load minecraft classes. In this case, I get a crash from SecureJarHandler:

Later in the launch process, FML will attempt to create `JarMetadata` for what it believes to be the minecraft jar. Because the jar's path doesn't follow a maven layout, SJH will use fallback parsing. `JarMetadata` will attempt to get the jar's file name using `path.getFileName().toString()`, where a `UnionPath` instance returns an empty string, which leads to a crash on the following [substring](https://github.com/McModLauncher/securejarhandler/blob/ee35db45b3da48a7ff1b844313167d0a8e5019b0/src/main/java/cpw/mods/jarhandling/JarMetadata.java#L79) call.

Crash log: https://pastebin.com/S7XsttXM

### Steps to reproduce

1. Download and extract the MDK to a new folder. Make sure to keep the default name (`forge-1.19.2-43.1.43-mdk`).
2. Remove the example mod, specifically the `mods.toml` file from the MDK. Suppose we are targeting the `SERVICE` layer with one of the mentioned service types.
4. According to one of the above examples, add a path in your MDK folder to the `minecraft_classpath` (local dependency or project output jar). 
   If you're using the latter, make sure the jar is built before the game runs by adding the following code to your buildscript:
```groovy
tasks.whenTaskAdded {  
    if (name == 'prepareRuns') {  
        dependsOn(jar)  
    }
}
```
3. Launching the game results in a crash

## Proposed solution

In `CommonUserdevLaunchHandler#findJarOnClasspath`, we should extract the file name from the tested path using `path.substring(path.lastIndexOf(File.separatorChar) + 1)` before testing it.

### PR DESCRIPTION
**Pull request by Su5eD**
### The issue

All details and reproductions steps are outlined in issue #9098.

### The proposal

- Move `findJarOnClasspath` to `CommonDevLaunchHandler` to avoid using duplicate code to locate `client-extra`
- Add an additional step to `findJarOnClasspath` and `getFmlStuff` that extracts the file name from the path before matching. This prevents the accidental selection of paths that contain the desired string in one of their parent folder names.

Closes #9098

### CODE REVIEW

File: fmlloader/src/main/java/net/minecraftforge/fml/loading/targets/CommonDevLaunchHandler.java [hunk 1]
```diff
@@ -77,11 +77,26 @@ protected String[] preLaunch(String[] arguments, ModuleLayer layer) {
     protected List<Path> getFmlStuff(String[] classpath) {
         // We also want the FML things, fmlcore, javafmllanguage, mclanguage, I don't like hard coding these, but hey whatever works for now.
         return Arrays.stream(classpath)
-            .filter(e -> e.contains("fmlcore") || e.contains("javafmllanguage") || e.contains("lowcodelanguage") || e.contains("mclanguage"))
+            .filter(e -> {
+                // Extract file name from path
+                String name = e.substring(e.lastIndexOf(File.separatorChar) + 1);
```
Comment (Matyrobbrt) [inline fmlloader/src/main/java/net/minecraftforge/fml/loading/targets/CommonDevLaunchHandler.java]: This file name extraction code could be moved in an utility method in `FileUtils`

**Review by Matyrobbrt — APPROVED** [review]

File: fmlloader/src/main/java/net/minecraftforge/fml/loading/targets/CommonDevLaunchHandler.java (hunk 1 above)
Comment (Su5eD) [reply fmlloader/src/main/java/net/minecraftforge/fml/loading/targets/CommonDevLaunchHandler.java]: done

File: fmlloader/src/main/java/net/minecraftforge/fml/loading/FileUtils.java [hunk 2]
```diff
@@ -8,10 +8,12 @@
 import com.mojang.logging.LogUtils;
 import org.slf4j.Logger;
 
+import java.io.File;
 import java.io.IOException;
 import java.nio.file.FileAlreadyExistsException;
 import java.nio.file.Files;
 import java.nio.file.Path;
+import java.util.regex.Pattern;
```
Comment (Matyrobbrt) [inline fmlloader/src/main/java/net/minecraftforge/fml/loading/FileUtils.java]: Why was this import added?

**Review by Matyrobbrt — CHANGES_REQUESTED** [review]

File: fmlloader/src/main/java/net/minecraftforge/fml/loading/FileUtils.java (hunk 2 above)
Comment (Su5eD) [reply fmlloader/src/main/java/net/minecraftforge/fml/loading/FileUtils.java]: oopsie, forgot to remove that

**Review by Matyrobbrt — APPROVED** [review]
