### PR TITLE
Throw when a mod returns null from a capability provider

### LINKED ISSUE #5645: [1.13] Add null check in CapabilityDispatcher so bug reports go to the right mod
In MC 1.12, returning `null` in getCapability was valid. In MC 1.13 it's not; the empty value is `LazyOptional.empty()` instead. However, there's nothing stopping modders from returning `null` anyway, and when the game crashes the stack trace shows the methods *checking* for capabilities, not the one that's actually broken. This can lead users to report crashes to the wrong mod dev, wasting people's time (see https://github.com/sargunv/level-up-hp/issues/8).

I think Forge should add a null check on `ret` in the below method, to throw an exception that reports the `ICapabilityProvider` that returned the invalid `null`.

```java
    // from net.minecraftforge.common.capabilities.CapabilityDispatcher
    @Override
    public <T> LazyOptional<T> getCapability(Capability<T> cap, @Nullable EnumFacing side)
    {
        for (ICapabilityProvider c : caps)
        {
            LazyOptional<T> ret = c.getCapability(cap, side);

            // insert null check here and throw exception to report the bad provider

            if (ret.isPresent()) {
                return ret;
            }
        }
        return LazyOptional.empty();
    }
```

I'd be happy to make the PR myself if this is something that would be accepted.

### PR DESCRIPTION
**Pull request by sargunv**
Currently, if MC1.13 mods return null in `getProvider` like they used to in MC1.12, the stack trace of the NPE leads users to report the bug to the mod checking for capabilities, not the mod that erroneously returned null. This `throw` will report the offending mod's provider, making it clear(er) which mod actually contains the bug.

This fixes #5645 (see that issue for context)

### CODE REVIEW

**Review by Gamebuster19901 — CHANGES_REQUESTED** [review]
MinecraftForge requires braces to begin on new lines.

https://github.com/sargunv/MinecraftForge/blob/c29fe380b0ee74b957ac2df5458973fff55fc938/src/main/java/net/minecraftforge/common/capabilities/CapabilityDispatcher.java#L104-L106

and 

https://github.com/sargunv/MinecraftForge/blob/c29fe380b0ee74b957ac2df5458973fff55fc938/src/main/java/net/minecraftforge/common/capabilities/CapabilityDispatcher.java#L112

**Comment by sargunv** [comment]
Sure, fixed.

**Comment by liach** [comment]
> 
> 
> MinecraftForge requires braces to begin on new lines.
> 
> https://github.com/sargunv/MinecraftForge/blob/c29fe380b0ee74b957ac2df5458973fff55fc938/src/main/java/net/minecraftforge/common/capabilities/CapabilityDispatcher.java#L104-L106
> 
> and
> 
> https://github.com/sargunv/MinecraftForge/blob/c29fe380b0ee74b957ac2df5458973fff55fc938/src/main/java/net/minecraftforge/common/capabilities/CapabilityDispatcher.java#L112

This is actually no longer the case beginning in the 1.13 port.

**Comment by LexManos** [comment]
I still prefer them on their own lines if the contained block is more then one line long.

File: src/main/java/net/minecraftforge/common/capabilities/CapabilityDispatcher.java [hunk 1]
```diff
@@ -101,15 +101,17 @@ public CapabilityDispatcher(Map<ResourceLocation, ICapabilityProvider> list, Lis
         {
             LazyOptional<T> ret = c.getCapability(cap, side);
             //noinspection ConstantConditions
-            if (ret == null) {
+            if (ret == null)
+            {
                 throw new RuntimeException(
                         String.format(
                                 "Provider %s.getCapability() returned null; this is not allowed!",
```
Comment (Gamebuster19901) [inline src/main/java/net/minecraftforge/common/capabilities/CapabilityDispatcher.java]: I'd also recommend adding something like "return LazyOptional.empty() instead" to the existing error message.

**Review by Gamebuster19901 — CHANGES_REQUESTED** [review]

File: src/main/java/net/minecraftforge/common/capabilities/CapabilityDispatcher.java (hunk 1 above)
Comment (Gamebuster19901) [reply src/main/java/net/minecraftforge/common/capabilities/CapabilityDispatcher.java]: Other than that, looks good to me.

Comment (liach) [reply src/main/java/net/minecraftforge/common/capabilities/CapabilityDispatcher.java]: Just crashing is fine. We need to stop bad mods as soon as possible.

Comment (Gamebuster19901) [reply src/main/java/net/minecraftforge/common/capabilities/CapabilityDispatcher.java]: Erm, I don't understand.

It already 'just crashes'.

Crashing with a better error message was pretty much the entire point of this PR. I suggested adding more clarification to the error message....

Furthermore, it used to be convention to return null. Documenting the fact that LazyOptional.empty() should now be returned instead will likely stop at least some unnecessary questions.

Comment (sargunv) [reply src/main/java/net/minecraftforge/common/capabilities/CapabilityDispatcher.java]: Updated the message.

**Review by Gamebuster19901 — APPROVED** [review]

**Review by mezz — APPROVED** [review]
