### PR TITLE
[1.19.x] Fix `ForgeSlider` not respecting custom height

### LINKED ISSUE #9094: ForgeSlider handle height does not respect the height of the widget
**Minecraft Version:** 1.19.2

**Forge Version:** 1.19.2-43.1.43

**Logs:** N/A

**Screenshot:**
image

**Steps to Reproduce:**
1. Create a screen.
2. Add a ForgeSlider component to the renderable widgets.
3. Input the height of the widget as anything other than `20`.

**Description of issue:**
When creating a `ForgeSlider` with any height other than `20`, the height of the slider handle does not change as it is hardcoded to `20`. This makes the `height` parameter *effectively*(imo) useless. As it doesn't make sense to want to have the height of the background area be a different height to the slider.

I can think of 3 solutions to this problem (all of which will provide a different result and I'm not sure which is generally preferred):
1. Override the `renderBg` method in `AbstractSliderButton`, replacing `20` with `this.height` - This will make the height of the handle respect the height of the widget.
2. (Probably not ideal) Remove the `height` parameter in the `ForgeSlider` constructor(s), passing `20` directly into the `super` - This means the height of the slider is hardcoded to `20`.
3. (Probably not ideal) Make it so that the slider background centres on the Y position of the slider handle (however, this would be much harder to achieve) - This means that the slider handle height will still not change however it would at least look a little better.

### PR DESCRIPTION
**Pull request by Matyrobbrt**
This PR fixes `ForgeSlider` not respecting the custom height by making it use `ScreenUtils#blitWithBorder`, akin to `ExtendedButton`. This PR also makes `ExtendedButton` do less hacky component substringing for ellipsis.

## Before
image

## After
image

Closes #9094.

### CODE REVIEW

File: src/main/java/net/minecraftforge/client/gui/widget/ExtendedButton.java [hunk 1]
```diff
@@ -44,14 +46,7 @@ public void renderButton(PoseStack poseStack, int mouseX, int mouseY, float part
...
-        Component buttonText = this.getMessage();
-        int strWidth = mc.font.width(buttonText);
-        int ellipsisWidth = mc.font.width("...");
-
-        if (strWidth > width - 6 && strWidth > ellipsisWidth)
-            //TODO, srg names make it hard to figure out how to append to an ITextProperties from this trim operation, wraping this in StringTextComponent is kinda dirty.
-            buttonText = Component.literal(mc.font.substrByWidth(buttonText, width - 6 - ellipsisWidth).getString() + "...");
-
-        drawCenteredString(poseStack, mc.font, buttonText, this.getX() + this.width / 2, this.getY() + (this.height - 8) / 2, getFGColor());
+        final FormattedText buttonText = mc.font.ellipsize(this.getMessage(), this.width - 6);
```
Comment (sciwhiz12) [inline src/main/java/net/minecraftforge/client/gui/widget/ExtendedButton.java]: There should be a comment here explaining that the `- 6` is so the text is always contained within the button, rather than possibly overlapping with the edges.

**Review by sciwhiz12 — CHANGES_REQUESTED** [review]
The fix for the slider height seems to work, but the ellipsizing of the text doesn't. It cuts off the text to fit within the slider's area, but I see no ellipsis for it. Please retest that functionality.

File: src/main/java/net/minecraftforge/client/extensions/IForgeFont.java [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+import net.minecraft.network.chat.FormattedText;
+
+/**
+ * Extension interface for {@link Font}.
+ */
+public interface IForgeFont
+{
+    FormattedText ELLIPSIS = FormattedText.of("...");
+
+    private Font self()
```
Comment (marchermans) [inline src/main/java/net/minecraftforge/client/extensions/IForgeFont.java]: On rendering Renate objects this method needs to be patched into the target instead of in gehe extension interface.

At the moment the jvm will generate bytecode which forces the runtime to check if IForgeFont's this instance is actually an instance of Font before doing the cast, which is really expensive compared to just the cast (several orders of magnitude difference).

**Review by marchermans — CHANGES_REQUESTED** [review]

File: src/test/java/net/minecraftforge/debug/client/GuiLayeringTest.java [hunk 3]
```diff
@@ -79,6 +80,8 @@ protected void init()
                 this.addRenderableWidget(Button.builder(Component.literal("Push New Layer"), this::pushLayerButton).pos(xoff, yoff + buttonSpacing * (cnt++)).size(buttonWidth, buttonHeight).build(ExtendedButton::new));
                 this.addRenderableWidget(Button.builder(Component.literal("Pop Current Layer"), this::popLayerButton).pos(xoff, yoff + buttonSpacing * (cnt++)).size(buttonWidth, buttonHeight).build(ExtendedButton::new));
                 this.addRenderableWidget(Button.builder(Component.literal("Close entire stack"), this::closeStack).pos(xoff, yoff + buttonSpacing * (cnt++)).size(buttonWidth, buttonHeight).build(ExtendedButton::new));
+
+                this.addRenderableWidget(new ForgeSlider(xoff, yoff + buttonSpacing * cnt, 50, 25, Component.literal("Val: ").withStyle(ChatFormatting.GOLD), Component.literal("some text which will be cut off"), 5, 55, 6, true));
```
Comment (sciwhiz12) [inline src/test/java/net/minecraftforge/debug/client/GuiLayeringTest.java:85]: The `ForgeSlider` class is not imported. _We really need to add compilation of the test source set to the CI build._

**Review by sciwhiz12 — CHANGES_REQUESTED** [review]

File: src/test/java/net/minecraftforge/debug/client/GuiLayeringTest.java (hunk 3 above)
Comment (Matyrobbrt) [reply src/test/java/net/minecraftforge/debug/client/GuiLayeringTest.java:85]: I really hate rebasing with conflicts...

**Review by sciwhiz12 — APPROVED** [review]
