### PR TITLE
[1.21.10] Fix `BusGroup.DEFAULT` not being trimmed after mod loading completes, also trim mod BusGroups now too

### LINKED ISSUE #10720: BusGroup#trim not called by FML after mod loading completes
**Minecraft Version:** 1.21.10, 1.21.8

**Forge Version:** 60.1.0, 58.1.9

**Logs:** N/A

**Steps to Reproduce:**
 1. Clone and setup forgedev
 2. Add a breakpoint to BusGroup#trim
 3. Run the client run config in debug mode
 4. Observe that the breakpoint is never triggered

**Description of issue:**
Despite FML having a withInline() setup on the `DONE` ModLoadingState, the inline Consumer is never called.
https://github.com/MinecraftForge/MinecraftForge/blob/5e8942e0a71b6e54d2e10f5c03bdd22e434b3ab8/src/main/java/net/minecraftforge/fml/core/ModStateProvider.java#L139-L140

Additionally, this would only trim the default BusGroup if it worked - mod bus groups aren't trimmed.

### PR DESCRIPTION
**Pull request by PaintNinja**
Fixes #10720

### CODE REVIEW

File: javafmllanguage/src/main/java/net/minecraftforge/fml/javafmlmod/FMLModContainer.java [hunk 1]
```diff
@@ -166,7 +168,8 @@ public Object getMod() {
         return modInstance;
     }
 
-    public BusGroup getModBusGroup() {
+    @Override
+    public @NonNull BusGroup getModBusGroup() {
```
Comment (Jonathing) [inline javafmllanguage/src/main/java/net/minecraftforge/fml/javafmlmod/FMLModContainer.java]: I am not a fan of non-null annotations. But more than that, Forge and FML need to be consistent with how these annotations are used. So, probably cleanup for later. My personal preference is to infer everything as not null by default.

Comment (PaintNinja) [reply javafmllanguage/src/main/java/net/minecraftforge/fml/javafmlmod/FMLModContainer.java]: For the trimming to work from FMLCore, I need a `getModBusGroup()` method so added one to `ModContainer` and defaulted it to null because not all containers have or need a mod bus group. I marked that method as nullable because it can return null depending on the subtype. To avoid a breaking change for `FMLModContainer`, I then annotate that override as non-null as it's guaranteed to never return null for that subtype.

FML's internals are absolute hell with a mix of intentionally null and accidentally null throughout the codebase with no consistent annotations at all. Good luck figuring out which and annotating the whole thing correctly. If you prefer, I can remove the nullable annotation on the parent method and remove the nonnull annotation on this method so that it's unknown nullability like most of FML's codebase?

Comment (Jonathing) [reply javafmllanguage/src/main/java/net/minecraftforge/fml/javafmlmod/FMLModContainer.java]: I'm not going to enforce anything with the annotations. It was more-so a declaration of how I'd like to approach them once we get started with the rewrite/cleanup.

Comment (Jonathing) [reply javafmllanguage/src/main/java/net/minecraftforge/fml/javafmlmod/FMLModContainer.java]: I'm not going to enforce anything with the annotations. It was more-so a declaration of how I'd like to approach them once we get started with the rewrite/cleanup.

Comment (Jonathing) [reply javafmllanguage/src/main/java/net/minecraftforge/fml/javafmlmod/FMLModContainer.java]: I'm not going to enforce anything with the annotations. It was more-so a declaration of how I'd like to approach them once we get started with the rewrite/cleanup.

File: fmlcore/src/main/java/net/minecraftforge/fml/ModLoader.java [hunk 2]
```diff
@@ -232,7 +233,19 @@ public void finishMods(final ModWorkManager.DrivenExecutor syncExecutor, final E
...
             dispatchAndHandleError(mls, syncExecutor, parallelExecutor, periodicTask, progress);
         }
-        statusConsumer.accept(String.format("Mod loading complete - %d mods loaded", this.modList.size()));
+
+        var modBusGroups = Set.of(
+                modList.getLoadedMods().stream()
+                        .map(ModContainer::getModBusGroup)
+                        .filter(Objects::nonNull)
+                        .toArray(BusGroup[]::new)
+        );
```
Comment (LexManos) [inline fmlcore/src/main/java/net/minecraftforge/fml/ModLoader.java:242]: For future references, its preferred to not use streams, and intermediate collections. This way you dont need to iterate over the collection twice.
