### PR TITLE
[1.21.1] Add optional fix of use item duration, disabled by default

### LINKED ISSUE #10150: Forge is different from the original Eye of Ender detection, is there any way to change it back
**Minecraft Version:** 1.20.1

**Forge Version:** 47.3.11

**Logs:** not have

**Steps to Reproduce:**
Open an forge and use the Eye of the Ender

**Description of issue:**
In the vanilla, only one eye of Ender will be used when the right button is held down, and the movement speed will be very slow
But in forge, however, holding down the right button will continuously use the Eye of Ender, and speed will not be affected
 I was wondering if there was any way to change this mechanism back, I didn't see any files about the Eye of Ender in forge's change docs
The first video below is the original and the second one is forge

https://github.com/user-attachments/assets/ea19e82d-0728-4cc2-b1ad-3cfaca1ef3b7

https://github.com/user-attachments/assets/fd772717-b666-46c9-bf82-1b38a64f8b46

### PR DESCRIPTION
**Pull request by Jonathing**
Fixes #10150 for 1.21.1. This fix is disabled by default and can only be enabled through the server config.

### CODE REVIEW

**Comment by Jonathing** [comment]
Once this PR is approved, I will create additional backport PRs for affected versions.

**Review by LexManos — APPROVED** [review]

File: src/main/java/net/minecraftforge/common/ForgeConfig.java [hunk 1]
```diff
@@ -61,8 +63,17 @@ public static class Server {
                     .translation("forge.configgui.advertiseDedicatedServerToLan")
                     .define("advertiseDedicatedServerToLan", true);
 
+            useItemWithDurationZero = builder
+                    .comment("Set this to true to enable living entities to use items with durations of 0. Fixes being able to use Eyes of Ender repeatedly by holding down the use button. Disabled by default as it could change interactions with items of existing mods.")
```
Comment (PaintNinja) [inline src/main/java/net/minecraftforge/common/ForgeConfig.java:67]: Would be good to mention if this should be set to true or false if players want to align with Vanilla behaviour. Also to mention that Vanilla behaviour is the default in 1.21.3+
