### PR TITLE
Fix #3682 getShareTag replacing data on the server

### LINKED ISSUE #3682: getShareTag is sometimes called serverside and replaces itemstacks on the server with the share tag
Note: I don't know how to reproduce this consistently or what causes this. This issue is merely for documenting this bug as it's quite a severe one. I'm hoping some other people can chip in as well who know more about this.

Debugging with @McJty:

```
<McJty> getNBTShareTag is a bit more dangerous then I expected. It does clear the storage server side somehow
<McJty> I have to check what's wrong
<McJty> raoulvdberge: if I put my tablet (containing items) in a chest and retrieved it again all items were gone
<McJty> So it seems somehow server side the share tag is being used instead of the normal one
<raoulvdberge> AHA!
<raoulvdberge> Great to hear
<raoulvdberge> That clarifies the whole "i lost all my items on RS disks" issue
<raoulvdberge> you have any other mods in there?
<McJty> Nope, it is in my rftools dev env
<McJty> So just a bunch of mine (top, interaction wheel, mcjtylib, ...)
<McJty> Ok, in any case. For now I think I will not use getNBTShareTag() until this is clarified :-)
<McJty> Pretty dangerous IMHO
<raoulvdberge> McJty:  I'd really appreciate it if you found out why it uses the share tag on the server
<McJty> ok, I can do that
<McJty> But not very familiar with those internals. Where can I look?
<McJty> Or how can I find needed info for you?
<raoulvdberge> well
<raoulvdberge> one thing you can do is
<raoulvdberge> open a server, try put the storage tablet in, put a breakpoint on the getNBTShareTag, and look at the trace
<McJty> ok
<McJty> hold on
<McJty> On server side I suppose? Or should I also check client side of this?
<raoulvdberge> just server i guess
<McJty> Hmm hard to do
<McJty> Client times out while server is in breakpoint
<McJty> And it breaks too often
<McJty> I cannot get the item in the chest :-)
<raoulvdberge> rip
<McJty> BTW, how can I make sure my client connects with same nick every time?
<McJty> Otherwise my tablet is gone every time I start a new client
<raoulvdberge> No idea
<raoulvdberge> I guess that is an FML arg or something
<McJty> um, now I cannot even reproduce it anymore...
<McJty> ah
<McJty> Raoul, I could apparently reproduce it again by inserting the tablet in an item frame
<McJty> um
<McJty> Actuall
<McJty> Actually
<McJty> It seems to happen when the server saves
<McJty> As I just went to the server and switched my player to survival and the tablet items were gone
<McJty> Sorry but this is not consistent
<McJty> I had it four times now that the items were lost
<McJty> But always at a different moment
<McJty> I cannot get it to reproduce consistently
<McJty> Actually
<raoulvdberge> o.o
<McJty> I know a way that I can perhaps debug this
<McJty> I can (in getNBTShareTag) insert a dummy tag that doesn't exist on the server side normally
<raoulvdberge> hmm
<McJty> And when I get that tag server side in my item I can detect that and break at that point
<McJty> raoulvdberge: yes I can confirm but I cannot find when/how or reproduce it
<McJty> But *sometimes* the share tag replaces the server side NBT tag
<McJty> If you have any ideas on what I can do for you to help?
<McJty> This time it happened just while the tablet was in my hotbar and I was doing other things
<McJty> i.e. putting other blocks in the world
<McJty> raoulvdberge: for now I'm giving up trying to debug it. I can reproduce this VERY difficultly
<McJty> It just seems to happen randomly
<raoulvdberge> hm i see
<McJty> Sometimes very fast. Sometimes it takes very long
<McJty> I printed a stacktrace everytime it happens
<McJty> So it will have happened in one of:
<McJty> Oh, I accidently closed it
<McJty> hmm hold on
<McJty> https://bpaste.net/show/5ac3a92310e3
<McJty> It is as if the packet that is created sometimes gets received on the server instead of the client
<McJty> But I don't understand how that can happen
<McJty> BTW, that's not a real crash
<McJty> Just me dumping the stacktrace
<McJty> But I have to go
```

Affected:

https://github.com/raoulvdberge/refinedstorage/issues/821

### PR DESCRIPTION
**Pull request by mezz**
See issue #3682.

There are three bugs addressed here:

1. Creative items will have `getShareTag` applied as they are sent to the server, making the ItemStack invalid on the server. The fix is to send the full NBT instead.
2. When clicking an item, it is sent from client to server to check that everything matches. This puts it though `getShareTag` a second time, which mods probably do not handle correctly (the client item does not have data necessary to create the share tag again unless it is checking that its NBT is already a share tag). The fix is the same as Issue 1: send the full NBT to the server instead.
3. When the server receives the clicked item, it does a comparison where it sees if an item clicked by a player matches the one on the server. Since the client ItemStack most likely came from the server in the first place, it has had `getShareTag` applied once before. The comparison is fixed by using `getShareTag` on both ItemStacks for comparison instead of comparing NBT directly.   
**EDIT:** there's a bug here, the item from the client has `getShareTag` applied twice for this comparison. Not sure what to do about it.
**EDIT2:** added a javadoc note about implementing `getShareTag` properly to avoid this issue.

@raoulvdberge, @McJty, please check that this fixes the issues you were seeing.
I tested RefinedStorage but the bug (https://github.com/raoulvdberge/refinedstorage/issues/821) was not 100% reproducible before this fix. I tried several times and wasn't able to reproduce it with this fix applied though.

### CODE REVIEW

**Comment by raoulvdberge** [comment]
Thanks for doing this @mezz, I couldn't figure it out.

File: patches/minecraft/net/minecraft/item/ItemStack.java.patch [hunk 1]
```diff
@@ -309,4 +309,42 @@
...
++        else
++            return !stackB.func_190926_b() && stackA.isItemStackEqualUsingNBTShareTag(stackB);
++    }
++
++    /**
++     * Modeled after ItemStack.isItemStackEqual
++     * Uses Item.getNBTShareTag for comparison instead of NBT and capabilities.
++     * Only used for comparing itemStacks that were transferred from server to client using Item.getNBTShareTag.
++     */
++    private boolean isItemStackEqualUsingNBTShareTag(ItemStack other)
```
Comment (liach) [inline patches/minecraft/net/minecraft/item/ItemStack.java.patch:333]: Why put this in a separate method?

Comment (mezz) [reply patches/minecraft/net/minecraft/item/ItemStack.java.patch:333]: I broke up the methods similar to the way vanilla does so that the logic is easier to verify.

**Comment by liach** [comment]
:heart:
