### PR TITLE
[1.19.4] Fix infinite BE render bounds failing frustum intersection test

### LINKED ISSUE #9321: [1.19.3] Block entities using INFINITE_EXTENT_AABB don't render at all angles
Starting from 1.19.3, returning `INFINITE_EXTENT_AABB` from `getRenderBoundingBox` has stopped working as it should. When looking up or down at a block entity using this, they don't render. Here's an example with beacons: 

Forge
image

Vanilla

I assume this is due to vanilla now using JOML's `FrustumIntersection` instead of its own frustum checks.

### PR DESCRIPTION
**Pull request by XFactHD**
This PR fixes infinite block entity render bounds failing the frustum intersection test at certain angles, closes #9321.

As suspected by the OP of the linked issue, this is caused by the use of JOML's `FrustumIntersection` where a bunch of vector dot products were used previously. The reason is that for the affected camera angles, certain values in the `FrustumIntersection` become 0 and then get multiplied with positive or negative infinity from the AABB which results in NaN and therefore fails all comparisons. This means that the infinite AABB needs to be special-cased since even the use of `-Double.MAX_VALUE` and `Double.MAX_VALUE` as the bounds ultimately leads to positive and negative infinity when the camera coordinates are subtracted from the bounds in Frustum#isVisible().

### CODE REVIEW

File: patches/minecraft/net/minecraft/client/renderer/culling/Frustum.java.patch [hunk 1]
```diff
@@ -0,0 +1,11 @@
+--- a/net/minecraft/client/renderer/culling/Frustum.java
++++ b/net/minecraft/client/renderer/culling/Frustum.java
+@@ -59,6 +_,8 @@
+    }
+ 
+    public boolean m_113029_(AABB p_113030_) {
++      //FORGE: exit early for infinite bounds, these would otherwise fail in the intersection test at certain camera angles
```
Comment (sciwhiz12) [inline patches/minecraft/net/minecraft/client/renderer/culling/Frustum.java.patch]: Space between the comment marker and `FORGE`. Also, I'm thinking whether to include the issue number, for future reference.

```suggestion
+      // FORGE: exit early for infinite bounds, these would otherwise fail in the intersection test at certain camera angles (GH-9321)
```

**Review by sciwhiz12 — CHANGES_REQUESTED** [review]
Works fine in testing.

**Review by sciwhiz12 — APPROVED** [review]
