### PR TITLE
1.20.x on creative mode tabs build contents fix

### LINKED ISSUE #9662: CreativeModeTabs are NOT a client only class yet they call forge client only events making them effectively be one.
As I've said CreativeModeTabs are a class that dont get stripped and isnt marked as client only. In previous versions one could access their condent on a logical server for various reasons (such as getting all items that were "intented" to be show ingame, grouping items by their categories to give to players and such).
From 1.20 forge calls ` ForgeHooksClient.onCreativeModeTabBuildContents()`, a method which loads a bunch of client classes making the entire process fail. This isnt even "fool proof" as one might accidantally calls any of those methods that rebuild content for whatever reason (whcih is totally valid as as I've said those are not in the client package)
I suggest to just move the event out of that client hooks class into the common one making it server safe

### PR DESCRIPTION
**Pull request by RealMangorage**
This fixes https://github.com/MinecraftForge/MinecraftForge/issues/9662 by moving ForgeHooksClient.onCreativeModeTabBuildContents() to ForgeHooks.java

### CODE REVIEW

File: src/main/java/net/minecraftforge/client/ForgeHooksClient.java [hunk 1]
```diff
@@ -1201,6 +1201,7 @@ public static ResourceLocation getShaderImportLocation(String basePath, boolean
         return new ResourceLocation(loc.getNamespace(), normalised);
     }
 
+    @Deprecated
```
Comment (Jonathing) [inline src/main/java/net/minecraftforge/client/ForgeHooksClient.java]: Please mark this as for removal.
```java
@Deprecated(forRemoval = true, since = "1.20.1")
// ...
```

**Review by Jonathing — CHANGES_REQUESTED** [review]

**Review by Jonathing — APPROVED** [review]
Look good. Thanks for doing the initial testing we discussed in #github-discussions. I think it might be nice to include a small description of what caused the issue and how you debugged it as discussed, but it's not necessary.
