### PR TITLE
Fix crafting causing crash

### LINKED ISSUE #3387: [1.11] Crafting crashes the game?
Using 1.11-forge1.11-13.19.0.2130

Crafting anything appears to cause a game crash.  Tested with Iron Pickaxe and Wood Planks in Creative and Survival.

fml-client-latest.log: http://ix.io/1Fxp

### PR DESCRIPTION
**Pull request by shadowfacts**
Closes #3387 

`getContainerItem` can return `null`, causing a crash when it's inserted into a `NonNullList`.

### CODE REVIEW

File: src/main/java/net/minecraftforge/common/ForgeHooks.java [hunk 1]
```diff
@@ -943,7 +943,10 @@ public static boolean onNoteChange(TileEntityNote te, byte old)
         NonNullList<ItemStack> ret = NonNullList.func_191197_a(inv.getSizeInventory(), ItemStack.field_190927_a);
         for (int i = 0; i < ret.size(); i++)
         {
-            ret.set(i, getContainerItem(inv.getStackInSlot(i)));
+            ItemStack container = getContainerItem(inv.getStackInSlot(i));
+            if (container != null) {
+                ret.set(i, container);
+            }
         }
```
Comment (LexManos) [inline src/main/java/net/minecraftforge/common/ForgeHooks.java:949]: The PROPER solution would be to make getContainerItem NOT return null, as Null ItemStacks are not valid anymore in 1.11

**Comment by shadowfacts** [comment]
Fixed

File: src/main/java/net/minecraftforge/common/ForgeHooks.java [hunk 2]
```diff
@@ -957,21 +959,22 @@ public static EntityPlayer getCraftingPlayer()
     {
         return craftingPlayer.get();
     }
+    @Nonnull
     public static ItemStack getContainerItem(ItemStack stack)
     {
-        if (stack == null) return null;
+        if (stack == null) return ItemStack.field_190927_a;
```
Comment (LexManos) [inline src/main/java/net/minecraftforge/common/ForgeHooks.java]: Input should never be null either. Seriously NO ITEMSTACK should ever be null.

**Comment by shadowfacts** [comment]
Fixed

File: src/main/java/net/minecraftforge/common/ForgeHooks.java [hunk 3]
```diff
@@ -957,21 +959,20 @@ public static EntityPlayer getCraftingPlayer()
     {
         return craftingPlayer.get();
     }
-    public static ItemStack getContainerItem(ItemStack stack)
+    @Nonnull
+    public static ItemStack getContainerItem(@Nonnull ItemStack stack)
     {
-        if (stack == null) return null;
-
         if (stack.getItem().hasContainerItem(stack))
```
Comment (HenryLoenwind) [inline src/main/java/net/minecraftforge/common/ForgeHooks.java:965]: Isn't it possible to have an invalid stack that has an item which has a container item as the input here?

Comment (LexManos) [reply src/main/java/net/minecraftforge/common/ForgeHooks.java:965]: Air does not have a container

Comment (HenryLoenwind) [reply src/main/java/net/minecraftforge/common/ForgeHooks.java:965]: Is AIR the only invalid itemStack? (Sorry I don't have a 1.11 workspace to actually look at itemStack, hotel wifi is rubbish and my data plan is used up). My understanding (based on early rumors) was that any itemstack could become invalid e.g. by getting down to stacksize 0.  Sorry again to bother you if that's wrong.
