### PR TITLE
[1.21.4] Add fast graphics render type to block models

### LINKED ISSUE #10389: Fast Graphics doesn’t adjust RenderTypes when they are done in json
**Minecraft Version:** 1.20.1-1.21.x

**Forge Version:** all for all those versions

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report} N/A

**Steps to Reproduce:**
 1. Make a custom block give it a cutout render type
 2. Load into game on fancy and view that you can see through it
 3. Change graphics to fast you can still see through the block

**Description of issue:**
Vanilla when going on fast graphics makes stuff like leaves not able to be seen through.  If you use the json render type in forge tho this isn’t respected causing performance issues.

### PR DESCRIPTION
**Pull request by Jonathing**
This PR was primarily created to address the issue of model JSON-based render types overriding vanilla's behavior of giving any instance of `LeavesBlock` the solid render type. However, I figured since the issue needed to be fixed anyway, I also added the `"render_type_fast"` member to the model json which gives the ability for modders to add fast graphics render types to their models.

As it is implied, fast graphics render types are only used when the game is set to fast graphics in the options menu. This property is checked using `!ItemBlockRenderLayers.isFancy()` which itself is set by vanilla in the level renderer. Traditionally in vanilla, all blocks only adhere to the render type that is given to them in this class. However since Forge uses render types as defined in the model's JSON file, it attempts to use that first *before* defaulting back to the vanilla logic of first checking for leaves and then getting the block's render type.

> [!IMPORTANT]
> Since item models have changed in 1.21.4, there is no additional check for item stacks as block items for leaves. That has be accounted for in backports to older versions, however.

The system implemented in `SimpleBakedModel` will first check if we are in fast graphics and attempt to use any defined fast graphics render types. If none exist, then we check if the main render type is rendering cutout (either cutout or cutout mipped) *and* if the block we are rendering for is an instance of `LeavesBlock`. If both of these conditions are met, then we render the solid render type. Render types in the fancy graphics mode remain unaffected. 

> [!NOTE]
> While this might seem unnecessary, it is to account for backwards compatibility with block models that will likely not be regenerated to add in a fast graphics render type. All previously existing item models will continue to work under this extension of the system.

I've added `-WithRenderTypeAndFast` sister method variants to all the related methods in `BlockStateProvider` to account for this change. An important thing to note is that I've modified the default `leaves` method in `ModelProvider` to use a normal render type of `"cutout_mipped"` and a fast graphics render type of `"solid"`.

- Fixes #10389 for 1.21.4.
- Although it may seem unreasonable, I've kept binary compatibility even for private and package-private methods. I am aware that some cheeky coremods might be hooking into these systems that I am modifying.

### CODE REVIEW

**Comment by Jonathing** [comment]
Ready for review. I wrote some test mods but they rely on the client's current graphics setting to test which render types to get. I would change it in the test itself, but I have no idea if these tests are run in parallel or not and don't want to risk it.

File: src/main/java/net/minecraftforge/client/model/generators/loaders/ItemLayerModelBuilder.java [hunk 1]
```diff
@@ -176,6 +213,14 @@ public JsonObject toJson(JsonObject json)
         });
         json.add("render_types", renderTypes);
 
+        JsonObject renderTypesFast = new JsonObject();
+        this.renderTypes.forEach((renderType, layers) -> {
```
Comment (LexManos) [inline src/main/java/net/minecraftforge/client/model/generators/loaders/ItemLayerModelBuilder.java]: copy paste error

File: patches/minecraft/net/minecraft/client/renderer/ItemBlockRenderTypes.java.patch [hunk 2]
```diff
@@ -75,7 +85,7 @@
 +    });
 +
 +    /** @deprecated Use {@link net.minecraft.client.resources.model.BakedModel#getRenderTypes(BlockState, net.minecraft.util.RandomSource, net.minecraftforge.client.model.data.ModelData)}. */
-+    //@Deprecated(since = "1.19", forRemoval = true)
++    @Deprecated(since = "1.19")
```
Comment (LexManos) [inline patches/minecraft/net/minecraft/client/renderer/ItemBlockRenderTypes.java.patch]: deprecated

File: patches/minecraft/net/minecraft/client/renderer/ItemBlockRenderTypes.java.patch [hunk 3]
```diff
@@ -86,20 +96,20 @@
 +    }
 +
 +    /** @deprecated Set your render type in your block model's JSON (eg. {@code "render_type": "cutout"}) or override {@link net.minecraft.client.resources.model.BakedModel#getRenderTypes(BlockState, net.minecraft.util.RandomSource, net.minecraftforge.client.model.data.ModelData)} */
-+    //@Deprecated(since = "1.19", forRemoval = true)
++    @Deprecated(since = "1.19")
```
Comment (LexManos) [inline patches/minecraft/net/minecraft/client/renderer/ItemBlockRenderTypes.java.patch]: deprecated

File: patches/minecraft/net/minecraft/client/renderer/ItemBlockRenderTypes.java.patch [hunk 4]
```diff
@@ -86,20 +96,20 @@
...
 +    public static void setRenderLayer(Block block, RenderType type) {
 +       com.google.common.base.Preconditions.checkArgument(type.getChunkLayerId() >= 0, "The argument must be a valid chunk render type returned by RenderType#chunkBufferLayers().");
 +       setRenderLayer(block, net.minecraftforge.client.ChunkRenderTypeSet.of(type));
 +    }
 +
 +    /** @deprecated Set your render type in your block model's JSON (eg. {@code "render_type": "cutout"}) or override {@link net.minecraft.client.resources.model.BakedModel#getRenderTypes(BlockState, net.minecraft.util.RandomSource, net.minecraftforge.client.model.data.ModelData)} */
-+    //@Deprecated(since = "1.19", forRemoval = true)
++    @Deprecated(since = "1.19")
```
Comment (LexManos) [inline patches/minecraft/net/minecraft/client/renderer/ItemBlockRenderTypes.java.patch]: deprecated

File: patches/minecraft/net/minecraft/client/renderer/ItemBlockRenderTypes.java.patch [hunk 5]
```diff
@@ -86,20 +96,20 @@
...
 +    public static synchronized void setRenderLayer(Block block, java.util.function.Predicate<RenderType> predicate) {
 +       setRenderLayer(block, createSetFromPredicate(predicate));
 +    }
 +
 +    /** @deprecated Set your render type in your block model's JSON (eg. {@code "render_type": "cutout"}) or override {@link net.minecraft.client.resources.model.BakedModel#getRenderTypes(BlockState, net.minecraft.util.RandomSource, net.minecraftforge.client.model.data.ModelData)} */
-+    //@Deprecated(since = "1.19", forRemoval = true)
++    @Deprecated(since = "1.19")
```
Comment (LexManos) [inline patches/minecraft/net/minecraft/client/renderer/ItemBlockRenderTypes.java.patch]: deprecated

File: patches/minecraft/net/minecraft/client/renderer/ItemBlockRenderTypes.java.patch [hunk 6]
```diff
@@ -86,20 +96,20 @@
...
 +    /** @deprecated Set your render type in your block model's JSON (eg. {@code "render_type": "cutout"}) or override {@link net.minecraft.client.resources.model.BakedModel#getRenderTypes(BlockState, net.minecraft.util.RandomSource, net.minecraftforge.client.model.data.ModelData)} */
-+    //@Deprecated(since = "1.19", forRemoval = true)
++    @Deprecated(forRemoval = true, since = "1.19")
 +    public static synchronized void setRenderLayer(Block block, java.util.function.Predicate<RenderType> predicate) {
 +       setRenderLayer(block, createSetFromPredicate(predicate));
 +    }
 +
 +    /** @deprecated Set your render type in your block model's JSON (eg. {@code "render_type": "cutout"}) or override {@link net.minecraft.client.resources.model.BakedModel#getRenderTypes(BlockState, net.minecraft.util.RandomSource, net.minecraftforge.client.model.data.ModelData)} */
-+    //@Deprecated(since = "1.19", forRemoval = true)
++    @Deprecated(forRemoval = true, since = "1.19")
```
Comment (LexManos) [inline patches/minecraft/net/minecraft/client/renderer/ItemBlockRenderTypes.java.patch]: All of these need updating to 1.21.4 as it breaks the build

File: patches/minecraft/net/minecraft/client/resources/model/SimpleBakedModel.java.patch [hunk 7]
```diff
@@ -1,104 +1,181 @@
...
-@@ -29,6 +_,17 @@
+@@ -29,7 +_,33 @@
      private final boolean usesBlockLight;
      private final TextureAtlasSprite particleIcon;
      private final ItemTransforms transforms;
+-
++    /** Forge: Block render types to be used with {@linkplain net.minecraft.client.GraphicsStatus#FANCY fancy graphics} */
 +    protected final net.minecraftforge.client.ChunkRenderTypeSet blockRenderTypes;
++    /** Forge: Block render types to be used with {@linkplain net.minecraft.client.GraphicsStatus#FANCY fast graphics} */
++    protected final net.minecraftforge.client.ChunkRenderTypeSet blockRenderTypesFast;
```
Comment (LexManos) [inline patches/minecraft/net/minecraft/client/resources/model/SimpleBakedModel.java.patch:11]: The comment is FANCY on both

File: patches/minecraft/net/minecraft/client/resources/model/SimpleBakedModel.java.patch [hunk 8]
```diff
@@ -1,104 +1,181 @@
...
 +    /*
++    /** Forge: Item render types to be used with {@linkplain net.minecraft.client.GraphicsStatus#FANCY fancy graphics} * /
 +    protected final List<net.minecraft.client.renderer.RenderType> itemRenderTypes;
++    /** Forge: Item render types to be used with {@linkplain net.minecraft.client.GraphicsStatus#FAST fast graphics} * /
```
Comment (LexManos) [inline patches/minecraft/net/minecraft/client/resources/model/SimpleBakedModel.java.patch]: All this is commented out, probably worth just deleting until item parts get implemented.

File: patches/minecraft/net/minecraft/client/resources/model/SimpleBakedModel.java.patch [hunk 9]
```diff
@@ -1,104 +1,181 @@
...
++    /** @deprecated Forge: Use {@linkplain #SimpleBakedModel(List, Map, boolean, boolean, boolean, TextureAtlasSprite, ItemTransforms, net.minecraftforge.client.RenderTypeGroup, net.minecraftforge.client.RenderTypeGroup) variant with RenderTypeGroup} **/
 +    @Deprecated
 +    public SimpleBakedModel(List<BakedQuad> p_119489_, Map<Direction, List<BakedQuad>> p_119490_, boolean p_119491_, boolean p_119492_, boolean p_119493_, TextureAtlasSprite p_119494_, ItemTransforms p_119495_) {
 +        this(p_119489_, p_119490_, p_119491_, p_119492_, p_119493_, p_119494_, p_119495_, net.minecraftforge.client.RenderTypeGroup.EMPTY);
 +    }
- 
++
++    /** Forge: Consider using {@linkplain #SimpleBakedModel(List, Map, boolean, boolean, boolean, TextureAtlasSprite, ItemTransforms, net.minecraftforge.client.RenderTypeGroup, net.minecraftforge.client.RenderTypeGroup) variant with RenderTypeGroup for fast graphics} **/
++    public SimpleBakedModel(List<BakedQuad> p_119489_, Map<Direction, List<BakedQuad>> p_119490_, boolean p_119491_, boolean p_119492_, boolean p_119493_, TextureAtlasSprite p_119494_, ItemTransforms p_119495_, net.minecraftforge.client.RenderTypeGroup renderTypes) {
```
Comment (LexManos) [inline patches/minecraft/net/minecraft/client/resources/model/SimpleBakedModel.java.patch:23]: Deprecated, for removal 1.21.4
