### PR TITLE
[1.21.4] Give ItemStack context to IForgeItem.getCapabilityProvider

### LINKED ISSUE #10403: [1.21.4] No access to ItemStack in Item#getCapabilityProvider
**Minecraft Version:** 1.21.4

**Forge Version:** 54.0.34

**Logs:** N/A

**Steps to Reproduce:** N/A

**Description of issue:**

Before item capabilities were removed/broken in 1.20.6, the `Item#initCapabilities` method had an `ItemStack` parameter, allowing the capability handler instance to store a reference to it. In particular, this was used by `IFluidHandlerItem` to reference the container item.

The `Item#getCapabilityProvider` method introduced in https://github.com/MinecraftForge/MinecraftForge/pull/10324 no longer has this parameter, making it difficult to store data using item components as is intended in the new design. The test mod from the PR uses `AttachCapabilitiesEvent` instead, which doesn't have this issue.

### PR DESCRIPTION
**Pull request by Jonathing**
Name entails. This isn't an issue when using `AttachCapabilitiesEvent<ItemStack>` since the item stack object is given there, but when overriding `IForgeItem.getCapabilityProvider`, the modder does not have access to the actual item stack that capabilities are being gathered for.

- Fixes #10403.

### CODE REVIEW

**Comment by Jonathing** [comment]
Backports of the Item Capabilities PRs that have not yet been merged now include this PR.

File: src/main/java/net/minecraftforge/common/extensions/IForgeItem.java [hunk 1]
```diff
@@ -615,9 +615,18 @@ default boolean canGrindstoneRepair(ItemStack stack) {
 
     /**
      * @return The Default Capability Provider for this item, if any.
+     *
+     * @deprecated Use the itemstack-sensitive version instead: {@link #getCapabilityProvider(ItemStack)}
      */
     @Nullable
+    @Deprecated(forRemoval = true)
     default ICapabilityProvider getCapabilityProvider() {
```
Comment (LexManos) [inline src/main/java/net/minecraftforge/common/extensions/IForgeItem.java:623]: since="1.21.4"
