### PR TITLE
Fix CustomModLoadingErrorDisplayScreen not being handled during init or preinit.

### LINKED ISSUE #4319: CustomModLoadingErrorDisplayException not working.
When you throw a CustomModLoadingErrorDisplayException in preInit or init FML will catch the exception and exit the game instead of displaying the error.

Here's some sample code used to produce the issue as well as the stacktrace produced by FML: https://gist.github.com/darkevilmac/8e468c1b676f1d986f4b5c2618577ec0
Tested with Forge 1.12.1-14.22.0.2456

### PR DESCRIPTION
**Pull request by darkevilmac**
Also adds missing buttons to GuiCustomModLoadingErrorScreen.

This fixes #4319

### CODE REVIEW

File: src/main/java/net/minecraftforge/fml/client/GuiCustomModLoadingErrorScreen.java [hunk 1]
```diff
@@ -19,27 +19,25 @@
...
-import net.minecraft.client.gui.GuiErrorScreen;
-
-public class GuiCustomModLoadingErrorScreen extends GuiErrorScreen
+public class GuiCustomModLoadingErrorScreen extends GuiErrorBase
 {
     private CustomModLoadingErrorDisplayException customException;
     public GuiCustomModLoadingErrorScreen(CustomModLoadingErrorDisplayException customException)
     {
-        super(null,null);
+        super();
```
Comment (mezz) [inline src/main/java/net/minecraftforge/fml/client/GuiCustomModLoadingErrorScreen.java]: you can remove call to super with no arguments

File: src/main/java/net/minecraftforge/fml/client/FMLClientHandler.java [hunk 2]
```diff
@@ -390,7 +391,8 @@ public void finishMinecraftLoading()
         }
         loading = false;
         client.gameSettings.loadOptions(); //Reload options to load any mod added keybindings.
-        Loader.instance().loadingComplete();
+        if(customError == null)
```
Comment (mezz) [inline src/main/java/net/minecraftforge/fml/client/FMLClientHandler.java]: spaces

File: src/main/java/net/minecraftforge/fml/client/FMLClientHandler.java [hunk 3]
```diff
@@ -342,17 +344,16 @@ public void finishMinecraftLoading()
...
-            FMLLog.log.error("A custom exception was thrown by a mod, the game will now halt", custom);
-            customError = custom;
-            SplashProgress.finish();
-            return;
-        }
         catch (LoaderException le)
         {
-            haltGame("There was a severe problem during mod loading that has caused the game to fail", le);
-            return;
+            if(le.getCause() instanceof CustomModLoadingErrorDisplayException){
```
Comment (mezz) [inline src/main/java/net/minecraftforge/fml/client/FMLClientHandler.java]: spaces

File: src/main/java/net/minecraftforge/fml/client/FMLClientHandler.java [hunk 4]
```diff
@@ -265,16 +265,18 @@ public void beginMinecraftLoading(Minecraft minecraft, List<IResourcePack> resou
...
-        catch (CustomModLoadingErrorDisplayException custom)
-        {
-            FMLLog.log.error("A custom exception was thrown by a mod, the game will now halt", custom);
-            customError = custom;
-        }
         catch (LoaderException le)
         {
-            haltGame("There was a severe problem during mod loading that has caused the game to fail", le);
-            return;
+            if(le.getCause() instanceof CustomModLoadingErrorDisplayException){
```
Comment (mezz) [inline src/main/java/net/minecraftforge/fml/client/FMLClientHandler.java]: spaces

File: src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java [hunk 5]
```diff
@@ -0,0 +1,54 @@
...
+import net.minecraft.client.gui.GuiErrorScreen;
+import net.minecraftforge.fml.client.CustomModLoadingErrorDisplayException;
+import net.minecraftforge.fml.common.Mod;
+import net.minecraftforge.fml.common.event.FMLInitializationEvent;
+import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
+import net.minecraftforge.fml.relauncher.Side;
+import net.minecraftforge.fml.relauncher.SideOnly;
+
+@Mod(modid = "clientexceptiontest", version = "0", name = "Client Exception Test")
+public class ClientExceptionTestMod {
```
Comment (mezz) [inline src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java]: braces on new lines

File: src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java [hunk 6]
```diff
@@ -0,0 +1,54 @@
...
+
+    // Disabled so other test mods can still work.
+    public static boolean ENABLE_PREINIT = false, ENABLE_INIT = false;
+    private static String LOREM_IPSUM = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.";
+
+    @Mod.EventHandler
+    @SideOnly(Side.CLIENT)
+    public void onPreInit(FMLPreInitializationEvent e) {
```
Comment (mezz) [inline src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java]: braces on new lines

File: src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java [hunk 7]
```diff
@@ -0,0 +1,54 @@
...
+        if (ENABLE_PREINIT) {
+            throw new CustomModLoadingErrorDisplayException("Custom Test Exception", new RuntimeException("Thrown in Pre-Init")) {
+                @Override
+                public void initGui(GuiErrorScreen parent, FontRenderer fontRenderer) {
```
Comment (mezz) [inline src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java]: braces on new lines

File: src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java [hunk 8]
```diff
@@ -0,0 +1,54 @@
...
+                    parent.drawCenteredString(parent.mc.fontRenderer, LOREM_IPSUM, parent.width / 2, 110, 16777215);
+                }
+            };
+        }
+    }
+
+    @Mod.EventHandler
+    @SideOnly(Side.CLIENT)
+    public void onInit(FMLInitializationEvent e) {
+        if (ENABLE_INIT) {
```
Comment (mezz) [inline src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java]: braces on new lines etc

File: src/main/java/net/minecraftforge/fml/client/FMLClientHandler.java [hunk 9]
```diff
@@ -342,17 +344,16 @@ public void finishMinecraftLoading()
...
+                CustomModLoadingErrorDisplayException custom = (CustomModLoadingErrorDisplayException) le.getCause();
+                FMLLog.log.error("A custom exception was thrown by a mod, the game will now halt", custom);
+                customError = custom;
+            } else {
```
Comment (mezz) [inline src/main/java/net/minecraftforge/fml/client/FMLClientHandler.java]: braces on new lines

File: src/main/java/net/minecraftforge/fml/client/FMLClientHandler.java [hunk 10]
```diff
@@ -265,16 +265,18 @@ public void beginMinecraftLoading(Minecraft minecraft, List<IResourcePack> resou
...
```
Comment (mezz) [inline src/main/java/net/minecraftforge/fml/client/FMLClientHandler.java]: braces on new lines

File: src/main/java/net/minecraftforge/fml/client/FMLClientHandler.java (hunk 4 above)
Comment (mezz) [reply src/main/java/net/minecraftforge/fml/client/FMLClientHandler.java]: braces on new lines

File: src/main/java/net/minecraftforge/fml/client/FMLClientHandler.java (hunk 3 above)
Comment (mezz) [reply src/main/java/net/minecraftforge/fml/client/FMLClientHandler.java]: braces on new lines

**Review by mezz — CHANGES_REQUESTED** [review]
style review

**Review by mezz — APPROVED** [review]

File: src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java [hunk 11]
```diff
@@ -0,0 +1,61 @@
...
+import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
+import net.minecraftforge.fml.relauncher.Side;
+import net.minecraftforge.fml.relauncher.SideOnly;
+
+@Mod(modid = "clientexceptiontest", version = "0", name = "Client Exception Test")
+public class ClientExceptionTestMod
+{
+
+    // Disabled so other test mods can still work.
+    public static boolean ENABLE_PREINIT = false, ENABLE_INIT = true;
```
Comment (mezz) [inline src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java]: This shouldn't be active by default

**Review by mezz — CHANGES_REQUESTED** [review]

File: src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java (hunk 11 above)
Comment (darkevilmac) [reply src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java]: Oops.

**Review by mezz — APPROVED** [review]

File: src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java [hunk 12]
```diff
@@ -0,0 +1,61 @@
...
+import net.minecraft.client.gui.FontRenderer;
+import net.minecraft.client.gui.GuiErrorScreen;
+import net.minecraftforge.fml.client.CustomModLoadingErrorDisplayException;
+import net.minecraftforge.fml.common.Mod;
+import net.minecraftforge.fml.common.event.FMLInitializationEvent;
+import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
+import net.minecraftforge.fml.relauncher.Side;
+import net.minecraftforge.fml.relauncher.SideOnly;
+
+@Mod(modid = "clientexceptiontest", version = "0", name = "Client Exception Test")
```
Comment (howtonotwin) [inline src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java]: snake_case is the convention for modids, and Forge recommends semantic versioning for mods. I think most test mods do something like `0.0.0.0` or `0.0.0.1`.

File: src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java [hunk 13]
```diff
@@ -0,0 +1,61 @@
...
+    public static boolean ENABLE_PREINIT = false, ENABLE_INIT = false;
+    private static String LOREM_IPSUM = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.";
+
+    @Mod.EventHandler
+    @SideOnly(Side.CLIENT)
+    public void onPreInit(FMLPreInitializationEvent e)
+    {
+        if (ENABLE_PREINIT)
+        {
+            throw new CustomModLoadingErrorDisplayException("Custom Test Exception", new RuntimeException("Thrown in Pre-Init"))
```
Comment (howtonotwin) [inline src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java]: Maybe put up a note that says "From ClientExceptionTestMod" in case this somehow gets turned on and the user doesn't know exactly where to turn it off. The circumstances are arguable, but when a test mod kills the entire game, clarity is always good.

File: src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java [hunk 14]
```diff
@@ -0,0 +1,61 @@
...
+@Mod(modid = "clientexceptiontest", version = "0", name = "Client Exception Test")
+public class ClientExceptionTestMod
+{
+
+    // Disabled so other test mods can still work.
+    public static boolean ENABLE_PREINIT = false, ENABLE_INIT = false;
+    private static String LOREM_IPSUM = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.";
+
+    @Mod.EventHandler
+    @SideOnly(Side.CLIENT)
```
Comment (howtonotwin) [inline src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java]: `@SideOnly` is a no-no. Test mods should follow best practices as examples for others. Use `@SidedProxy` with nested static classes.

File: src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java [hunk 15]
```diff
@@ -0,0 +1,61 @@
...
+    public void onPreInit(FMLPreInitializationEvent e)
+    {
+        if (ENABLE_PREINIT)
+        {
+            throw new CustomModLoadingErrorDisplayException("Custom Test Exception", new RuntimeException("Thrown in Pre-Init"))
+            {
```
Comment (howtonotwin) [inline src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java]: Would be cleaner with a nested class.

**Review by howtonotwin — CHANGES_REQUESTED** [review]
Just a few nitpicks

**Comment by howtonotwin** [comment]
Seeing that your already working on this: would it be a good idea to make this work in postinit too? I can't think of a usecase myself, but it might be useful.

File: src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java (hunk 12 above)
Comment (liach) [reply src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java]: 1. That is already a good mod id: they follow package naming convention instead of snake case
2. `0` is a sematic version.

File: src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java (hunk 14 above)
Comment (liach) [reply src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java]: Client ones are good, in general. Server ones often cause crashes when it is on the client.

File: src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java (hunk 13 above)
Comment (liach) [reply src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java]: Most people that use test mods are developers. They can see the stack trace.

File: src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java (hunk 15 above)
Comment (liach) [reply src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java]: No need for extra lines of code.

File: src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java (hunk 12 above)
Comment (howtonotwin) [reply src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java]: http://semver.org disagrees, officially linked to in https://mcforge.readthedocs.io/en/latest/conventions/versioning/

(Though I did get a bunch of things wrong: `0.0.1` would be a semantic version, and Forge supplies its own versioning scheme based on it, where the version would be `0.0.0.1`.)

File: src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java (hunk 15 above)
Comment (howtonotwin) [reply src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java]: That would be *fewer* lines of code, which is why I suggested it.

File: src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java (hunk 14 above)
Comment (howtonotwin) [reply src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java]: Lex has repeatedly said not to use `@SideOnly`,  ever.

File: src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java (hunk 12 above)
Comment (LexManos) [reply src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java]: Versioning only matters that we can determine A's relation to B.
The number of segments in your string doesn't matter. All that matters is that its numbers separated by periods.
1 == 1.0.0.0.0.0.0....
1 > 0.2 as it will be treated at 1.0 vs 0.2

**Review by liach — APPROVED** [review]

File: src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java (hunk 15 above)
Comment (darkevilmac) [reply src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java]: This is just a really simple test mod, no need to make it more complicated than necessary imo.

File: src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java (hunk 13 above)
Comment (darkevilmac) [reply src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java]: Ya there's pretty much no use case that this will ever get turned on by a user, if someone manually changes the boolean in here they should know what they're doing.

File: src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java (hunk 14 above)
Comment (darkevilmac) [reply src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java]: This mod is client side only and should only be executed on the client. A proxy seems redundant.

File: src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java (hunk 15 above)
Comment (howtonotwin) [reply src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java]: Again, test mods are meant to be good examples. Writing the same thing twice is not a good example.

File: src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java (hunk 14 above)
Comment (liach) [reply src/test/java/net/minecraftforge/debug/ClientExceptionTestMod.java]: https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fml/common/Mod.java#L135

**Review by howtonotwin — APPROVED** [review]

**Comment by darkevilmac** [comment]
I think that's everything, this should be good to merge.

File: src/main/java/net/minecraftforge/fml/client/FMLClientHandler.java [hunk 16]
```diff
@@ -342,17 +347,19 @@ public void finishMinecraftLoading()
...
-            FMLLog.log.error("A custom exception was thrown by a mod, the game will now halt", custom);
-            customError = custom;
-            SplashProgress.finish();
-            return;
-        }
         catch (LoaderException le)
         {
-            haltGame("There was a severe problem during mod loading that has caused the game to fail", le);
-            return;
+            if (le.getCause() instanceof CustomModLoadingErrorDisplayException)
```
Comment (thilokru) [inline src/main/java/net/minecraftforge/fml/client/FMLClientHandler.java:352]: Your added code fragments in `beginMinecraftLoading()` and `finishMinecraftLoading()` seem identical. I'd suggest moving it into a method, so that changes are easier to apply in the future.

**Review by thilokru — COMMENTED** [review]
Minor Refactoring Suggestion.

File: src/main/java/net/minecraftforge/fml/client/FMLClientHandler.java (hunk 16 above)
Comment (darkevilmac) [reply src/main/java/net/minecraftforge/fml/client/FMLClientHandler.java:352]: This is the same as how FML was doing this previously, I just moved it into a different catch so the exception doesn't get missed.

Comment (howtonotwin) [reply src/main/java/net/minecraftforge/fml/client/FMLClientHandler.java:352]: If you're going to mess with it, you may as well leave it better than it was before.

Comment (darkevilmac) [reply src/main/java/net/minecraftforge/fml/client/FMLClientHandler.java:352]: My goal isn't to mess with it, it's to fix a bug. Adding a method just to handle an exception seems... excessive.

File: src/main/java/net/minecraftforge/fml/client/FMLClientHandler.java [hunk 17]
```diff
@@ -265,16 +265,21 @@ public void beginMinecraftLoading(Minecraft minecraft, List<IResourcePack> resou
         {
             Loader.instance().preinitializeMods();
         }
-        catch (CustomModLoadingErrorDisplayException custom)
-        {
-            FMLLog.log.error("A custom exception was thrown by a mod, the game will now halt", custom);
-            customError = custom;
-        }
         catch (LoaderException le)
```
Comment (liach) [inline src/main/java/net/minecraftforge/fml/client/FMLClientHandler.java:268]: I think you should let the loader fall the CustomModLoadingErrorDisplayException through, or is that worse?

Comment (darkevilmac) [reply src/main/java/net/minecraftforge/fml/client/FMLClientHandler.java:268]: This exception is client side, the loader is common so it needs to be dealt with in the FMLClientHandler.

**Comment by darkevilmac** [comment]
I'd really like to be able to use this in my mod to make things clearer for end users, is there anything else that I can do to speed this up at all?

**Comment by LexManos** [comment]
Is there no path that would allow the Custom exception to be the top level? You're removing the handler for it so that it'd be skipped over if anyone tossed it in a path that didnt get wrapped in a LoadException

**Comment by darkevilmac** [comment]
> Is there no path that would allow the Custom exception to be the top level? You're removing the handler for it so that it'd be skipped over if anyone tossed it in a path that didnt get wrapped in a LoadException

Not that I saw no, not sure how someone would manage to throw an exception and have it not get wrapped during init or preinit though.

**Comment by LexManos** [comment]
Sure, we'll go with it, lets see if it breaks anything in existing mods. Pretty sure things could throw exceptions that arnt wrapped but don't have time to dig through it all.
