### PR TITLE
[1.20.x] Fix double message encoding in `Channel#toVanillaPacket` #9721

### LINKED ISSUE #9721: [1.20.x] `Channel#toVanillaPacket` encodes messages twice
**Minecraft Version:** 1.20.2

**Forge Version:** 48.0.1

**Logs:** https://gist.github.com/SuperMartijn642/b56470cc6f72fbf66333aefb7643e9bc

**Steps to Reproduce:**
 1. Try to open a container with custom container data through `IForgePlayer#openMenu`
 2. `OpenContainer#encode` gets called twice
 3. The second call results in an exception in the logs and the container does not get opened

**Description of issue:**
When sending custom packets through an instance of Forge's `Channel`, the packet's data gets encoded into a `FriendlyByteBuf`. This happens in the `Channel#toVanillaPacket` method through a `Channel#toBuffer` call. However, when the connection is in the `PLAY` or new `CONFIGURATION` stage, `Channel#toBuffer` gets called twice.
https://github.com/MinecraftForge/MinecraftForge/blob/d80f106140b30813432808f8b94da4d66e76dbfe/src/main/java/net/minecraftforge/network/Channel.java#L44-L64

This causes issues when combined the `OpenContainer` packet. The `OpenContainer` packet has a `FriendlyByteBuf` field for custom container data. In `OpenContainer#encode` the `FriendlyByteBuf` gets read without resetting the reader index, thus when the same packet instance is encoded twice, trying to read from the `FriendlyByteBuf` throws an exception. A log of this happening is included above.

In `Channel#toVanillaPacket`, the result of the first `Channel#toBuffer` call is stored in the `data` variable. Since this method was changed from 1.20.1, it seems like this is a simple oversight and the second `Channel#toBuffer` should simply be replaced with the `data` variable.

### PR DESCRIPTION
**Pull request by SuperMartijn642**
This PR fixes #9721 by replacing the second `Channel#toBuffer` call with the `data` variable.

### CODE REVIEW

**Comment by LexManos** [comment]
Ah whoops small oversight, but it did expose another small issue. Packets are meant to be encodeable multiple times. So OpenContainer needs to reset its index.

**Comment by SuperMartijn642** [comment]
> So OpenContainer needs to reset its index.

Ah seems that was broken in 1.20.1 as well. Do you want me to add that to this PR, since it should just be a one line fix?

**Comment by LexManos** [comment]
Would explain why I missed it. Ya go for it.

**Comment by SuperMartijn642** [comment]
Done 👍

File: src/main/java/net/minecraftforge/network/packets/OpenContainer.java [hunk 1]
```diff
@@ -45,6 +45,7 @@ public static void encode(OpenContainer msg, FriendlyByteBuf buf) {
         buf.writeVarInt(msg.windowId);
         buf.writeComponent(msg.name);
         buf.writeByteArray(msg.additionalData.readByteArray());
+        msg.additionalData.resetReaderIndex();
```
Comment (LexManos) [inline src/main/java/net/minecraftforge/network/packets/OpenContainer.java:49]: You're missing the markReaderIndex

Comment (SuperMartijn642) [reply src/main/java/net/minecraftforge/network/packets/OpenContainer.java:49]: When there's no reader index marked, it just resets the reader index back to 0, which should be fine in this case. I guess it might lead to obscure issues when something messes with the buffer beforehand, so I will add it just to be safe.

Comment (LexManos) [reply src/main/java/net/minecraftforge/network/packets/OpenContainer.java:49]: Always good to be safe. The other option is to use `buf.writeBytes(data, data.readerIndex(), data.readableBytes())` which doesnt modify the indexes at all. Or you could of done `write(data.slice())` so it had its own indexes.
But this was is simple as well.

Comment (SuperMartijn642) [reply src/main/java/net/minecraftforge/network/packets/OpenContainer.java:49]: Ah good to know, I was indeed wondering why some places used `data.slice()` instead of just passing in the buffer itself, now I know. Thanks for the tips!
