### PR TITLE
Non-player entities now respect WorldProvider.getMovementFactor (+ bonus bug)

### LINKED ISSUE #4470: WorldProvider.getMovementFactor not applied to non-player entities?
WorldProvider.getMovementFactor allows one to adjust the 8x nether "fast travel" multiplier

However, it's only patched in in PlayerList and not into Entity.changeDimension, meaning all non-player entities ignore it. Is this intended?

### PR DESCRIPTION
**Pull request by williewillus**
closes #4470 

Previously, getMovementFactor was used for players but non-players used the vanilla hardcoded cases / 8 and * 8 for the nether and returning from nether, respectively. As @mezz noted in #4470 this is probably because entities traveling through portals was introduced in 1.4, after getMovementFactor was added.

Since this logic now runs for all entities, it can be tested by simply tossing items/pushing mobs through a nether portal and making sure they end up where you end up.

### CODE REVIEW

File: patches/minecraft/net/minecraft/server/management/PlayerList.java.patch [hunk 1]
```diff
@@ -189,8 +189,8 @@
 +        net.minecraft.world.WorldProvider pOld = p_82448_3_.field_73011_w;
 +        net.minecraft.world.WorldProvider pNew = p_82448_4_.field_73011_w;
 +        double moveFactor = pOld.getMovementFactor() / pNew.getMovementFactor();
-+        double d0 = p_82448_1_.field_70165_t * moveFactor;
-+        double d1 = p_82448_1_.field_70161_v * moveFactor;
++        double d0 = MathHelper.func_151237_a(p_82448_1_.field_70165_t * moveFactor, p_82448_4_.func_175723_af().func_177726_b() + 16.0D, p_82448_4_.func_175723_af().func_177728_d() - 16.0D);
++        double d1 = MathHelper.func_151237_a(p_82448_1_.field_70161_v * moveFactor, p_82448_4_.func_175723_af().func_177736_c() + 16.0D, p_82448_4_.func_175723_af().func_177733_e() - 16.0D);
```
Comment (williewillus) [inline patches/minecraft/net/minecraft/server/management/PlayerList.java.patch:193]: this is a tangentially related bugfix in the player version of the logic that didn't apply the clamping to the world border that the patched-out vanilla code applies (probably because the patch was made before world borders existed)

Comment (bs2609) [reply patches/minecraft/net/minecraft/server/management/PlayerList.java.patch:193]: #2759?

Comment (williewillus) [reply patches/minecraft/net/minecraft/server/management/PlayerList.java.patch:193]: yes, this change fixes the second part of #2759

**Comment by williewillus** [comment]
any news? this should be complete
