### PR TITLE
Fix incorrect lighting of item models

### LINKED ISSUE #4401: Item models generated by Forge don't match Vanilla
See these screenshots, taken at roughly the same angle:

* Vanilla:
vanilla

* Forge:
forge

In particular the side facing 'up' at that angle is brighter in vanilla, and darker in forge. It should be bright, as that's how vanilla handles shading of faces.

I think [this](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/client/model/ItemLayerModel.java#L375) code, in `ItemLayerModel`, might have something to do with it, but have no idea what the "something else" is supposed to be, so I'm hesitant to change it.

There's also some differences with what parts of the model can be seen through (although this may be intentional, I'm not sure).

### PR DESCRIPTION
**Pull request by bs2609**
Should fix #4401, see there for screenshot examples.

This just changes the code to only call `getOpposite` for y-oriented sides, fixing the current incorrect lighting of quads with sides on the X axis.

### CODE REVIEW

File: src/main/java/net/minecraftforge/client/model/ItemLayerModel.java [hunk 1]
```diff
@@ -372,15 +372,21 @@ private static BakedQuad buildSideQuad(VertexFormat format, Optional<TRSRTransfo
...
             x1, y1, z0, sprite.getInterpolatedU(u1), sprite.getInterpolatedV(v1),
             x1, y1, z1, sprite.getInterpolatedU(u1), sprite.getInterpolatedV(v1),
             x0, y0, z1, sprite.getInterpolatedU(u0), sprite.getInterpolatedV(v0)
         );
     }
 
-    private static final BakedQuad buildQuad(
+    private static EnumFacing remap(EnumFacing side)
+    {
+        // getOpposite is related either to the swapping of V direction, or something else
```
Comment (mezz) [inline src/main/java/net/minecraftforge/client/model/ItemLayerModel.java]: This comment should be clarified or removed, it doesn't make sense to me.

**Review by mezz — CHANGES_REQUESTED** [review]

**Review by mezz — APPROVED** [review]
