### PR TITLE
Adjust light matrix calculations to use per-face logic

### LINKED ISSUE #4049: [1.11] [1.12] Incorrect light transmission to opposite faces of stairs and slabs
Forge has slabs and stairs incorrectly lighting their interior faces when lit by an exterior light source. This affects at least the latest 1.11 and 1.12 versions of Forge.

A tube made from stairs and solid blocks:
https://kek.gg/i/5NjLBg.png
 
Correct lighting in vanilla:
https://kek.gg/i/3zr9Qk.png
 
Incorrect lighting in forge:
https://kek.gg/i/x7c76.png
 
Optifine or other mods are not involved.
 
fml-client-latest.log under 14.21.0.2340:
https://pastebin.com/nQCGA9Br

### PR DESCRIPTION
**Pull request by bs2609**
Fixes #4049.

* Tunnel construct as in issue:

* Same with 'open' stairs on top:

The code [here](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/client/model/pipeline/BlockInfo.java#L124-L134) is what's causing the issue.
Looking at how it affects things:

* With code block (and PR changes):

* Without code block:

It seems to be intended to handle the case for stairs and other non-full blocks which are otherwise opaque. When that code is removed completely, we still get the 'correct' result for the stairs on the top-left, but a different result for the flipped stairs on the top-right.

The solution applied here is to make that code depend on the block side being queried, `doesSideBlockRendering` seemed to be the most appropriate side-aware function available.

### CODE REVIEW

File: src/main/java/net/minecraftforge/client/model/pipeline/BlockInfo.java [hunk 1]
```diff
@@ -114,16 +113,12 @@ public void updateLightMatrix()
...
-                        full = state.isFullCube();
-                    }
                 }
             }
         }
-        if(!full)
+        for(EnumFacing side : EnumFacing.values())
         {
-            for(EnumFacing side : EnumFacing.values())
+            if(!state.getBlock().doesSideBlockRendering(state, world, blockPos, side))
```
Comment (asiekierka) [inline src/main/java/net/minecraftforge/client/model/pipeline/BlockInfo.java]: If you're doing this here, shouldn't you do an analogous change in VertexLighterFlat.updateLightmap?
