### PR TITLE
Fix ScreenEvent.Init.[Pre/Post] not working correctly

### LINKED ISSUE #9418: [1.19.4] ScreenEvent.Init not firing on window resize
**Minecraft Version:** 1.19.4
**Forge Version:** 45.0.22 (Development Enviroment)

Example code:
```java
@SubscribeEvent
public void initGui(ScreenEvent.Init.Post evt) {
	if(evt.getScreen() instanceof TitleScreen) {
		Button btn = Button.builder(Component.literal("Button!"), b -> {}).bounds(0, 0, 100, 20).build();
		evt.addListener(btn);
	}
}
```
The button disappears when the window is resized. It shows up again if you open any other menu and come back.
The `resize` method in Screen no longer calls the `init(mc, w, h)` method, and won't fire the event.

### PR DESCRIPTION
**Pull request by Shadows-of-Fire**
Fixes https://github.com/MinecraftForge/MinecraftForge/issues/9418

This PR moves the firing point for `ScreenEvent.Init` to the correct locations that will enable it to fire both on first init and resize, and reinstate the functionality that allows it to cancel the addition of default screen buttons.

### CODE REVIEW

File: patches/minecraft/net/minecraft/client/gui/screens/Screen.java.patch [hunk 1]
```diff
@@ -165,14 +168,27 @@
...
+          this.f_169422_ = p_169426_;
+       }
+    }
++
++   private void addEventWidget(GuiEventListener b) {
++      if (b instanceof Renderable r)
++         this.f_169369_.add(r);
++      if (b instanceof NarratableEntry ne)
++         this.f_169368_.add(ne);
++         f_96540_.add(b);
```
Comment (ChampionAsh5357) [inline patches/minecraft/net/minecraft/client/gui/screens/Screen.java.patch]: I believe this is a misindentation.

File: patches/minecraft/net/minecraft/client/gui/screens/Screen.java.patch [hunk 2]
```diff
@@ -165,14 +168,27 @@
...
++
     private void m_169380_(long p_169381_, boolean p_169382_) {
+       this.f_169377_ = Util.m_137550_() + p_169381_;
+       if (p_169382_) {
+@@ -734,4 +_,12 @@
+          this.f_169422_ = p_169426_;
+       }
+    }
++
++   private void addEventWidget(GuiEventListener b) {
```
Comment (ChampionAsh5357) [inline patches/minecraft/net/minecraft/client/gui/screens/Screen.java.patch:187]: Shouldn't this method handle the three allowed cases by vanilla?

Method | Renderable | Narratable | Children
:---: | :---: | :---: | :---:
addRenderableWidget | 1 | 1 | 1
addRenderableOnly | 1 | 0 | 0
addWidget | 0 | 1 | 1

**Review by ChampionAsh5357 — CHANGES_REQUESTED** [review]

File: patches/minecraft/net/minecraft/client/gui/screens/Screen.java.patch (hunk 2 above)
Comment (LexManos) [reply patches/minecraft/net/minecraft/client/gui/screens/Screen.java.patch:187]: What would the usecases of this be?
And if we did this we would have to add these mirror methods to the event class itself.
This function is there because we don't want to expose access to inner fields.

Comment (ChampionAsh5357) [reply patches/minecraft/net/minecraft/client/gui/screens/Screen.java.patch:187]: The main issue is that pretty much everything extends `Renderable` and `NarratableEntry` such that everything would be essentially be delegated to `#addRenderableWidget`. So, it's difficult to perform any kind of granularity of if you want to use a preexisting widget but want it only to display.

However, you could also argue vanilla is bad at this since their logic could be front loaded into the widget itself. So, honestly, you can probably just ignore this comment.

Comment (Shadows-of-Fire) [reply patches/minecraft/net/minecraft/client/gui/screens/Screen.java.patch:187]: Given how old this event is and that we haven't had any requests for a different method of widget addition, I think we can call it a non-issue.  If this was desired functionality surely _someone_ would have mentioned something.

Comment (LexManos) [reply patches/minecraft/net/minecraft/client/gui/screens/Screen.java.patch:187]: I'm of the same opinion, if someone wants it, they can ask for it and pull it in later.
This is no reason to delay what is essentially a bug fix.
