### PR TITLE
Fix hardcoded precipitation in ClimateSettingsBuilder

### LINKED ISSUE #9397: [1.19.4] Precipitation doesn't seem to be cancelled in biomes where it should be
**Minecraft Version:** 1.19.4

**Forge Version:** 45.0.9

**Logs:** N/A

**Steps to Reproduce:**
 1. Create a new world.
 2. Locate a desert (e.g. through `/locate biome minecraft:desert`).
 3. Turn precipitation on with `/weather rain`.

**Description of issue:**
Rain/precipitation occurs in biomes where it shouldn't according to `"has_precipitation"`. This extends to modded/datapack biomes as well.

### PR DESCRIPTION
**Pull request by sciwhiz12**
This PR fixes #9397 by removing the hardcoded `true` for the `hasPrecipitation` in the climate settings builder and using the stored property value. See my comment on the linked issue for details: https://github.com/MinecraftForge/MinecraftForge/issues/9397#issuecomment-1475607851.

### CODE REVIEW

File: src/main/java/net/minecraftforge/common/world/ClimateSettingsBuilder.java [hunk 1]
```diff
@@ -6,7 +6,6 @@
 package net.minecraftforge.common.world;
 
 import net.minecraft.world.level.biome.Biome.ClimateSettings;
-import net.minecraft.world.level.biome.Biome.Precipitation;
```
Comment (marchermans) [inline src/main/java/net/minecraftforge/common/world/ClimateSettingsBuilder.java:9]: @sciwhiz12 Why does this remove an import? Is this done on purpose or by accident?

**Review by marchermans — APPROVED** [review]
Okey tested it internally, it is fine.

File: src/main/java/net/minecraftforge/common/world/ClimateSettingsBuilder.java (hunk 1 above)
Comment (sciwhiz12) [reply src/main/java/net/minecraftforge/common/world/ClimateSettingsBuilder.java:9]: It is done on purpose, as it is an unused import due to `ClimateSettings` no longer storing a value of `Biome.Precipitation` (since it was replaced by a simple `boolean hasPrecipitation`). I decided that an unused import removal is acceptable to include in this small patch.

Comment (marchermans) [reply src/main/java/net/minecraftforge/common/world/ClimateSettingsBuilder.java:9]: Yeah that is fine. Already checked :D
