### PR TITLE
[1.21.4] Fix forced chunks never being ticked by the server

### LINKED ISSUE #10184: [1.21.3] forceTicks in addRegionTicket isn't working correctly
**Minecraft Version:** 1.21.3
**Forge Version:** tested on 53.0.19

**Steps to Reproduce:**
 1. Add a ticket with `ServerChunkCache.addRegionTicket(TicketType<T> p_140841_, ChunkPos p_140842_, int p_140843_, T p_140844_, boolean forceTicks)` with forceTicks set to true.
 2. Plant some wheat seeds in the forceloaded chunk.
 3. Fly far away and set random tick speed to 3000, then wait for 30 seconds.
 4. Set random tick speed back to 3.
 5. Return to the forceloaded chunk.
 6. The wheat has not grown.

**Description of issue:**
Forceload tickets with forceTicks set to true don't force random block ticks. I feel like `DistanceManager.shouldForceTicks` isn't even called anywhere for this purpose, but could be wrong here.

### PR DESCRIPTION
**Pull request by Jonathing**
In the update to 1.21.3, a patch was eaten that was responsible for adding forced chunk tickets to the iterator of ticking chunks. The functionality of collecting ticking chunks was moved elsewhere, so this PR compensates by patching the collection of chunks to include forced chunks.

- Fixes #10184 for 1.21.4.
- Backports will be made after this PR is approved.

### CODE REVIEW

**Comment by Jonathing** [comment]
Drafted until game tests are written and working, which requires #10309 and #10316 to be merged first.

File: patches/minecraft/net/minecraft/server/level/ChunkMap.java.patch [hunk 1]
```diff
@@ -33,3 +33,23 @@
...
++    // Copy of forEachSpawnCandidateChunk, but with forced chunks
++    void forEachForcedChunk(Consumer<ChunkHolder> p_364582_) {
++        LongIterator longiterator = this.distanceManager.forcedTickets.keySet().iterator();
++
++        while (longiterator.hasNext()) {
++            long i = longiterator.nextLong();
++            ChunkHolder chunkholder = this.visibleChunkMap.get(i);
++            if (chunkholder != null) {
++                p_364582_.accept(chunkholder);
+             }
```
Comment (LexManos) [inline patches/minecraft/net/minecraft/server/level/ChunkMap.java.patch]:
```java
    void forEachSpawnCandidateChunk(Consumer<ChunkHolder> p_364582_) {
        forEachChunk(this.distanceManager.getSpawnCandidateChunks(), this::anyPlayerCloseEnoughForSpawningInternal, p_364582_);
    }

    void forEachForcedChunk(Consumer<ChunkHolder> callback) {
        forEachChunk(this.distanceManager.forcedTickets.keySet().iterator(), pos -> true, callback);
    }

    private void forEachChunk(LongIterator longiterator, java.util.function.Predicate<ChunkPos> filter, Consumer<ChunkHolder> p_364582_) {
        while (longiterator.hasNext()) {
            long i = longiterator.nextLong();
            ChunkHolder chunkholder = this.visibleChunkMap.get(i);
            if (chunkholder != null && filter.test(chunkholder.getPos())) {
                p_364582_.accept(chunkholder);
            }
        }
    }
``` 
    Dunno if thats a better patch, makes it more clear what its doing

File: src/test/java/net/minecraftforge/debug/gameplay/level/ForcedChunkLoadingTest.java [hunk 2]
```diff
@@ -0,0 +1,42 @@
+package net.minecraftforge.debug.gameplay.level;
```
Comment (LexManos) [inline src/test/java/net/minecraftforge/debug/gameplay/level/ForcedChunkLoadingTest.java:6]: needs license header, and the mod id doesnt need the _test suffix
You could also pick a spot that you KNOW is outside the range by checking the chunkmap. Or offsetting the position from the current test position.

Also, need to add a check to make sure the chunk is loaded and in the ticking list.

**Comment by thexaero** [comment]
I'm fairly certain this solution can create duplicate chunks in the `p_368970_` list that will be ticked twice, if the chunks are both naturally ticked and force-ticked. Am I missing something?

File: patches/minecraft/net/minecraft/server/level/ChunkMap.java.patch (hunk 1 above)
Comment (Jonathing) [reply patches/minecraft/net/minecraft/server/level/ChunkMap.java.patch]: I was trying to be careful not to change semantics too much, but that's probably better. When I'm back home I'll probably make it do something like that.

**Comment by Jonathing** [comment]
Good catch, thanks. I'll probably need to collect them in some sort of sublist and then distinct them so that doesn't happen.

**Comment by thexaero** [comment]
Nice! `List.contains` could be a problem though when the list gets big. Would be much faster to just filter out all chunks contained in `forcedTickets` when collecting naturally ticked chunks, the same way you're checking `isNaturalSpawningAllowed`, since that would be a hash set check. Or you could replace the list with a HashSet altogether.

**Comment by Jonathing** [comment]
I considered replacing the list with a hash set but again I am trying to be wary of the patch surface becoming too big. If it comes down to it I can just make sister methods that accept Set and deprecate the original vanilla methods.

**Comment by Jonathing** [comment]
Ok, I solved this problem by using a middle-man linked hash set inside of `collectTickingChunks`. Since vanilla is using a list which preserves order I thought it would be better than just using a normal hash set. This also allowed me to cut down the contains patch in the callback.

File: patches/minecraft/net/minecraft/server/level/ServerChunkCache.java.patch [hunk 3]
```diff
@@ -11,6 +11,28 @@
...
                      this.storeInCache(i, chunkaccess1, ChunkStatus.FULL);
+@@ -368,9 +_,19 @@
+     }
+ 
+     private void collectTickingChunks(List<LevelChunk> p_368970_) {
+-        this.chunkMap.forEachSpawnCandidateChunk(p_358696_ -> {
++        // FORGE: Use a LinkedHashSet to preserve order
++        Set<LevelChunk> set = new java.util.LinkedHashSet<>();
++        this.chunkMap.forEachSpawnCandidateChunk(this.getChunkCollector(set, chunk -> this.level.isNaturalSpawningAllowed(chunk.getPos())));
++        this.chunkMap.forEachForcedChunk(this.getChunkCollector(set, chunk -> true));
```
Comment (LexManos) [inline patches/minecraft/net/minecraft/server/level/ServerChunkCache.java.patch:28]: Could just make the second predicate `chunk -> !p_368970_.contains(chunk)` Little costly, but forced chunks should be small enough to not be an issue. Well no more costly then a set and copying it over.

Comment (Jonathing) [reply patches/minecraft/net/minecraft/server/level/ServerChunkCache.java.patch:28]: It depends. I'm working under the assumption that forced chunks can have any number of chunks in them which is why I delegated to a set in the first place.

Comment (LexManos) [reply patches/minecraft/net/minecraft/server/level/ServerChunkCache.java.patch:28]: True, but the most common case will be that there are no forced chunks at all.
So the set and loop may be unneeded. Maybe have a test if forced chunks are empty and only use the slower path then?

Comment (Jonathing) [reply patches/minecraft/net/minecraft/server/level/ServerChunkCache.java.patch:28]: Good call.

**Comment by Jonathing** [comment]
oh no
