### PR TITLE
Make check tasks fail instead of silently fix errors

### LINKED ISSUE #9207: Check tasks silently correct errors instead of failing the build
Recently, we configured our TeamCity CI to execute the check tasks and the compatibility checker task for all Pull Requests, as part of reducing the workload of Triage with regards to hunting down missing license headers and accidentally missing binary-compatibility breaking changes.

Setting aside the problem with the compatibility checker task (which will be fixed by #9202), the checks tasks also have their own issue: they silently correct errors instead of failing the build while in CI.

Currently, the check tasks -- `checkPatches`, `checkATs`, `checkExcs`, etc.[^1] -- are coded and configured with the premise that it is run by a human in their developement environment. To that end, these check tasks automatically correct and fix errors, only reporting (and failing the build) those errors which it could not automatically correct. This has been the way the tasks worked for a long time.

However, because we now execute these tasks in our CI, they must be reprogrammed to fail when encountering errors, instead of silently correcting them and proceeding. We should alsoto add new fixing tasks which can be run by humans to correct errors in their development environment, similar to what the check tasks do now.

To that end, the work to be done consists of three parts:

 - Refactoring the code for the check tasks to allow for two 'modes': one where it reports all errors as a build failure (or not, depending on `VerificationTask#getIgnoreFailures` which the tasks will also now implement), and one where it does as much silent correction on errors and reporting those which it cannot fix.
 - Modifying the existing check tasks to use the first mode, where it reports errors as build failures.
 - Creating a new `fix*` task using the second mode for each corresponding check task, where it does correction (and reporting problems that cannot be automatically fixed).

[^1]: I specifically exclude `checkLicenses` from the licenser plugin, because it correctly fails the build when license header violations are present.

### PR DESCRIPTION
**Pull request by Matyrobbrt**
This PR makes the `check*` tasks actually fail when they encounter errors, instead of silently fixing them.  
The old behaviour of fixing the error is reimplemented in the `FIX` mode, which is used by the `checkAndFix*` tasks.

## Implementation Details
This PR adds a `CheckTask` which implements `VerificationTask`, and can run in 2 different `mode`s:
- `CheckMode.CHECK`: this mode will report all encountered errors to the console, even if they can be automatically fixed. Moreover, if `ignoreFailures` is set to `false` (as it is by default), the build will fail if issues are found;
- `CheckMode.FIX`: this mode will check for issues in the checked file, and attempt to automatically fix them. If it is not able to do so, a non-fixable error will be reported, failing the build if `ignoreFailures` is set to `false`.

Closes #9207

### CODE REVIEW

File: buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/checks/CheckSAS.groovy [hunk 1]
```diff
@@ -0,0 +1,111 @@
...
+import org.gradle.api.file.ConfigurableFileCollection
+import org.gradle.api.file.RegularFileProperty
+import org.gradle.api.tasks.InputFile
+import org.gradle.api.tasks.InputFiles
+
+@CompileStatic
+abstract class CheckSAS extends CheckTask {
+
+	@InputFile abstract RegularFileProperty getInheritance()
+	@InputFiles abstract ConfigurableFileCollection getSass()
```
Comment (sciwhiz12) [inline buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/checks/CheckSAS.groovy]: Formatting: 4 spaces, not tabs.

```suggestion
    @InputFile abstract RegularFileProperty getInheritance()
    @InputFiles abstract ConfigurableFileCollection getSass()
```

File: buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/checks/CheckSAS.groovy [hunk 2]
```diff
@@ -0,0 +1,111 @@
...
+                    boolean sided = clsSided
+
+                    /* TODO: MergeTool doesn't do fields
+                    if (json[cls]['fields'] != null) {
+						for (entry in json[cls]['fields']) {
+                            if (isSided(entry.value)) {
+                                sided = true
+                                toAdd.add('\t' + cls + ' ' + entry.key)
+                            }
+						}
```
Comment (sciwhiz12) [inline buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/checks/CheckSAS.groovy]: Formatting: 4 spaces, not tabs.

```suggestion
                        for (entry in json[cls]['fields']) {
                            if (isSided(entry.value)) {
                                sided = true
                                toAdd.add('\t' + cls + ' ' + entry.key)
                            }
                        }
```

File: buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/checks/CheckSAS.groovy [hunk 3]
```diff
@@ -0,0 +1,111 @@
...
+                return true
+        }
+        return false
+    }
+    
+	protected static findChildMethods(Map<String, InheritanceData> json, String cls, String desc)
+	{
+		return json.values().findAll{ it.methods != null && it.methods[desc] != null && it.methods[desc].override == cls && isSided(it.methods[desc]) }
+				.collect { it.name + ' ' + desc.replace(' ', '') } as TreeSet
+	}
```
Comment (sciwhiz12) [inline buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/checks/CheckSAS.groovy]: Formatting: 4 spaces, not tabs.
```suggestion
    protected static findChildMethods(Map<String, InheritanceData> json, String cls, String desc)
    {
        return json.values().findAll{ it.methods != null && it.methods[desc] != null && it.methods[desc].override == cls && isSided(it.methods[desc]) }
                .collect { it.name + ' ' + desc.replace(' ', '') } as TreeSet
    }
```

File: buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/checks/CheckPatches.groovy [hunk 4]
```diff
@@ -0,0 +1,177 @@
...
+        }
+    }
+
+    void verifyPatch(Path patch, Reporter reporter, boolean fix, String patchPath, boolean hasS2SArtifact) {
+        final hunk_start_pattern = Pattern.compile('^@@ -[0-9,]* \\+[0-9,_]* @@$')
+        final white_space_pattern = Pattern.compile('^[+\\-]\\s*$')
+        final import_pattern = Pattern.compile('^[+\\-]\\s*import.*')
+        final field_pattern = Pattern.compile('^[+\\-][\\s]*((public|protected|private)[\\s]*)?(static[\\s]*)?(final)?([^=;]*)(=.*)?;\\s*$')
+        final method_pattern = Pattern.compile('^[+\\-][\\s]*((public|protected|private)[\\s]*)?(static[\\s]*)?(final)?([^(]*)[(]([^)]*)?[)]\\s*[{]\\s*$')
+        final class_pattern = Pattern.compile('^[+\\-][\\s]*((public|protected|private)[\\s]*)?(static[\\s]*)?(final[\\s]*)?(class|interface)([^{]*)[{]\\s*$')
```
Comment (sciwhiz12) [inline buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/checks/CheckPatches.groovy]: It pains me that these `Pattern`s are recreated on each invocation of this method. Please move them to static constants.

File: buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/checks/CheckPatches.groovy [hunk 5]
```diff
@@ -0,0 +1,177 @@
...
+
+        final oldFixedErrors = reporter.fixed.size()
+
+        final accessMap = [private: 0, null: 1, protected:2, public:3]
```
Comment (sciwhiz12) [inline buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/checks/CheckPatches.groovy]: This should also be moved to a static constant.

File: buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/checks/CheckATs.groovy [hunk 6]
```diff
@@ -0,0 +1,304 @@
...
+                        itr.remove()
+                        reporter.report("Invalid group, class has no fields: $key")
+                    } else {
+                        jcls.fields.each { field, value ->
+                            final fkey = entry.cls + ' ' + field
+                            if (accessLevel(value.access) < accessStr(entry.modifier)) {
+                                if (lines.containsKey(fkey)) {
+                                    toRemove.add(fkey)
+                                } else if (!entry.existing.contains(fkey)) {
+                                    println('Added: ' + fkey)
```
Comment (sciwhiz12) [inline buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/checks/CheckATs.groovy]: Shouldn't this be reported, given that this means that the check task found a line which _should_ exist in the AT but actually doesn't? (Same with the other nearby `println('Added: ' + fKey)` and `println('Removed: ' + fKey)`.)

File: buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/checks/CheckATs.groovy [hunk 7]
```diff
@@ -0,0 +1,304 @@
...
+                                entry.children.add(key)
+                            } else if (lines.containsKey(key)) {
+                                toRemove.add(key)
+                                println('Removed: ' + key)
+                            }
+                        }
+                        entry.existing.findAll { it !in entry.children }.each { println('Removed: ' + it) }
+                    }
+                } else if ('<init>' == entry.desc) { //Make all public non-abstract subclasses
+                    inheritance.each { tcls, value ->
```
Comment (sciwhiz12) [inline buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/checks/CheckATs.groovy]: I wonder if this could be optimized by moving this outside of the AT entry checking loop, so it only needs to iterate over all the classes in the inheritance map once.

File: buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/checks/CheckATs.groovy [hunk 8]
```diff
@@ -0,0 +1,304 @@
...
+                        if (!value.methods || ((value.access & Opcodes.ACC_ABSTRACT) != 0)) return
+                        final parents = [] as Set
+                        String parent = tcls
+                        while (parent !== null && inheritance.containsKey(parent)) {
+                            parents.add(parent)
+                            def p = inheritance[parent]
+                            parent = p === null ? null : p.superName
+                        }
+                        if (parents.contains(entry.cls.replaceAll('\\.', '/'))) {
```
Comment (sciwhiz12) [inline buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/checks/CheckATs.groovy]: Do we really need to traverse all the parents of the target class _then_ check if the AT class (`entry.cls`) is a parent? Could we not do the check at each parent name, and short-circuit once we encounter the parent for the first time? This would also avoid allocating a `Set` each time.

File: buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/checks/CheckATs.groovy [hunk 9]
```diff
@@ -0,0 +1,304 @@
...
+                            }
+                        }
+                    }
+                    entry.existing.findAll { it !in entry.children }.each{ println('Removed: ' + it) }
+                }
+            }
+
+            // Process normal lines, remove invalid and remove narrowing
+            else {
+                def jcls = inheritance.get(entry.cls.replaceAll('\\.', '/'))
```
Comment (sciwhiz12) [inline buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/checks/CheckATs.groovy]: I've seen `entry.cls.replaceAll('\\.', '/')` enough times that I think it warrants being calculated once and put into a local variable. Perhaps, `.replaceAll('\\.', '/')` should also become a named function on its own (like, say, `toBinaryName`)?

**Review by sciwhiz12 — CHANGES_REQUESTED** [review]

**Comment by sciwhiz12** [comment]
Also, there seems to be some errors caught by the new check tasks in the check runs for your PR. :D

File: buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/checks/CheckATs.groovy [hunk 10]
```diff
@@ -163,6 +138,33 @@ abstract class CheckATs extends CheckTask {
...
+                                toRemove.add(child)
+                                reporter.report("Found invalid group entry: $child")
+                            }
+                        }
+                    }
+                }
+                parent = inheritance[parent]?.superName
+            }
+        }
+        constructorGroups.values().each { entry -> entry.existing.findAll { it !in entry.children }.each{ println('Removed: ' + it) } }
```
Comment (sciwhiz12) [inline buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/checks/CheckATs.groovy]: Shouldn't this also be processed by the `Reporter`?

File: build.gradle [hunk 11]
```diff
@@ -1173,6 +1174,20 @@ project(':forge') {
...
+    }
+    tasks.register('checkAllAndFix') {
+        dependsOn 'findFieldInstanceChecks', 'checkLicenses'
+        group = 'checks'
+    }
+    afterEvaluate {
+        tasks.withType(CheckTask).all {
+            tasks.getByName(it.mode.get() === CheckMode.FIX ? 'checkAllAndFix' : 'checkAll').dependsOn(it)
+        }
+    }
```
Comment (sciwhiz12) [inline build.gradle]: Why does this use `afterEvaluate` and the eager methods (`all`, `getByName`) instead of the equivalent lazy task configuration API methods (`configureEach`, `named(...).configure`)?

**Review by sciwhiz12 — APPROVED** [review]
