### PR TITLE
[1.21.4] Allow mipmap lowering to be disabled

### LINKED ISSUE #10155: Low-res texture packs are horribly broken.
**Minecraft Version:** 1.20.1

**Forge Version:** 47.3.7, 47.3.11

**Logs:** N/A

**Steps to Reproduce:**
 1. Open Minecraft
 2. Enable a resource pack with a resolution less than 16x
 3. Raise render distance to 32
 4. Look at blocks in the distance. 

**Description of issue:** Blocks in very far away chunks will appear to be the entirely wrong color (ex. sand can be purple instead of yellow) and water may or may not stop rendering at those distances. Confirmed to happen without any mods, and with the experimental rendering pipeline enabled or disabled, on a freshly installed instance of Forge with either of these resource packs: F8thful or Pollachius. 
image
image

### PR DESCRIPTION
**Pull request by Jonathing**
This PR allows mipmaps to be lowered in real-time, which Forge disables. This is done with a new flag in the Forge client config, and it is set to `false` by default.

- Fixes #10155.
- Follows up on #8622.

### CODE REVIEW

File: patches/minecraft/net/minecraft/client/renderer/texture/SpriteLoader.java.patch [hunk 1]
```diff
@@ -5,7 +5,7 @@
          int k1 = Mth.log2(j1);
          int l1;
 -        if (k1 < p_261919_) {
-+        if (false) { // Forge: Do not lower the mipmap level
++        if (net.minecraftforge.common.ForgeConfig.CLIENT.allowMipmapLowering() && k1 < p_261919_) { // Forge: Do not lower the mipmap level
```
Comment (PaintNinja) [inline patches/minecraft/net/minecraft/client/renderer/texture/SpriteLoader.java.patch]: Please put the int comparison before the untrusted final field read

**Review by PaintNinja — CHANGES_REQUESTED** [review]

**Review by LexManos — APPROVED** [review]
