### PR TITLE
Check source permission level before selector permission

### LINKED ISSUE #9137: [Forge Server] Functions/Commands and player selectors are not working as intended unless Op'd
**Minecraft Version:** 1.19.2

**Forge Version:** 43.1.47
- Issue has been present since 43.0.18 and all versions that followed

**Steps to Reproduce:**
 1. In a function write `say hi @s` and have an advancement run that function
 2. When opped the result will be "hi (player name) when not opped the result will be "hi @s"
- this also happened with command blocks when the bug started but seems to have been fixed since then, only functions are affected now from the looks of it

**Description of issue:**
In the latest versions of the Forge Server the connection between the person running the advancement isn't taken into account, so the @s selector doesn't know who to target, it seems as if it's handled as if the server ran it not the player, UNLESS the player is opped in which case it works as expected.

I did a quick test with a vanilla advancement and linked it to a function that simply does /say hello @s, when opped it comes back with "hello The8BitMonkey" but when I remove my op statue I get "hello @s" instead

The last version where everything worked as expected was 43.0.17 but as of 43.0.18 is no longer works without op statue, this could be due to this change noted in the change-log for Forge;

> - 43.0.18 Redirect checks for entity selector use to a permission (#8947)
>            This allows greater flexibility for configuring servers with
>            operator-like permissions to user groups through the permissions API and
>            their permissions handler of choice without needing to grant the
>            vanilla operator permission to any player.
>            The new permission is "forge:use_entity_selectors", which is granted by
>            default to players with permission level 2 (GAMEMASTERS) and above.
>            The hook falls back to checking the permission level if the source of
>            the command is not a ServerPlayer, such as for command blocks and
>            functions.

This clearly breaks vanilla behaviour and results in a lot of datapacks from working as intended when added to the game.

I've attached a video showing the bug in action: https://youtu.be/eJkrgG1bQSc
I've also a datapack to easily reproduce the bug yourself: https://www.dropbox.com/s/80dpejouiec01l1/forge_bug_test.zip?dl=1

### PR DESCRIPTION
**Pull request by sciwhiz12**
This PR fixes #9137 by moving the command source stack permission check to _before_ the Forge entity selector permission check.

In some situations, such as execution of a function by an advancement as part of its reward, a command source stack may have a backing source of a `ServerPlayer` which may lack the entity selector permission _and_ have an explicit permission level that should allow the use of entity selectors, through `CommandSourceStack#withPermission`.

This does means that an operator permission level of 2 will always override the Forge entity selector permission.

This is a major oversight on my part, as this was brought up previously[^1] during public discussions in the Discord by @LexManos, but I forgot to do that one change before my PR was merged[^2].

[^1]: "okay, ATing field and `||`ing the permission level check to the Forge permission check" ~ sciwhiz12#1286 [in `#github-discussions`](https://canary.discord.com/channels/313125603924639766/852298000042164244/1012260131733508136)
[^2]: "Shit `@sci, señor sleepy sus 🔰` I derpeed, you didn't add the || before I pulled..." ~ Lex#4688 [in `#github-discussions`](https://canary.discord.com/channels/313125603924639766/852298000042164244/1012443862305886228)

### CODE REVIEW

File: src/main/java/net/minecraftforge/common/ForgeHooks.java [hunk 1]
```diff
@@ -296,12 +296,12 @@ public static void onLivingSetAttackTarget(LivingEntity entity, LivingEntity tar
     {
         MinecraftForge.EVENT_BUS.post(new LivingSetAttackTargetEvent(entity, target, targetType));
     }
-    
+
```
Comment (Matyrobbrt) [inline src/main/java/net/minecraftforge/common/ForgeHooks.java]: Whitespace change

File: src/main/java/net/minecraftforge/common/ForgeHooks.java [hunk 2]
```diff
@@ -296,12 +296,12 @@ public static void onLivingSetAttackTarget(LivingEntity entity, LivingEntity tar
...
     public static LivingChangeTargetEvent onLivingChangeTarget(LivingEntity entity, LivingEntity originalTarget, ILivingTargetType targetType)
     {
         LivingChangeTargetEvent event = new LivingChangeTargetEvent(entity, originalTarget, targetType);
         MinecraftForge.EVENT_BUS.post(event);
-        
+
```
Comment (Matyrobbrt) [inline src/main/java/net/minecraftforge/common/ForgeHooks.java]: Whitespace change

**Review by Matyrobbrt — CHANGES_REQUESTED** [review]

File: src/main/java/net/minecraftforge/common/ForgeHooks.java (hunk 1 above)
Comment (sciwhiz12) [reply src/main/java/net/minecraftforge/common/ForgeHooks.java]: I hate unnecessary whitespace being added, and also having to re-add unnecessary whitespace for the sole purpose of keeping changes in a PR minimal.

**Review by Matyrobbrt — APPROVED** [review]

**Review by marchermans — APPROVED** [review]
