### PR TITLE
Fix render_type in block models not being used. Fixes #10294

### LINKED ISSUE #10294: [1.21.4] `render_type` in block models not being used
**Minecraft Version:** 1.21.4

**Forge Version:** 54.0.16

**Logs:** N/A

**Steps to Reproduce:**
 1. Clone and run the [test mod](https://github.com/Choonster-Minecraft-Mods/ForgeRenderTypeTestMod)
 2. Execute `/give @a forge_render_type_test:cutout_block`
 3. Place the block

**Description of issue:**

The block is rendered with the default `solid` render type rather than `cutout`, resulting in black sections around the sapling texture. This is despite the [block model](https://github.com/Choonster-Minecraft-Mods/ForgeRenderTypeTestMod/blob/82ac3668592eb4c0a87689ad00d859a2ddd3fceb/src/main/resources/assets/forge_render_type_test/models/block/cutout_block.json) using `"render_type": "minecraft:cutout"`.

On the left is the Vanilla Acacia Sapling, on the right is the Cutout Test block.

From what I can see, the `render_type` property is being read and stored in `BlockGeometryBakingContext` by `ForgeHooksClient.deserializeBlockModel`, but `IGeometryBakingContext#getRenderTypeHint` is only called by `BlockGeometryBakingContext` and `StandaloneGeometryBakingContext.Builder`.

### PR DESCRIPTION
**Pull request by LexManos**
This is a dirty hack to get render_type working again. We need to pass this extra context data to the parent bake function, So I attach it to ModelBaker. Anyone got a better idea?

### CODE REVIEW

**Comment by Jonathing** [comment]
insane

File: src/main/java/net/minecraftforge/client/model/SimpleModelState.java [hunk 1]
```diff
@@ -11,31 +11,26 @@
 /**
  * Simple implementation of {@link ModelState}.
  */
-public final class SimpleModelState implements ModelState
-{
+public final class SimpleModelState implements ModelState {
```
Comment (PaintNinja) [inline src/main/java/net/minecraftforge/client/model/SimpleModelState.java]: Record candidate
