### PR TITLE
[1.19.x] Fixed the PlayerInteractEvent.EntityInteractSpecific not respecting cancelled status on server side

### LINKED ISSUE #9040: [1.19.2] Cancelling `EntityInteractSpecific` event does not cancel interaction server-side
**Minecraft Version:** 1.19.2

**Forge Version:** 43.1.25

**Steps to Reproduce:**
 1. Cancel `PlayerInteractEvent.EntityInteractSpecific` by providing a cancellation result and setting `canceled` to `true`
 2. Vanilla processing for the event will still take place, and code provided in the event will be run afterwards

**Example:**
Example for cancelling interactions with armor stand, theoretically this should prevent any armor from being added or taken. In reality nothing is changed.
```java
    @SubscribeEvent
    public static void onEntityInteractSpecific(final PlayerInteractEvent.EntityInteractSpecific evt) {
        if (evt.getTarget() instanceof ArmorStand) {
            evt.setCancellationResult(InteractionResult.sidedSuccess(evt.getLevel().isClientSide));
            evt.setCanceled(true);
        }
    }
```
**Description of issue:**
The problem is the Forge event is fired too late in `ServerGamePacketListenerImpl`, only after the vanilla interaction has been processed. Simply moving the event invocation to before vanilla's code is not enough though, currently the event completely ignores the provided cancellation result.

Therefore I suggest when the event is cancelled setting the result to the local `InteractionResult` variable, otherwise let vanilla run and set the variable itself. The local variable is later used by vanilla for triggering a statistics tracker as well as calling the arm swing server side for other players to see.

### PR DESCRIPTION
**Pull request by MagnusHJensen**
This PR closes: #9040 

As mentioned by [9040#issuecomment-1248310872](https://github.com/MinecraftForge/MinecraftForge/issues/9040#issuecomment-1248310872) the event being cancelled was never respected, due to this line
```java
InteractionResult interactionresult = p_143680_.run(ServerGamePacketListenerImpl.this.player, entity, p_143679_);
```
being executed before the event, essentially running the interact action on the server.

The event check was moved out to what calls the bigger chunk. (Also the same place Fabric has placed it) [Fabric/ServerPlayNetworkHandlerMixin.java#L48](https://github.com/FabricMC/fabric/blob/bd290a2e1935096397e81d608e61c26328dd40db/fabric-events-interaction-v0/src/main/java/net/fabricmc/fabric/mixin/event/interaction/ServerPlayNetworkHandlerMixin.java#L48)

Which also contains the proper local hit vector, which was also incorrect. (Also spotted by @Fuzss).

This small test code, can show it working:
```java
@SubscribeEvent
public static void onEntityInteractSpecific(PlayerInteractEvent.EntityInteractSpecific event)
{
  if (event.getTarget() instanceof ArmorStand) {
    System.out.println(event.getLocalPos());
    event.setCancellationResult(InteractionResult.sidedSuccess(event.getLevel().isClientSide()));
    event.setCanceled(true);
  }
}
```

_There is also the issue #8143, but I deem that as 1.18, and will provide a backport for 1.18, which would close that issue. (Unless they are seen as the same issue)_

### CODE REVIEW

**Comment by Fuzss** [comment]
Hey there, thanks for looking into this.

This is not the fix I had in mind though, as it contains yet another issue: The cancellation result of the event (from `PlayerInteractEvent::getCancellationResult`) is ignored, it is only checked if it is present at all (via the `null` check).

The problem with that is, when `InteractionResult#CONSUME` or `InteractionResult#SUCCESS` are returned, the interact with entity statistic is not updated, and the arm swing animation does not play.

In my issue report linked above I suggested moving the event invocation to the head of the lambda, so just one line further down. There, if `PlayerInteractEvent::getCancellationResult` is not `null` that value can be returned to be further processed by vanilla as I described above, otherwise the vanilla behavior from that lambda can run.

I've implemented a custom event in one of my mods with the same behavior as a temporary solution until this is fixed in the location I've described here, please take a look if my description is unclear.
https://github.com/Fuzss/armorstatues/blob/1.19/Forge/src/main/java/fuzs/armorstatues/mixin/ServerGamePacketListenerImplMixin.java

**Comment by MagnusHJensen** [comment]
Hi, thanks for clarifying.

I do see what you mean.
I moved the event call inside the lambda, and if the event is canceled (it returns a value), return that so if set as success/consume it would still increment the stats, and swing the arm.

**Comment by Fuzss** [comment]
Awesome, thank you!

File: patches/minecraft/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch [hunk 1]
```diff
@@ -87,11 +87,22 @@
...
+-                  this.m_143678_(p_143682_, (p_143686_, p_143687_, p_143688_) -> {
+-                     return p_143687_.m_7111_(p_143686_, p_143683_, p_143688_);
++
++                   this.m_143678_(p_143682_, (p_143686_, p_143687_, p_143688_) -> {
++                    InteractionResult onInteractEntityAtResult = net.minecraftforge.common.ForgeHooks.onInteractEntityAt(f_9743_, entity, p_143683_, p_143682_);
++                    if (onInteractEntityAtResult != null) {
++                     return onInteractEntityAtResult;
++                    }
++                    return p_143687_.m_7111_(p_143686_, p_143683_, p_143688_);
+                   });
```
Comment (ChampionAsh5357) [inline patches/minecraft/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch]: Incorrect indentation and redundant patches.

**Review by ChampionAsh5357 — CHANGES_REQUESTED** [review]
~~So, why are we moving this down to a different method? This would mean that there would be even more bugs since now it would handle when the client sends the packet over. This is not a valid solution to the issue.~~

~~There are two ways you could solve this: fix the logic in `#performInteraction` such that it checks whether the interaction result is present from the event, and then run the logic if it isn't; or stop the packet from being sent to the server in the first place. The latter probably isn't the best solution since some people still want to have the syncing on the server, hence why the event is called after the packet is sent.~~

Ignore me, misunderstood the issue. Comments are still valid.

**Comment by Fuzss** [comment]
> So, why are we moving this down to a different method?

The current implementation runs too late, only after the interaction has already run. This makes it impossible to cancel. The event must be invoked before the interaction happens, just where this patch moves it. And the event requires the hit vector, which is only available in `#onInteraction(InteractionHand, Vec3)`, so keeping the patch in `#performInteraction` is not an option.

Also `#performInteraction` is called from another method as well: `#onInteraction(InteractionHand)`. That type of interaction is handled elsewhere though (by `PlayerInteractEvent.EntityInteract`) and doesn't have the hit vector, which `PlayerInteractEvent.EntityInteractSpecific` requires.

> This would mean that there would be even more bugs

What bugs do you mean exactly?

> now it would handle when the client sends the packet over

This PR doesn't change that, it's been like that before.

> fix the logic in `#performInteraction` such that it checks whether the interaction result is present from the event, and then run the logic if it isn't

That's what this patch does, it's simply placed in a different method, but it runs inside `#performInteraction`.

**Comment by Fuzss** [comment]
This PR simply fixes `PlayerInteractEvent.EntityInteractSpecific` to once again only run when it's supposed to, and to work in the way it's javadoc describes it's function.

If you want to redesign the way `PlayerInteractEvent.EntityInteract` and `PlayerInteractEvent.EntityInteractSpecific` work (for e.g. cancelling the interact packet being sent to the server in the first place) that should probably go into a separate PR.

**Comment by ChampionAsh5357** [comment]
> The current implementation runs too late, only after the interaction has already run. This makes it impossible to cancel. The event must be invoked before the interaction happens, just where this patch moves it. And the event requires the hit vector, which is only available in #onInteraction(InteractionHand, Vec3), so keeping the patch in #performInteraction is not an option.
> Also #performInteraction is called from another method as well: #onInteraction(InteractionHand). That type of interaction is handled elsewhere though (by PlayerInteractEvent.EntityInteract) and doesn't have the hit vector, which PlayerInteractEvent.EntityInteractSpecific requires.

Ah, that was my misunderstanding, apologies. I simply read the what the PR described as it just provided a solution without any further explanation as to why it was correct.

> If you want to redesign the way PlayerInteractEvent.EntityInteract and PlayerInteractEvent.EntityInteractSpecific work (for e.g. cancelling the interact packet being sent to the server in the first place) that should probably go into a separate PR.

That was not my intention. I was under the impression that it needed to be called there and such also provided some alternatives.

However, the indentations and patch redundancies need to be fixed still.

File: patches/minecraft/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch (hunk 1 above)
Comment (MagnusHJensen) [reply patches/minecraft/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch]: Indentation fixed, not sure what you mean about redundant patches. I removed the empty line.

File: patches/minecraft/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch [hunk 2]
```diff
@@ -87,11 +87,21 @@
...
-                      CriteriaTriggers.f_10565_.m_61494_(ServerGamePacketListenerImpl.this.f_9743_, itemstack, entity);
-                      if (interactionresult.m_19080_()) {
-@@ -1558,6 +_,8 @@
+@@ -1551,13 +_,19 @@
+                }
+ 
+                public void m_142143_(InteractionHand p_143682_, Vec3 p_143683_) {
+-                  this.m_143678_(p_143682_, (p_143686_, p_143687_, p_143688_) -> {
+-                     return p_143687_.m_7111_(p_143686_, p_143683_, p_143688_);
++                   this.m_143678_(p_143682_, (p_143686_, p_143687_, p_143688_) -> {
```
Comment (ChampionAsh5357) [inline patches/minecraft/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch]: Indentation still not fixed, you can tell because you are still removing lines.

File: patches/minecraft/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch [hunk 3]
```diff
@@ -87,11 +87,21 @@
...
++                       InteractionResult onInteractEntityAtResult = net.minecraftforge.common.ForgeHooks.onInteractEntityAt(f_9743_, entity, p_143683_, p_143682_);
++                       if (onInteractEntityAtResult != null) {
++                           return onInteractEntityAtResult;
++                       }
```
Comment (ChampionAsh5357) [inline patches/minecraft/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch]: This can be one line.

**Review by ChampionAsh5357 — CHANGES_REQUESTED** [review]

File: patches/minecraft/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch (hunk 2 above)
Comment (MagnusHJensen) [reply patches/minecraft/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch]: I see what you mean, the file (maybe the entire project) uses 3 space indentation (not sure why), anyhow that should be fixed.

File: patches/minecraft/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch (hunk 3 above)
Comment (MagnusHJensen) [reply patches/minecraft/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch]: Condensed to one line ternary operator.

File: patches/minecraft/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch [hunk 4]
```diff
@@ -87,11 +87,16 @@
...
-                      CriteriaTriggers.f_10565_.m_61494_(ServerGamePacketListenerImpl.this.f_9743_, itemstack, entity);
-                      if (interactionresult.m_19080_()) {
-@@ -1558,6 +_,8 @@
+@@ -1552,12 +_,15 @@
+ 
+                public void m_142143_(InteractionHand p_143682_, Vec3 p_143683_) {
+                   this.m_143678_(p_143682_, (p_143686_, p_143687_, p_143688_) -> {
+-                     return p_143687_.m_7111_(p_143686_, p_143683_, p_143688_);
++                     InteractionResult onInteractEntityAtResult = net.minecraftforge.common.ForgeHooks.onInteractEntityAt(f_9743_, entity, p_143683_, p_143682_);
++                     return onInteractEntityAtResult != null ? onInteractEntityAtResult : p_143686_.m_7111_(p_143686_, p_143683_, p_143688_);
```
Comment (ChampionAsh5357) [inline patches/minecraft/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch]: Again...the if statement can be condensed down to one line. This makes three line changes (2 additions 1 removal) while the other only causes two (2 additions).

Comment (MagnusHJensen) [reply patches/minecraft/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch]: I see what you mean now.
I don't understand why I was so dense as to seeing that change.

**Review by ChampionAsh5357 — APPROVED** [review]
