### PR TITLE
Fix issues with client only commands

### LINKED ISSUE #8438: Forge mod causing LuckPerm commands to not register in client
**Minecraft Version:** {Minecraft version}
Minecraft 1.18.1 Client with Forge (Optifine & Controllable Mods)

**Forge Version:** {Forge version. *Version number, not latest/rb*}
Forge Mod 39.0.46 - 39.0.63 (Issue Versions)
Forge Mod 39.0.40 - 39.0.45 (Working Versions)

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}
https://paste.ee/p/nFncj - Debug Log
https://paste.ee/p/nknCg - Latest Log (Edited for redaction)

**Steps to Reproduce:**
 1. Run Minecraft 1.18.1 Server with LuckPerms Plugin (v5.3.98)
 2. Install Forge Mod version between 39.0.46 - 39.0.63 on client running forge of versions above
 3. Run any LuckPerms server side issued command to verify issue on client running forge of versions above

**Description of issue:**

When running seemingly any version of Forge 39.0.46 through 39.0.63 (latest as of submission), this causes the client to not register any Luck Permissions plugin command on server as if command is not being entered at all. There is no log of event on client or server side, it just purely acts like the command isn't being entered and nothing happens. _This issue **DOES NOT** happen as tested with Forge Versions 39.0.40 or 39.0.45 and works as expected._

### LINKED ISSUE #8456: Brigadier throws exception when commands are not exist
**Minecraft Version:** 1.18.1

**Forge Version:** 39.0.66

**Logs:** https://gist.github.com/Jenya705/7dbeef72bb4c2747047ad8c3dcb5d7cd

**Steps to Reproduce:**
 1. Join the server which is not registering the commands
 2. type the `/some command`

**Description of issue:**
When you are typing the command on the server without registered comnand, then it type in the chat `An unexpected error occurred trying to execute that command`. Vanilla client doesn't type that message.

### PR DESCRIPTION
**Pull request by diesieben07**
Fixes #8438. Fixes #8456.

1. Handles commands which are unknown on the client more gracefully, by delegating to the server. This fixes #8438. 
    Verified with local PaperMC + LuckPerms installation.
2. Improves handling of badly formed (infinite recursion) or absent command packets from some server implementations. This fixes #8456.
    Verified with local Limbo installation (with commands and without, through permissions).

### CODE REVIEW

File: src/main/java/net/minecraftforge/client/ClientCommandHandler.java [hunk 1]
```diff
@@ -278,26 +302,34 @@ public static boolean sendMessage(String sendMessage)
...
-                        .withStyle((style) -> style
-                                .withClickEvent(new ClickEvent(ClickEvent.Action.SUGGEST_COMMAND, reader.getString())));
-                if (position > 10)
-                {
-                    details.append("...");
-                }
-                details.append(syntax.getInput().substring(Math.max(0, position - 10), position));
-                if (position < syntax.getInput().length())
+                // in case of unknown command, let the server try and handle it
+                Minecraft.getInstance().player.chat(sendMessage);
```
Comment (sciwhiz12) [inline src/main/java/net/minecraftforge/client/ClientCommandHandler.java]: Is there a specific reason why this calls `LocalPlayer#chat` directly instead of returning `false` from this method and letting vanilla call it instead?
