### PR TITLE
Fix random FML handshake crash, fixes #4285 and #3974

### LINKED ISSUE #4285: [1.12] Another strange Netty crash
Similar to #4219, but not quite the same.

That issue (fixed by #4220) led to this exception:
```
java.lang.ClassCastException: Cannot cast net.minecraft.client.network.NetHandlerLoginClient to net.minecraft.client.network.NetHandlerPlayClient
```

This issue, as seen here (https://github.com/MinecraftForge/MinecraftForge/issues/4219#issuecomment-317061214), has a different exception:
```
java.lang.ClassCastException: net.minecraftforge.fml.common.network.handshake.FMLHandshakeMessage$ServerHello cannot be cast to net.minecraftforge.fml.common.network.handshake.FMLHandshakeMessage$ModList
```

I've just experienced this issue myself with a Forge dev environment, no mods installed (branched from build 2444).

Here's a copy of the [fml-junk-earlystartup.log](https://gist.github.com/bs2609/ed95784e887a777c1f484142fad63cb1) file (the error is [here](https://gist.github.com/bs2609/ed95784e887a777c1f484142fad63cb1#file-fml-junk-earlystartup-log-L3936-L4041))

### PR DESCRIPTION
**Pull request by Niko-sk2x**
~~This fixes a race condition introduced in 3fee319. I fixed it by running the code previously in `handlerAdded` on the netty thread (using the same way netty does it for running `handlerAdded`).~~

~~I described a few other ways it could be fixed in #4285, but I think this is the best one, without changing a lot of code.~~

There are 2 parts to make sure it's fixed:
 * Make sure that when processing handshake messages, new state is set before sending any packets.

I think setting autoRead to false should be enough to fix it, but I don't understand enough of netty to make that work (and it may be a bug in netty)

The issue in #4285 is that the `START` handshake state handler is called from server thread, which makes it possible to server to receive reply before the method returns.

The issue in #3974 is that the client `START` handler calls `clientListenForServerHandshake` which may read messages from server before setting new state.

Both should be fixed just my making sure the new state is set before doing anything important.

### CODE REVIEW

**Comment by Niko-sk2x** [comment]
Don't merge yet, I found that I'm getting these serverside exceptions when connecting to dedicated server:
```
java.util.NoSuchElementException: packet_handler
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1080) ~[DefaultChannelPipeline.class:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:251) ~[DefaultChannelPipeline.class:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:240) ~[DefaultChannelPipeline.class:4.1.9.Final]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.insertIntoChannel(NetworkDispatcher.java:175) ~[NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.serverToClientHandshake(NetworkDispatcher.java:155) ~[NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.fmlServerHandshake(FMLNetworkHandler.java:72) ~[FMLNetworkHandler.class:?]
	at net.minecraft.server.network.NetHandlerLoginServer.tryAcceptPlayer(NetHandlerLoginServer.java:135) ~[NetHandlerLoginServer.class:?]
	at net.minecraft.server.network.NetHandlerLoginServer.update(NetHandlerLoginServer.java:63) ~[NetHandlerLoginServer.class:?]
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:285) ~[NetworkManager.class:?]
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:179) [NetworkSystem.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:788) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:396) [DedicatedServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

io.netty.channel.ChannelPipelineException: net.minecraftforge.fml.common.network.handshake.NetworkDispatcher is not a @Sharable handler, so can't be added or removed multiple times.
	at io.netty.channel.DefaultChannelPipeline.checkMultiplicity(DefaultChannelPipeline.java:588) ~[DefaultChannelPipeline.class:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:249) ~[DefaultChannelPipeline.class:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:240) ~[DefaultChannelPipeline.class:4.1.9.Final]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.insertIntoChannel(NetworkDispatcher.java:176) ~[NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.serverToClientHandshake(NetworkDispatcher.java:155) ~[NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.fmlServerHandshake(FMLNetworkHandler.java:72) ~[FMLNetworkHandler.class:?]
	at net.minecraft.server.network.NetHandlerLoginServer.tryAcceptPlayer(NetHandlerLoginServer.java:135) ~[NetHandlerLoginServer.class:?]
	at net.minecraft.server.network.NetHandlerLoginServer.update(NetHandlerLoginServer.java:63) ~[NetHandlerLoginServer.class:?]
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:285) ~[NetworkManager.class:?]
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:179) [NetworkSystem.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:788) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:396) [DedicatedServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

I'm still trying to figure out what causes it.

File: src/main/java/net/minecraftforge/fml/common/network/handshake/NetworkDispatcher.java [hunk 1]
```diff
@@ -174,16 +173,21 @@ private void insertIntoChannel()
         this.manager.channel().config().setAutoRead(false);
         // Insert ourselves into the pipeline
         this.manager.channel().pipeline().addBefore("packet_handler", "fml:packet_handler", this);
-        if (this.state != null) {
-            FMLLog.log.info("Opening channel which already seems to have a state set. This is a vanilla connection. Handshake handler will stop now");
+        ChannelPipeline cp = this.manager.channel().pipeline().addBefore("packet_handler", "fml:packet_handler", this);
```
Comment (covers1624) [inline src/main/java/net/minecraftforge/fml/common/network/handshake/NetworkDispatcher.java]: This is called twice, could that be your issue?

Comment (Niko-sk2x) [reply src/main/java/net/minecraftforge/fml/common/network/handshake/NetworkDispatcher.java]: Uh... yes that could very well be it. I have no idea how I didn't see it.

**Comment by Niko-sk2x** [comment]
That was what @covers1624 mentioned, it can be merged now.

**Comment by Niko-sk2x** [comment]
This PR will fix one race condition, but it will still leave issue #3974, which may require reverting to the `handlerAdded` hack.

**Comment by Niko-sk2x** [comment]
This should fix both issues now. Can someone else test it? (it worked find with all of my tests). Also to be sure I didn't break anything I need to test compatibility with vanilla server, older versions of forge server, new forge server with vanilla client, and new forge server with old client.

**Comment by Kris1432** [comment]
@Barteks2x does this link to #4290 at all?

**Comment by Niko-sk2x** [comment]
The crash in the initial description - yes, probably. The registry issue - I really doubt it.

**Comment by Niko-sk2x** [comment]
And I just discovered that it didn't actually fix anything, just moved the race somewhere else... so back to the beginning.

**Comment by Niko-sk2x** [comment]
Should be really fixed this time.

**Comment by redfast00** [comment]
Can you please merge this? I am unable to play on my singleplayer worlds.

**Comment by Niko-sk2x** [comment]
I wanted to write instructions to workaround it with jdb, but after almost an hour of trying to make it work without an IDE I gave up. Modders can workaround it in IDE by setting thread-only breakpoints on the first lines of `FMLHandshakeServerState.START.accept` and `FMLHandshakeClientState.HELLO.accept` and resuming almost immediately from those breakpoints.

**Comment by mezz** [comment]
@cpw  can you look this over?
