### PR TITLE
Fix #8298 (MobBucketItem) and add test mod

### LINKED ISSUE #8298: Javascript coremod for MobBucketItem commented out
**Minecraft Version:** 1.18.1

**Forge Version:** 39.0.0

**Description of issue:** A small regression. In the 1.17 update the coremod that makes the supplier-ified MobBucketItem constructor useful was commented out. It is linked below. As a result trying to construct a custom bucket using the class is useless.

https://github.com/MinecraftForge/MinecraftForge/blob/456a48b12a61ae62bc86a36fe824245781cfab19/src/main/resources/coremods/field_to_method.js#L57-L65

### PR DESCRIPTION
**Pull request by eerussianguy**
This removes the broken coremod for MobBucketItem by just removing the old fields and redirecting everything to the supplier-ified constructor

### CODE REVIEW

File: src/test/java/net/minecraftforge/debug/item/CustomMobBucketTest.java [hunk 1]
```diff
@@ -0,0 +1,34 @@
+package net.minecraftforge.debug.item;
```
Comment (sciwhiz12) [inline src/test/java/net/minecraftforge/debug/item/CustomMobBucketTest.java:20]: Missing license header, please run the `updateLicenses`/`licenseFormat` task.

File: src/test/java/net/minecraftforge/debug/item/CustomMobBucketTest.java [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+import net.minecraftforge.registries.ForgeRegistries;
+import net.minecraftforge.registries.RegistryObject;
+
+@Mod(CustomMobBucketTest.MODID)
+public class CustomMobBucketTest
+{
+    public static final String MODID = "custom_mob_bucket_test";
+    public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, MODID);
+
+    public static final boolean ENABLE = true;
```
Comment (sciwhiz12) [inline src/test/java/net/minecraftforge/debug/item/CustomMobBucketTest.java]: Nitpick: the conventional name for this field is `ENABLED`.

File: src/test/java/net/minecraftforge/debug/item/CustomMobBucketTest.java [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+
+    public static final RegistryObject<Item> COW_BUCKET = ITEMS.register("cow_bucket", () -> new MobBucketItem(() -> EntityType.COW, () -> Fluids.WATER, () -> SoundEvents.BUCKET_EMPTY_FISH, (new Item.Properties()).stacksTo(1).tab(CreativeModeTab.TAB_MISC)));
```
Comment (sciwhiz12) [inline src/test/java/net/minecraftforge/debug/item/CustomMobBucketTest.java]: Just for readability purposes, could you split this into 2+ lines?

**Review by sciwhiz12 — CHANGES_REQUESTED** [review]
Testing with the included test mod's mob bucket item (the cow bucket) and the linked issue's code (the pig bucket) shows both work correctly with this PR applied.

Aside from the review comments, please confirm who created the `cow_bucket.png` texture and what the license for the texture is (and if the copyright author grants Forge a license to use, modify, redistribute, etc. the texture under the LGPLv2.1 license as set out in the [CLA](https://github.com/MinecraftForge/MinecraftForge/blob/1.18.x/docs/CONTRIBUTING.md#contributor-license-agreement)).

**Comment by eerussianguy** [comment]
I made that texture, I grant forge full rights to it as covered in the CLA.

**Review by sciwhiz12 — CHANGES_REQUESTED** [review]
After some discussion of this PR in the `#github-discussions` channel, it's decided that the uses of the `type` and `emptySound` fields within the class should be manually patched to redirect to the methods instead of using the transformer (which should now be deleted), along with some other changes.
- The now-`@Deprecated` constructor for `MobBucketItem` should redirect to the supplier-using constructor instead.
- The original non-supplier fields should be deleted, so if this class were to change in the future (for example, other uses of the fields are added), this class will fail to compile during the update and patch cycle as to draw attention to it (rather than silently compiling but having broken logic).

File: patches/minecraft/net/minecraft/world/item/MobBucketItem.java.patch [hunk 4]
```diff
@@ -1,43 +1,67 @@
...
-+   protected EntityType<?> getFishType() {
-+      return fishTypeSupplier.get();
++   protected EntityType<?> getFishType()
++   {
++      return entityTypeSupplier.get();
 +   }
 +
-+   protected SoundEvent getEmptySound() {
++   protected SoundEvent getEmptySound()
++   {
```
Comment (sciwhiz12) [inline patches/minecraft/net/minecraft/world/item/MobBucketItem.java.patch]: Because these are Minecraft classes, the code style to be followed is the same as the rest of the class (i.e. the formatting outputted by Fernflower): brackets on the same line.

File: patches/minecraft/net/minecraft/world/item/MobBucketItem.java.patch [hunk 5]
```diff
@@ -1,43 +1,67 @@
...
+-      if (this.f_151134_ == EntityType.f_20489_) {
++      if (getFishType() == EntityType.f_20489_) {
+          CompoundTag compoundtag = p_151155_.m_41783_();
+          if (compoundtag != null && compoundtag.m_128425_("BucketVariantTag", 3)) {
+             int i = compoundtag.m_128451_("BucketVariantTag");
+@@ -80,6 +_,16 @@
              p_151157_.add(mutablecomponent);
           }
        }
 -
```
Comment (sciwhiz12) [inline patches/minecraft/net/minecraft/world/item/MobBucketItem.java.patch]: Since you're in this patch anyway, could you introduce a blank link here so this line removal disappears?

**Review by sciwhiz12 — CHANGES_REQUESTED** [review]
Looks fine to me, just two minor quibbles remaining and then this is good to go!

**Review by sciwhiz12 — APPROVED** [review]
