### PR TITLE
[1.19.x] Remove Attack Range and Reach Distance and add Block Reach and Entity Reach

### LINKED ISSUE #9309: Forge 40.1.22 1.18.2+ has extended player reach
**Minecraft Version:** 1.19.3

**Forge Version:** 44.1.5

**Logs:** N/A

**Steps to Reproduce:**
1. Install any version of Forge 40.1.22 1.18.2+.
2. **Two easy options**: Right click an armourstand that has items on it from 4-5 blocks. This will work and give you the item. **OR:** Spawn a villager and right click it. This is easier to see in my opinion.
3. You may also test left click reach, but this doesn't seem to be affected as badly. It is easier to test right-click reach visually.

**Description of issue:**
Any version of Forge `40.1.22 1.18.2`+ has inbuilt reach hacks up to almost 5 blocks for right-click, around 3.3 for left-click. This is caused by the PR #8478.

I have tested this both on servers and singleplayer worlds. This is extremely bad as it flags anticheats (obviously).

I am aware of #9013 which potentially fixes this problem, however I believe 1.18.2 is still supported and that is only for 1.19, and the PR has been open for a long time now for such a big problem. This issue also raises awareness of the problem and tracks it, it took me a while to understand what was going on and that I wasn't insane.

It would be nice to see this problem solved on both 1.18 and 1.19 and as quickly as possible.

Edit: Video proving left-click reach is affected: https://youtu.be/GQcVjAxb1uE

### PR DESCRIPTION
**Pull request by Shadows-of-Fire**
## Summary
* The motivation for this PR is to fix #9309, which requires that entity interactions not be tracked by the same attribute are block interactions to keep vanilla parity.
* The attributes `reach_distance` and `attack_range` were removed, instead being replaced by `block_reach` and `entity_reach` respectively.
* The fixes from PRs #9013 and #9015 are rolled into this PR. If merged, they can be closed.

## Background
Prior to #8478, there was only one reach attribute, `reach_distance`, which controlled the maximum distance that a player could "reach" blocks, for left or right clicking.  There were no means to increase entity reach.
After #8478, `attack_range` was added, which controlled the maximum distance that a player could attack (left click) an entity. Entity interaction (right click) distance was coupled to `reach_distance`, and certain checks were reimplemented by forge to handle this change instead of relying on the method vanilla used.

As noted in #9013 and #9015, there were issues with that implementation, specifically regarding client checks and server validation on large-sized entities.
Additionally, as noted in #9309 and #8478, the coupling of `reach_distance` to the entity interaction range led to an increase in the default range (from 3.0 on vanilla to 4.5 on forge)
* The interaction range being different is technically a bug, as described in [MC-172289](https://bugs.mojang.com/browse/MC-172289) and [MC-92484](https://bugs.mojang.com/browse/MC-92484).
* However, parity with vanilla is desirable until vanilla fixes the issue, as some parties consider this an exploit.

## Implementation
The new attributes, `block_reach` and `entity_reach` control the maximum distance for left and right clicks to blocks and entities, respectively. Both attributes will be aliased to the previous names, with `reach_distance` aliased to `block_reach` and `attack_range` aliased to `entity_reach`.
* Note this aliasing does not introduce 1:1 feature parity.  Features that relied on `reach_distance` to increase the distance that a player may right click an entity _will no longer work_.

As compared to #8478's implementation, the checks for entity reach are now more centralized.  The entity checks are mainly performed in `GameRenderer#pick()`, where the entity is raytraced.  This is possible because all entity interactions have the same distance cap, so entity interactions being possible is a binary state.

Code references to reach and range have been replaced with the new attributes, including method renames.  Old names were deprecated and bounce to the new names as appropriate.

Finally, all of the range checks on `IForgePlayer` have been replaced with overloads of `canReach`.

### CODE REVIEW

File: src/main/java/net/minecraftforge/common/ForgeMod.java [hunk 1]
```diff
@@ -138,30 +138,43 @@
...
 
     /**
-     * Attack Range represents the distance at which a player may attack an entity.  The default is 3 blocks.  Players in creative mode have an additional 3 blocks of attack reach.
-     * @see IForgePlayer#getAttackRange()
-     * @see IForgePlayer#canHit(Entity, double)
+     * TODO: Remove
+     * @deprecated - use {@link #BLOCK_REACH}
      */
-    public static final RegistryObject<Attribute> ATTACK_RANGE = ATTRIBUTES.register("attack_range", () -> new RangedAttribute("generic.attack_range", 3.0D, 0.0D, 1024.0D).setSyncable(true));
+    public static final RegistryObject<Attribute> REACH_DISTANCE = BLOCK_REACH;
```
Comment (KnightMiner) [inline src/main/java/net/minecraftforge/common/ForgeMod.java:157]: Shouldn't this be annotated `@Deprecated` instead of just Javadoc deprecated? My compiler always yells at me if I annotate something only through the javadoc.

Comment (Shadows-of-Fire) [reply src/main/java/net/minecraftforge/common/ForgeMod.java:157]: Maybe, eclipse was smart enough to detect it through the jdoc, and IDEA tends to be "smarter" than eclipse, so I figured it was sufficient.

File: patches/minecraft/net/minecraft/client/renderer/GameRenderer.java.patch [hunk 2]
```diff
@@ -17,28 +17,30 @@
...
              if (this.f_109059_.f_91072_.m_105291_()) {
 -               d1 = 6.0D;
-+               d1 = Math.max(d0, atkRange);
++               d1 = Math.max(d0, entityReach);
                 d0 = d1;
              } else {
 -               if (d0 > 3.0D) {
-+               if (d0 > atkRange) {
++               if (d0 > entityReach) {
                    flag = true;
```
Comment (LexManos) [inline patches/minecraft/net/minecraft/client/renderer/GameRenderer.java.patch]: If you remove the use of flag, then this is not needed.

File: src/main/java/net/minecraftforge/common/ForgeMod.java (hunk 1 above)
Comment (LexManos) [reply src/main/java/net/minecraftforge/common/ForgeMod.java:157]: We use the deprecated annotation, and the since value to tell us when to delete.

File: src/main/java/net/minecraftforge/common/ForgeMod.java [hunk 3]
```diff
@@ -138,30 +138,43 @@
...
-     * Reach Distance represents the distance at which a player may interact with the world.  The default is 4.5 blocks.  Players in creative mode have an additional 0.5 blocks of reach distance.
-     * @see IForgePlayer#getReachDistance()
-     * @see IForgePlayer#canInteractWith(BlockPos, double)
-     * @see IForgePlayer#canInteractWith(Entity, double)
+     * Reach Distance represents the distance at which a player may interact with the world.  The default is 4.5 blocks.  Players in creative mode have an additional 0.5 blocks of block reach.
+     * @see IForgePlayer#getBlockReach()
+     * @see IForgePlayer#canReach(BlockPos, double)
      */
-    public static final RegistryObject<Attribute> REACH_DISTANCE = ATTRIBUTES.register("reach_distance", () -> new RangedAttribute("generic.reachDistance", 4.5D, 0.0D, 1024.0D).setSyncable(true));
+    public static final RegistryObject<Attribute> BLOCK_REACH = ATTRIBUTES.register("block_reach", () -> new RangedAttribute("forge.block_reach", 4.5D, 0.0D, 1024.0D).setSyncable(true));
```
Comment (LexManos) [inline src/main/java/net/minecraftforge/common/ForgeMod.java:150]: Have we confirmed what happens when this registry name changes? IIRC it should just be a 'unknown attribute' when reading an entity from disk. Which then gets resuscitated by whatever added the original attribute modifiers in the first place.. But lets be sure we document what happens either way in this PR.

File: src/main/java/net/minecraftforge/common/ForgeMod.java [hunk 4]
```diff
@@ -452,6 +465,11 @@ public ForgeMod()
         MinecraftForge.EVENT_BUS.addListener(this::registerPermissionNodes);
 
         ForgeRegistries.ITEMS.tags().addOptionalTagDefaults(Tags.Items.ENCHANTING_FUELS, Set.of(ForgeRegistries.ITEMS.getDelegateOrThrow(Items.LAPIS_LAZULI)));
+
+        // TODO: Remove when addAlias becomes proper API, as this should be done in the DR's above.
+        ForgeRegistry<Attribute> attrReg = (ForgeRegistry<Attribute>) ForgeRegistries.ATTRIBUTES;
+        attrReg.addAlias(new ResourceLocation("forge", "reach_distance"), new ResourceLocation("forge", "block_reach"));
```
Comment (LexManos) [inline src/main/java/net/minecraftforge/common/ForgeMod.java]: Pull this out into its own method, and annotate with @deprecated so that we can use static analysis to tell us when to delete it. 
`@Deprecated(forRemoval = true, since = `1.19.3`) // TODO: Remove when a proper alias API has been added to the registry, or we break world format`
Something like that.

File: src/main/java/net/minecraftforge/common/extensions/IForgePlayer.java [hunk 5]
```diff
@@ -22,74 +23,118 @@ private Player self()
...
+     */
+    default double getAttackRange()
+    {
+        return this.getEntityReach();
+    }
+
+    /**
+     * @deprecated use {@link #getBlockReach()}
+     */
+    default double getReachDistance()
```
Comment (LexManos) [inline src/main/java/net/minecraftforge/common/extensions/IForgePlayer.java]: These need proper annotations, and I prefer these renames to be right next to the newly named function. It makes it easier for people to find and for me to see that they arnt binary breaking changes.

File: src/main/java/net/minecraftforge/registries/ForgeRegistry.java [hunk 6]
```diff
@@ -473,10 +473,11 @@ public V getRaw(ResourceLocation key)
         return ret;
     }
 
-    void addAlias(ResourceLocation from, ResourceLocation to)
+    // TODO: Add as public api in IForgeRegistry - currently visible for remapping reach/range attributes.
```
Comment (LexManos) [inline src/main/java/net/minecraftforge/registries/ForgeRegistry.java]: Toss a @ApiStatus.Internal onto the entire ForgeRegistry class. People should be accessing it through our public API.

**Comment by LexManos** [comment]
Few minor cleanups, and then this looks good to me.
Note to whoever pulls the language files: Be sure to not remove entries from crowdin so that old builds can still build.

File: src/main/java/net/minecraftforge/common/ForgeMod.java (hunk 3 above)
Comment (Shadows-of-Fire) [reply src/main/java/net/minecraftforge/common/ForgeMod.java:150]: Based on my testing, it works flawlessly.  Anything that attempts to load with the name `reach_distance` looks up the object via the alias, and is then saved with the new name.

**Comment by Meldexun** [comment]
I tested the changes of this PR and now it's possible to hit blocks through entities that are outside the entity reach.

https://user-images.githubusercontent.com/27779321/224099308-4525ea0e-262d-4308-bf4e-a8390039f1bc.mp4

<br>

It's also possible to hit entities through blocks that are outside the block reach (assuming that the entity reach is greater than the block reach).

**Comment by KnightMiner** [comment]
> I tested the changes of this PR and now it's possible to hit blocks through entities that are outside the entity reach.
> 
> 
> It's also possible to hit entities through blocks that are outside the block reach (assuming that the entity reach is greater than the block reach).

Is that a problem?

**Comment by Meldexun** [comment]
> Is that a problem?

I would say it's kind of confusing and unrealistic. Also that's not how it works in vanilla Minecraft.

**Comment by Shadows-of-Fire** [comment]
I suppose the patch in GameRenderer#pick needs to be changed to always pick with the highest of the two, and perform the distance checks against both (ensuring that if one was hit, we cap the distance for the other)

It is considered a bug by vanilla to be able to "click through" things, so this needs to be addressed

**Comment by LexManos** [comment]
> I would say it's kind of confusing and unrealistic. Also that's not how it works in vanilla Minecraft.

Is it not how it works in vanilla due to vanilla never having a block reach that is more then entity reach, or something else?

> It is considered a bug by vanilla to be able to "click through" things, so this needs to be addressed

For documentation sake, can you cite a source on this? Because code wise it looks like vanilla doesn't care. 

Honestly I can see both sides of it, gameplay wise it doesnt make sense that we can 'reach through' 'solid' objects like entities. But on the code side it makes sense. All I care about is that we mimic vanilla behavior as long as no mods edit the values. Once the mods edit the values, vanilla's behavior doesn't matter.

**Comment by Shadows-of-Fire** [comment]
Mojira bug for this being a problem - https://bugs.mojang.com/browse/MC-76493

Vanilla fixes it by ignoring it (i.e. it can never happen due to the reach distances), but that doesn't work here.

**Comment by LexManos** [comment]
> Working as intended. Your interaction range is lower than the block-interaction range. When aiming at something that you cannot interact with however we now make sure you cannot reach the block behind it.

Interesting, this would claim the other, that they explicitly check that there is no entity in the way before accepting the block hit.
Probably worth seeing the 1.8.2-pre5 diff to confirm their 'fix'.

But i'm willing to accept this as documentation of the intention aligning with basic gameplay expectations.
That being: You can't magically pass through an entity to hit the block behind it, even if your block reach is longer then your entity reach.

Just be sure that this is documented as intentional in the code.

File: patches/minecraft/net/minecraft/client/gui/Gui.java.patch [hunk 7]
```diff
@@ -4,7 +4,7 @@
                    if (this.f_92986_.f_91076_ != null && this.f_92986_.f_91076_ instanceof LivingEntity && f >= 1.0F) {
                       flag = this.f_92986_.f_91074_.m_36333_() > 5.0F;
                       flag &= this.f_92986_.f_91076_.m_6084_();
-+                     flag &= this.f_92986_.f_91074_.canHit(this.f_92986_.f_91076_, 0);
++                     flag &= this.f_92986_.f_91074_.canReach(this.f_92986_.f_91077_.m_82450_(), 0);
```
Comment (Meldexun) [inline patches/minecraft/net/minecraft/client/gui/Gui.java.patch]: This line is no longer needed because the entity attack reach and interaction reach is now the same again like in vanilla.

File: patches/minecraft/net/minecraft/world/entity/player/Player.java.patch [hunk 8]
```diff
@@ -258,7 +258,7 @@
 -                     for(LivingEntity livingentity : this.f_19853_.m_45976_(LivingEntity.class, p_36347_.m_20191_().m_82377_(1.0D, 0.25D, 1.0D))) {
 -                        if (livingentity != this && livingentity != p_36347_ && !this.m_7307_(livingentity) && (!(livingentity instanceof ArmorStand) || !((ArmorStand)livingentity).m_31677_()) && this.m_20280_(livingentity) < 9.0D) {
 +                     for(LivingEntity livingentity : this.f_19853_.m_45976_(LivingEntity.class, this.m_21120_(InteractionHand.MAIN_HAND).getSweepHitBox(this, p_36347_))) {
-+                        if (livingentity != this && livingentity != p_36347_ && !this.m_7307_(livingentity) && (!(livingentity instanceof ArmorStand) || !((ArmorStand)livingentity).m_31677_()) && this.canHit(livingentity, 0)) { // Original check was dist < 3, range is 3, so vanilla used padding=0
++                        if (livingentity != this && livingentity != p_36347_ && !this.m_7307_(livingentity) && (!(livingentity instanceof ArmorStand) || !((ArmorStand)livingentity).m_31677_()) && this.canReach(livingentity, 0)) { // Original check was dist < 3, range is 3, so vanilla used padding=0
```
Comment (Meldexun) [inline patches/minecraft/net/minecraft/world/entity/player/Player.java.patch]: Changing this from a "bottom-center to bottom-center" distance check to an "eyes to closest-corner" distance check will make the player be able to hit entities with the sweep that wouldn't be hit in vanilla in some scenarios.

File: patches/minecraft/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch [hunk 9]
```diff
@@ -68,18 +68,15 @@
...
                    }, p_248212_);
                 });
-@@ -1434,9 +_,10 @@
+@@ -1434,7 +_,7 @@
              return;
           }
  
 -         if (entity.m_20238_(this.f_9743_.m_146892_()) < f_215198_) {
-+         if (true) { //Forge: Perform distance checks below since interactions and attacks differ.
++         if (this.f_9743_.canReach(entity, 2)) { // Tighten padding to 2 (from 3) due to eye-to-closest-corner check. (vanilla uses bottom center-to-center)
```
Comment (Meldexun) [inline patches/minecraft/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch]: I checked this again and I was wrong here https://github.com/MinecraftForge/MinecraftForge/pull/9013#issuecomment-1436949100.

Vanilla uses a "player-eyes to bottom-center" distance check here. This means that the new "player-eyes to closest-corner" distance check will make the player be able to hit some big mobs which wouldn't be hittable in vanilla in some scenarios.
The affected vanilla entities are:
- Wither (only slightly affected)
- Ghast (affected more than Wither due to larger size)

All other vanilla mobs are too small to be affected.
(Note that this is also an issue without the changes from #9013)

My personal opinion is that a "player-eyes to closest-corner" distance check is fine here since it only slightly affects the Wither, Ghasts are usually not fought melee and this will most likely be preferred by modders who add large entities.

**Review by Meldexun — COMMENTED** [review]
I noticed a few things that will be different from vanilla when this PR gets merged.

File: patches/minecraft/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch (hunk 9 above)
Comment (Shadows-of-Fire) [reply patches/minecraft/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch]: I agree.  This check is preferable.  People would expect it to work correctly for large entities, and it doesn't impact anything that isn't very large.

File: patches/minecraft/net/minecraft/world/entity/player/Player.java.patch (hunk 8 above)
Comment (Shadows-of-Fire) [reply patches/minecraft/net/minecraft/world/entity/player/Player.java.patch]: Is that significant?  I.e. do we care about a slight disparity on sweeping edge attacks being valid?  We _might_ be able to raise this as a vanilla bug, because entities within the sweeping hitbox aren't valid for attacking unless their center is valid.

For standard entities, the difference is (at most) the radius of their hitbox.  For large entities, we end up with the same thing as in the below discussion, where it probably makes more sense to make it work correctly as it won't impact vanilla.

**Comment by Shadows-of-Fire** [comment]
> Interesting, this would claim the other, that they explicitly check that there is no entity in the way before accepting the block hit.  

Vanilla does perform this check in `GameRenderer#pick(float)`, but it relies on assumptions that are not true when the attributes can change.  I've fixed the checks to work properly when the distances can change.

File: patches/minecraft/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch (hunk 9 above)
Comment (Shadows-of-Fire) [reply patches/minecraft/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch]: It looks like vanilla uses E2CC anyway, since AABB#distanceToSqr uses closest-corner checks, so this actually doesn't change.
