### PR TITLE
[1.17.x] Fix part entities not working at all

### LINKED ISSUE #8071: [1.17.1] PartEntity doesn't replace all instances of EnderDragonPart
**Minecraft Version:** 1.17.1

**Forge Version:** 37.0.53

**Description of issue:**
The class `PartEntity` provided by forge does not replace the instances of `EnderDragonPart` in the methods `Level#getEntities`, `ServerLevel.EntityCallbacks#onTrackingStart`, and`ServerLevel.EntityCallbacks#onTrackingEnd` as well as the field `dragonParts` in `ServerLevel` meaning subclasses of `PartEntity` besides `EnderDragonPart` are not properly handled on the server and cannot be targeted in `Level#getEntities`.

### PR DESCRIPTION
**Pull request by uSkizzik**
This PR fixes #8071 by replacing all usages of `EnderDragonPart` outside of the `EnderDragon` class with PartEntity.

### CODE REVIEW

File: src/test/java/net/minecraftforge/debug/entity/PartEntityTest.java [hunk 1]
```diff
@@ -0,0 +1,188 @@
+package net.minecraftforge.debug.entity;
+
+import net.minecraft.client.renderer.entity.PigRenderer;
+import net.minecraft.nbt.CompoundTag;
+import net.minecraft.network.protocol.Packet;
+import net.minecraft.network.protocol.game.ClientboundAddMobPacket;
+import net.minecraft.world.damagesource.DamageSource;
+import net.minecraft.world.entity.*;
```
Comment (ChampionAsh5357) [inline src/test/java/net/minecraftforge/debug/entity/PartEntityTest.java]: No wildcard imports.

File: src/test/java/net/minecraftforge/debug/entity/PartEntityTest.java [hunk 2]
```diff
@@ -0,0 +1,188 @@
+package net.minecraftforge.debug.entity;
```
Comment (ChampionAsh5357) [inline src/test/java/net/minecraftforge/debug/entity/PartEntityTest.java:20]: Missing license header.

File: src/test/java/net/minecraftforge/debug/entity/PartEntityTest.java [hunk 3]
```diff
@@ -0,0 +1,188 @@
...
+        event.put(TEST_ENTITY.get(), Pig.createAttributes().build());
+    }
+
+    @Mod.EventBusSubscriber(modid = MOD_ID, value = Dist.CLIENT, bus = Mod.EventBusSubscriber.Bus.MOD)
+    private static class ClientEvents
+    {
+        @SubscribeEvent
+        public static void onRegisterRenderers(final EntityRenderersEvent.RegisterRenderers event)
+        {
+            if (!ENABLED) { return; }
```
Comment (ChampionAsh5357) [inline src/test/java/net/minecraftforge/debug/entity/PartEntityTest.java]: Unnecessary brackets.

File: src/test/java/net/minecraftforge/debug/entity/PartEntityTest.java [hunk 4]
```diff
@@ -0,0 +1,188 @@
...
+        {
+            return this.size;
+        }
+
+        public boolean shouldBeSaved() 
+        {
+            return false;
+        }
+    }
+}
```
Comment (ChampionAsh5357) [inline src/test/java/net/minecraftforge/debug/entity/PartEntityTest.java]: LF at EOF. (Line feed (or new line) at end of file)

**Review by ChampionAsh5357 — CHANGES_REQUESTED** [review]
Seems to work fine from testing, just formatting changes. There is one thing I'm unsure about, so I'll wait to hear back about it.

**Review by ChampionAsh5357 — APPROVED** [review]
