### PR TITLE
Fix inconsistency between vanilla and modded glass. Closes #4679

### LINKED ISSUE #4679: Water_flow on modded glass blocks
I noticed that water blocks when next to vanilla glass use the water_overlay texture while with modded glass it uses water_flow. It seems the method `BlockFluidRenderer::renderFluid` is checking if the adjacent blocks are either glass or stained glass to decide if to render water_overlay.

Example:
water

### PR DESCRIPTION
**Pull request by BernardoCBranco**
Fixes #4679.

Changed `BlockFluidRenderer::renderFluid` to check the material instead of the block itself, so all blocks with Material.GLASS should now work fine.

### CODE REVIEW

**Comment by mezz** [comment]
Looks like a good, simple fix.

**Comment by williewillus** [comment]
do forge fluids handle this properly? they use `ModelFluid` instead of vanilla's BlockFluidRenderer

**Comment by mezz** [comment]
I just checked and Forge fluids don't handle any kind of glass, the sides are always flowing. I think that can be considered a different issue though, the Forge fluids probably still have a few rendering inconsistencies vs vanilla.

**Comment by mezz** [comment]
I think this will make water render incorrectly against glass panes.
Please check that the block is solid on the side that the fluid is against.

**Comment by HenryLoenwind** [comment]
I don't think glass isSolid?

**Comment by BernardoCBranco** [comment]
@mezz The way it is now, water against glass panes renders water_overlay, which differs from vanilla behaviour, normally it would render water_overlay for glass blocks and water_flow for everything else (including glass panes).

**Comment by BernardoCBranco** [comment]
@mezz It does cause some issues with glass panes. :\

Before:


After:

**Comment by BernardoCBranco** [comment]
Water blocks against glass panes now render correctly. `BlockFluidRenderer::renderFluid` now checks if the adjacent blocks are not glass panes and only then renders water_overlay.

**Comment by mezz** [comment]
I think it's important to look at the reasoning behind why glass works this way, and look at the block's properties instead of using anything like `==` or `instanceof Block`. Ideally these rules should work for modded blocks properly, without people having to really think about it.

**Comment by BernardoCBranco** [comment]
Something like this `if (state.getBlockFaceShape(blockAccess, blockpos, EnumFacing.UP) == BlockFaceShape.SOLID) { ... }`? By doing things this way, only "full" blocks should use water_overlay and from what I tested it seems to work fine, even with modded blocks.

**Comment by BernardoCBranco** [comment]
It would also need to check the bottom otherwise slabs would not work properly.

**Comment by BernardoCBranco** [comment]
Improved over the example above. Now checks the block faces that are against the water block to see if they're solid.

File: patches/minecraft/net/minecraft/client/renderer/BlockFluidRenderer.java.patch [hunk 1]
```diff
@@ -0,0 +1,30 @@
+--- ../src-base/minecraft/net/minecraft/client/renderer/BlockFluidRenderer.java
++++ ../src-work/minecraft/net/minecraft/client/renderer/BlockFluidRenderer.java
+@@ -1,14 +1,13 @@
+ package net.minecraft.client.renderer;
+ 
+-import net.minecraft.block.Block;
+ import net.minecraft.block.BlockLiquid;
+ import net.minecraft.block.material.Material;
++import net.minecraft.block.state.BlockFaceShape;
```
Comment (mezz) [inline patches/minecraft/net/minecraft/client/renderer/BlockFluidRenderer.java.patch]: Patches to Minecraft code should not change the imports.
Instead of importing, use the fully qualifies name where you need it, like `net.minecraft.block.state.BlockFaceShape.SOLID`

**Review by mezz — CHANGES_REQUESTED** [review]
Looks good, just need to fix the patches so there are no import changes.

File: patches/minecraft/net/minecraft/client/renderer/BlockFluidRenderer.java.patch [hunk 2]
```diff
@@ -0,0 +1,14 @@
...
++++ ../src-work/minecraft/net/minecraft/client/renderer/BlockFluidRenderer.java
+@@ -184,9 +184,9 @@
+ 
+                 if (!flag)
+                 {
+-                    Block block = p_178270_1_.func_180495_p(blockpos).func_177230_c();
++                    IBlockState state = p_178270_1_.func_180495_p(blockpos);
+ 
+-                    if (block == Blocks.field_150359_w || block == Blocks.field_150399_cn)
++                    if (state.func_193401_d(p_178270_1_, blockpos, EnumFacing.field_82609_l[i1+2].func_176734_d()) == net.minecraft.block.state.BlockFaceShape.SOLID)
```
Comment (mezz) [inline patches/minecraft/net/minecraft/client/renderer/BlockFluidRenderer.java.patch:11]: I think `EnumFacing.VALUES[i1+2]` should be `EnumFacing.getHorizontal(i1)`

**Review by mezz — CHANGES_REQUESTED** [review]

File: patches/minecraft/net/minecraft/client/renderer/BlockFluidRenderer.java.patch (hunk 2 above)
Comment (BernardoCBranco) [reply patches/minecraft/net/minecraft/client/renderer/BlockFluidRenderer.java.patch:11]: That doesn't work because `VALUES` and `HORIZONTALS` are ordered differently. (`getHorizontal()` just returns the values from `HORIZONTALS`)

VALUES[2] -> NORTH
VALUES[3] -> SOUTH
VALUES[4] -> WEST
VALUES[5] -> EAST

HORIZONTALS[0] -> SOUTH
HORIZONTALS[1] -> WEST
HORIZONTALS[2] -> NORTH
HORIZONTALS[3] -> EAST

`BlockFluidRenderer::renderFluid` checks the adjacent blocks in the same order as `VALUES`, so if I used `EnumFacing.getHorizontal(i1)` it would check the wrong side of the block, it wouldn't check the side that's against water.

Comment (BernardoCBranco) [reply patches/minecraft/net/minecraft/client/renderer/BlockFluidRenderer.java.patch:11]: Probably would make sense to make `HORIZONTALS` follow the same order as `VALUES`. Then it would be possible to use `getHorizontal(i1)` instead of `VALUES[i1+2]`. Although it would break something that depends on it being in the current order. :\

Comment (mezz) [reply patches/minecraft/net/minecraft/client/renderer/BlockFluidRenderer.java.patch:11]: Yuck, ok. Nothing we can do about that, yeah.

**Review by mezz — APPROVED** [review]

**Comment by mezz** [comment]
Can you make a final screenshot to show this off?

**Comment by BernardoCBranco** [comment]
Here are some screenshots but I also found some issues.

water2

Here's an image showing what makes water render water_overlay and what doesn't:


Water next to any solid face now renders water_overlay.

1. Glass Pane
2. Diamond Glass Pane - Diamond Glass
3. Diamond Glass Stairs (side) - Diamond Glass
4. Stone Slab
5. Structuralduct with Hardened Silver Glass Cover - Thermal Dynamics ***1**
6. Cobblestone Structure Pipe with Facade: Glass - Buildcraft ***2**
7. Thickened Glass - Extra Utilities
8. Glass
9. Diamond Glass - Diamond Glass
10. Ice
11. Hardened Copper Glass - Thermal Foundation
12. Diamond Glass Stairs (back to water) - Diamond Glass

## Issues:
### 1.
As you can see in the image below, it wasn't working properly, the water is flowing even with the cover. I managed to fix this by also checking `isSideSolid()`. 

Before:


After:


### 2.
This one also doesn't work right and it's even worse than the first. It's always solid even without a facade on, wich makes it look like this when underwater:

**Comment by mezz** [comment]
I think just one check for `getBlockFaceShape` should be good enough, checking both seems like a workaround for a minor bug in BuildCraft.

**Comment by BernardoCBranco** [comment]
Reset to previous commit, I don't know if that's the best way to do it, but I thought it would make more sense than leaving it in and having another undoing it. Anyway, now it only checks `getBlockFaceShape`.
