### PR TITLE
Fix packet handling on play messages.

### LINKED ISSUE #8873: [Bug] SpawnEntity packet additional data is not accessible in custom client factory
**Minecraft Version:** 1.19

**Forge Version:** 41.0.98

**Logs:** 
Stack Trace: https://gist.github.com/jglrxavpok/68fa6e4488e9ea7a0fcee842428f717f
latest.log: https://gist.github.com/jglrxavpok/c2f4080d922fd52894804099430d6be3

**Steps to Reproduce:**
1. Setup an Entity implementing IEntityAdditionalSpawnData
2. When spawning the entity, read from the buffer passed as input of `IEntityAdditionalSpawnData#readSpawnData(FriendlyByteBuf)`
3. An exception is thrown because the buffer is no longer accessible.

**Description of issue:**
Additional spawn data cannot be read from the SpawnEntity packet due to the internal buffer not being accessible.
This does not prevent entities to spawn, but no data will be loaded into the entity.

I believe the networking changes of PR #8703 require the buffer to be kept alive until it is used in the enqueueWork callback.

My readSpawnData method for reference:
```kotlin
    override fun readSpawnData(additionalData: FriendlyByteBuf) {
        try {
            val data = additionalData.readNbt()
            readAdditionalSaveData(data!!)
        } catch (t: Throwable) {
            MoarBoats.logger.error("Error in readSpawnData", t)
        }
    }
```

### PR DESCRIPTION
**Pull request by marchermans**
This fixes forges own play messages trying to read data from a FriendlyByteBuf in an enqueueWork section after the code-flow execution of the network thread (which owns and frees said FriendlyByteBuf) has already been completed.

Fixes: #8873

### CODE REVIEW

File: src/main/java/net/minecraftforge/network/PlayMessages.java [hunk 1]
```diff
@@ -109,7 +111,17 @@ public static void encode(SpawnEntity msg, FriendlyByteBuf buf)
             buf.writeShort(msg.velZ);
             if (msg.entity instanceof IEntityAdditionalSpawnData)
             {
-                ((IEntityAdditionalSpawnData) msg.entity).writeSpawnData(buf);
+                final FriendlyByteBuf spawnDataBuffer = new FriendlyByteBuf(Unpooled.buffer());
+
+                ((IEntityAdditionalSpawnData) msg.entity).writeSpawnData(spawnDataBuffer);
```
Comment (sciwhiz12) [inline src/main/java/net/minecraftforge/network/PlayMessages.java]: Since we're already modifying this code, this should be using pattern-matching instanceof.

File: src/main/java/net/minecraftforge/network/PlayMessages.java [hunk 2]
```diff
@@ -109,7 +111,17 @@ public static void encode(SpawnEntity msg, FriendlyByteBuf buf)
...
+
+                buf.writeVarInt(spawnDataBuffer.readableBytes());
+                buf.writeBytes(spawnDataBuffer);
+
+                spawnDataBuffer.release();
+            }
+            else {
```
Comment (sciwhiz12) [inline src/main/java/net/minecraftforge/network/PlayMessages.java]: Formatting: braces on newlines.
```suggestion
            else
            {
```

File: src/main/java/net/minecraftforge/network/PlayMessages.java [hunk 3]
```diff
@@ -122,23 +134,36 @@ public static SpawnEntity decode(FriendlyByteBuf buf)
...
                     buf.readByte(), buf.readByte(), buf.readByte(),
                     buf.readShort(), buf.readShort(), buf.readShort(),
-                    buf
+                    readSpawnDataPacket(buf)
                     );
         }
 
+        private static FriendlyByteBuf readSpawnDataPacket(FriendlyByteBuf buf) {
+            final int count = buf.readVarInt();
+            if (count > 0) {
```
Comment (sciwhiz12) [inline src/main/java/net/minecraftforge/network/PlayMessages.java]: Formatting: braces on newlines.
```suggestion
        private static FriendlyByteBuf readSpawnDataPacket(FriendlyByteBuf buf)
        {
            final int count = buf.readVarInt();
            if (count > 0)
            {
```

File: src/main/java/net/minecraftforge/network/PlayMessages.java [hunk 4]
```diff
@@ -122,23 +134,36 @@ public static SpawnEntity decode(FriendlyByteBuf buf)
...
+            return new FriendlyByteBuf(Unpooled.buffer());
+        }
+
         public static void handle(SpawnEntity msg, Supplier<NetworkEvent.Context> ctx)
         {
             ctx.get().enqueueWork(() -> {
                 EntityType<?> type = Registry.ENTITY_TYPE.byId(msg.typeId);
                 if (type == null)
                 {
+                    msg.buf.release();
```
Comment (sciwhiz12) [inline src/main/java/net/minecraftforge/network/PlayMessages.java]: Perhaps a `try`-`finally` would be better here to ensure the buffer's release, instead of inserting multiple release calls?

File: src/main/java/net/minecraftforge/network/PlayMessages.java [hunk 5]
```diff
@@ -159,6 +184,7 @@ public static void handle(SpawnEntity msg, Supplier<NetworkEvent.Context> ctx)
                 {
                     ((IEntityAdditionalSpawnData) e).readSpawnData(msg.buf);
```
Comment (sciwhiz12) [inline src/main/java/net/minecraftforge/network/PlayMessages.java]: Please also convert this into using pattern-matching `instanceof`.

File: src/main/java/net/minecraftforge/network/PlayMessages.java [hunk 6]
```diff
@@ -273,6 +299,7 @@ public static void handle(OpenContainer msg, Supplier<NetworkEvent.Context> ctx)
                 MenuScreens.getScreenFactory(msg.getType(), Minecraft.getInstance(), msg.getWindowId(), msg.getName())
                              .ifPresent(f -> {
                                  AbstractContainerMenu c = msg.getType().create(msg.getWindowId(), Minecraft.getInstance().player.getInventory(), msg.getAdditionalData());
+                                 msg.getAdditionalData().release();
```
Comment (sciwhiz12) [inline src/main/java/net/minecraftforge/network/PlayMessages.java]: This is also a candidate for using a `try`-`finally` to ensure the buffer is released.

**Review by sciwhiz12 — CHANGES_REQUESTED** [review]

File: src/main/java/net/minecraftforge/network/PlayMessages.java [hunk 7]
```diff
@@ -122,42 +132,67 @@ public static SpawnEntity decode(FriendlyByteBuf buf)
...
-                e.setYBodyRot((msg.headYaw * 360) / 256.0F);
-
-                e.setId(msg.entityId);
-                e.setUUID(msg.uuid);
-                world.filter(ClientLevel.class::isInstance).ifPresent(w->((ClientLevel)w).putNonPlayerEntity(msg.entityId, e));
-                e.lerpMotion(msg.velX / 8000.0, msg.velY / 8000.0, msg.velZ / 8000.0);
-                if (e instanceof IEntityAdditionalSpawnData)
+        public static void handle(SpawnEntity msg, Supplier<NetworkEvent.Context> ctx)
+        {
+            ctx.get().enqueueWork(() ->
```
Comment (TheCurle) [inline src/main/java/net/minecraftforge/network/PlayMessages.java]: I beg you to make this function easier to read.

I legitimately cannot parse the control flow or order of parameters being used here.

Please make things one giant line if it benefits, this ridiculous line splitting is horrendous for the rest of us.

File: src/main/java/net/minecraftforge/network/PlayMessages.java [hunk 8]
```diff
@@ -122,42 +132,67 @@ public static SpawnEntity decode(FriendlyByteBuf buf)
...
+            {
+                try {
+                    EntityType<?> type = Registry.ENTITY_TYPE.byId(msg.typeId);
+                    if (type == null)
```
Comment (TheCurle) [inline src/main/java/net/minecraftforge/network/PlayMessages.java]: This is a useless check, type cannot be null.

**Review by sciwhiz12 — APPROVED** [review]
