### PR TITLE
Fix `SidedInvWrapper` not accounting for vanilla stacking special cases

### LINKED ISSUE #9178: `(Sided)InvWrapper` does not account for some `canPlaceItem` edge cases
**Minecraft Version:** 1.19.2

**Forge Version:** 43.1.25

**Steps to Reproduce:**
 1. Try to insert a stack of >1 buckets or bottles from the side of a furnace or brewing stand respectively using some modded automation. I used IE conveyors.
 2. Notice that the furnace or brewing stand accepts too many items: 
image
image

**Detailed explanation**
So, vanilla has two very hacky `Container#canPlaceItem` implementations to make some specifc items unstackable. They achieve this by allowing insertions if the current stack is empty. This works fine when inserting items 1 by 1, however in a modded context it doesn't work when multiple items are inserted at once.

The two offenders are the insertion of buckets in the furnace fuel slot and the insertion of brewing recipe inputs in slots 0/1/2:
image
image

`SidedInvWrapper` needs special logic to account for this edge case. I'll provide the patch in a bit.

### PR DESCRIPTION
**Pull request by Technici4n**
Fixes #9178.

### CODE REVIEW

**Comment by Technici4n** [comment]
Just tested. Was a good idea because my original fix was broken; this one works though. 😅

File: src/main/java/net/minecraftforge/items/wrapper/SidedInvWrapper.java [hunk 1]
```diff
@@ -142,6 +145,17 @@ public ItemStack insertItem(int slot, @NotNull ItemStack stack, boolean simulate
                 return stack;
 
             m = Math.min(stack.getMaxStackSize(), getSlotLimit(slot));
+
+            // A few special cases to account for canPlaceItem implementations attempting to limit specific inputs to 1,
+            // by returning false if there's already a contained item. This doesn't work with modded inserted sizes > 1.
+            // - Limit buckets to 1 in furnace fuel inputs.
+            // - Limit brewing stand "bottle" inputs to 1.
+            if (inv instanceof AbstractFurnaceBlockEntity && getSlot(inv, slot, side) == 1 && stack.is(Items.BUCKET)
+                    || inv instanceof BrewingStandBlockEntity && getSlot(inv, slot, side) < 3)
```
Comment (sciwhiz12) [inline src/main/java/net/minecraftforge/items/wrapper/SidedInvWrapper.java]: Since you've filed issue #9178 on this, we should probably add the issue number here for posterity.

Also, in the interest of ensuring maximum clarity, please surround the two conditions of the `||` with parentheses.

**Review by sciwhiz12 — CHANGES_REQUESTED** [review]

**Review by sciwhiz12 — APPROVED** [review]

File: src/main/java/net/minecraftforge/items/wrapper/SidedInvWrapper.java [hunk 2]
```diff
@@ -142,6 +145,18 @@ public ItemStack insertItem(int slot, @NotNull ItemStack stack, boolean simulate
...
 
             m = Math.min(stack.getMaxStackSize(), getSlotLimit(slot));
+
+            // A few special cases to account for canPlaceItem implementations attempting to limit specific inputs to 1,
+            // by returning false if there's already a contained item. This doesn't work with modded inserted sizes > 1.
+            // - Limit buckets to 1 in furnace fuel inputs.
+            // - Limit brewing stand "bottle" inputs to 1.
+            // See also https://github.com/MinecraftForge/MinecraftForge/issues/9178
+            if ((inv instanceof AbstractFurnaceBlockEntity && getSlot(inv, slot, side) == 1 && stack.is(Items.BUCKET))
+                    || (inv instanceof BrewingStandBlockEntity && getSlot(inv, slot, side) < 3))
```
Comment (pupnewfster) [inline src/main/java/net/minecraftforge/items/wrapper/SidedInvWrapper.java]: I feel like it would be reasonable to move the override check for the brewing stand to happening in `getSlotLimit`. That way if any mods query the slot limit for other use cases they get the proper value.

**Review by pupnewfster — CHANGES_REQUESTED** [review]

File: src/main/java/net/minecraftforge/items/wrapper/SidedInvWrapper.java [hunk 3]
```diff
@@ -8,18 +8,34 @@
...
     protected final Direction side;
 
+    // A few special cases to account for canPlaceItem implementations attempting to limit specific inputs to 1,
+    // by returning false if there's already a contained item. This doesn't work with modded inserted sizes > 1.
+    // - Limit buckets to 1 in furnace fuel inputs.
+    // - Limit brewing stand "bottle" inputs to 1.
+    // Done using lambdas to avoid the overhead of instanceof checks in hot code.
+    private final IntUnaryOperator slotLimit;
+    private final InsertLimit newStackInsertLimit;
+    private interface InsertLimit {
```
Comment (sciwhiz12) [inline src/main/java/net/minecraftforge/items/wrapper/SidedInvWrapper.java]: Formatting: braces on newlines.

File: src/main/java/net/minecraftforge/items/wrapper/SidedInvWrapper.java [hunk 4]
```diff
@@ -8,18 +8,34 @@
...
 {
     protected final WorldlyContainer inv;
     @Nullable
     protected final Direction side;
 
+    // A few special cases to account for canPlaceItem implementations attempting to limit specific inputs to 1,
+    // by returning false if there's already a contained item. This doesn't work with modded inserted sizes > 1.
+    // - Limit buckets to 1 in furnace fuel inputs.
+    // - Limit brewing stand "bottle" inputs to 1.
+    // Done using lambdas to avoid the overhead of instanceof checks in hot code.
```
Comment (sciwhiz12) [inline src/main/java/net/minecraftforge/items/wrapper/SidedInvWrapper.java]: This should probably be moved to the constructor instead.

**Review by sciwhiz12 — CHANGES_REQUESTED** [review]

**Review by sciwhiz12 — APPROVED** [review]
