### PR TITLE
Fixes parameter inconsistency in IFieldWrapper (Fixes #4325)

### LINKED ISSUE #4325: [1.12.x] FieldWrapper.MapWrapper doesn't add new properties to the Map
`FieldWrapper.MapWrapper#handlesKey` never returns `true` because it asks if the `name` argument starts with the `category` field followed by the `name` argument itself, which is impossible.  `name` will only ever be the simple name of a property, it will never be a fully-qualified name starting with a category.

This means that properties added to the `Map` field's category in the config file won't be added to the `Map` when `ConfigManager.sync` is called.

### PR DESCRIPTION
**Pull request by thilokru**
As described in Issue #4325, the interface IFieldWrapper wasn't clear about what the method parameters ment. This caused issues with the MapWrapper, because it disagreed with ConfigManager about what should be in the parameter name.

This PR fixes the parameter naming inconsistency by renaming it to `key` (which also fixes the collision with the field `name`).
To prevent similar problems in the future, `IFieldWrapper` and `ITypeAdapter` were documented.
Also, `ConfigManager::sync` now has more detailed comments to allow other developers to easier understand the code (I had trouble reading my own code...)

Additionally, as indicated by @Choonster , Map entries weren't synced properly. This was caused by faulty return values for the category and the FieldWrapper ignoring the fact, that category names are all lowercase. This is fixed with 3a519a1.

### CODE REVIEW

**Comment by thilokru** [comment]
@Choonster I'm pretty sure this fixes your issue, but please take a look to ensure it really does.

**Comment by Choonster** [comment]
After some testing, I don't think this fixes #4325.

In TestMod3, I have a `Map<String, Double>` field in my config class that's populated with three default values at startup ([here](https://github.com/Choonster-Minecraft-Mods/TestMod3/blob/2ce586d2a90443f3c71d4c201cfeb7f5a4169888/src/main/java/choonster/testmod3/config/ModConfig.java#L23-L30)).

If I add a new property to the corresponding category in the config file and then launch the game, this new property is visible in the config GUI but not present in the `Map` (which I verified using [this command](https://github.com/Choonster-Minecraft-Mods/TestMod3/blob/2ce586d2a90443f3c71d4c201cfeb7f5a4169888/src/main/java/choonster/testmod3/command/CommandDebugConfig.java#L28-L32)).

**Comment by thilokru** [comment]
Are you sure, that the way you use `@Mod.EventBusSubscriber` is correct? What you are describing sounds an awefull lot like `ConfigManager::sync` isn't been called when required. Maybe your event listener isn't working?

**Comment by Choonster** [comment]
The event handler is definitely being called after changes have been made in the config GUI, but that's not really relevant as the new property is already present in the `Configuration` object when `ConfigManager.sync` is first called from `FMLModContainer#constructMod`.

**Comment by thilokru** [comment]
I think I found out what caused this: The `MapWrapper` contains an implementation error; The base name is incorrect if the property has no parent category. Will fix this.

**Comment by thilokru** [comment]
This should fix the original bug and the problems reported above.

File: src/main/java/net/minecraftforge/common/config/ConfigManager.java [hunk 1]
```diff
@@ -218,39 +218,47 @@ private static void sync(Configuration cfg, Class<?> cls, String modid, String c
     {
         for (Field f : cls.getDeclaredFields())
         {
-            if (!Modifier.isPublic(f.getModifiers()))
+            if (!Modifier.isPublic(f.getModifiers())) //Allow modders to have private field for internal data
                 continue;
```
Comment (LexManos) [inline src/main/java/net/minecraftforge/common/config/ConfigManager.java]: Remove all your useless comment spam.

Comment (thilokru) [reply src/main/java/net/minecraftforge/common/config/ConfigManager.java]: I'll gladly do, but when I tried to understand this code (which I wrote almost a year ago), I could barely understand it anymore. As I suspect that there will be more bugs and/or missing features, other people might want to contribute. I think it is better to comment the code so that strangers can understand.

However, if you insist, I will remove it all.

Comment (LexManos) [reply src/main/java/net/minecraftforge/common/config/ConfigManager.java]: The only confusion is that you didnt clearly specify what the key should be.
But things like 'getType() Returns the type!' is just redundant.
Your code should be self-documenting for the most part sprinkeled with a few "I couldn't specify the format of the key in the variable name so here is the correct format" style comments.

Comment (thilokru) [reply src/main/java/net/minecraftforge/common/config/ConfigManager.java]: OK, I will try to change the comments to fit your criteria.

**Comment by thilokru** [comment]
Reson why this PR isn't stale: I need to fix the merge conflict, but currently, I don't have access to my computer to do that. Within a week I should be able to fix this.

**Comment by thilokru** [comment]
Merge conflicts have been resolved.
