### PR TITLE
[1.21.4] Update context in AddReloadListenerEvent

### LINKED ISSUE #10409: [1.21.4] Can't decode a Global Loot Modifier when it has an Item Tag
**Minecraft Version:** 1.21.4

**Forge Version:** 54.0.21

**Logs:** N/A

**Steps to Reproduce:** Generate a json file of a loot table using a `LootModifier`. Make it so one of the conditions or functions has a reference to an item, being the item an item tag, for example the `MatchTool` condition and put the tool as `#minecraft:pickaxes` (so `ItemTags.PICKAXES` on the `GlobalLootModifierProvider` class if we're generating this json file instead of just manually writing it, as is this case)

**Description of issue:** A data-generated loot table json doesn't get properly decoded into a `IGlobalLootModifier` in the `apply` method of the `LootModifierManager` class when this loot table contains an item tag, the `ifError` branch of the `parse` function inside the lambda of the `apply` method gets called. The `HolderLookup.Provider registries` field of that same class is missing most of the item tags on the Item registry at the momment `apply` gets executed, they haven't been added yet into it, they do after a bit of time (miliseconds).
I have no reason to think this is related to my code in any way, as the call to the `apply` method and the assignation of the `registries` field get done by core Forge classes and I don't think that can be configured in any way unless directly modifying the classes with mixins. But in any case, my repo is  [here](https://github.com/katanya04/mine-spawners-forge).

### PR DESCRIPTION
**Pull request by Jonathing**
The way server resources are loaded have changed since when this event was created. It has, for a long time, only given the context of the server resources and a registry access in the event. But now the server resources use a different context when accessing registries from within the listeners, found in `ReloadableServerRegistries.LoadResult`. Simply using the composite registry access isn't enough anymore, because it will not contain all information needed for everything to work, such as loot modifiers. The best way to test for this is to use a reload listener that needs access to tags.

I believe part of this is because the event is currently using a registry access that was cached from startup. So, every object up until the `RegistryLayer.STATIC` layer can be referenced, but since tags exist in the `RELOADABLE` layer, they haven't yet been added to the registry access. This means reloading all data resources in a world (using `/reload`) will give the reload listeners the context they need, but at that point it is probably too late.

This PR gives AddReloadListenerEvent this new context so that reload listeners can properly take advantage of the info in the registries the same way vanilla's reload listeners would. In short, it takes both values from the `ReloadableServerRegistries.LoadResult` and gives them to the event.

- Fixes #10409 for 1.21.4.

> [!CAUTION]
> This PR preserved a lot of now-deprecated methods for the sole purpose of preserving binary compat. If you are a modder, you should not be firing `AddReloadListenersEvent` on your own anyways.

### CODE REVIEW

**Comment by Jonathing** [comment]
Drafted because I forgot to generate the patches, and my laptop fucking died 😃👍

**Comment by Jonathing** [comment]
Patches are up. I also removed the `LayeredRegistryAccess<RegistryLayer>` I originally included in the event, since the holder lookup provider is all that's needed. Unfortunately I can't just replace the original registry access with this new thing, because the holder lookup is not a registry access, and would break bin compat if I did that.

File: src/main/java/net/minecraftforge/event/ForgeEventFactory.java [hunk 1]
```diff
@@ -712,10 +715,15 @@ public static long onSleepFinished(ServerLevel level, long newTime, long minTime
         return fire(new SleepFinishedTimeEvent(level, newTime, minTime)).getNewTime();
     }
 
+    @Deprecated(forRemoval = true, since = "1.21.4")
     public static List<PreparableReloadListener> onResourceReload(ReloadableServerResources serverResources, RegistryAccess registryAccess) {
         return fire(new AddReloadListenerEvent(serverResources, registryAccess)).getListeners();
     }
 
+    public static List<PreparableReloadListener> onResourceReload(ReloadableServerResources serverResources, HolderLookup.Provider lookupProvider, @Deprecated(forRemoval = true, since = "1.21.4") RegistryAccess registryAccess) {
+        return fire(new AddReloadListenerEvent(serverResources, lookupProvider, registryAccess)).getListeners();
```
Comment (LexManos) [inline src/main/java/net/minecraftforge/event/ForgeEventFactory.java:724]: Looks fine, only comment is that we typically add new parameters to the end of a function not the middle.
But this will work.

Comment (Jonathing) [reply src/main/java/net/minecraftforge/event/ForgeEventFactory.java:724]: Noted for next time.
