### PR TITLE
Fix #3634 Fix issues with Block.rotateBlock

### LINKED ISSUE #3634: Piston Bugs. Rotation. Block Dissapearing 1.11.2
EnderIO: 1.10.2-3.1.161
EnderCore: 0.4.1.64-beta
Minecraft: 1.10.2
Forge:12.18.3.2209

**Issue Description:**

Difficult to explain, but see the images to understand it. Better watch the videos too.

When i extend the piston then wrench it, it gets a bug that it wrenches the block, means it rotates it. but when you replace the redstone signal it will return to normal.

But, if your piston is rotated to a block and you update the redstone signal on and off again, you will see that the block disapears. It will do to any kind of block. Even bedrock. (only normal piston)

**What happens:**
Images:
http://i.imgur.com/N30YZYC.png
http://i.imgur.com/HEOz7we.png
http://i.imgur.com/4fno5hN.png

Videos:
https://vimeo.com/199477886
https://vimeo.com/199477948

How to break bedrock or any block:
https://vimeo.com/199478691

**What you expected to happen:**

To not do a glitch, and to not destroy a block.

**Steps to reproduce:**

1.Place down piston (any kind)
2.Place a redstone block at the corner of piston. meaning 1 block to the side, then 1 block up.
3.Wrench the extended piston.

Tried to post it on EnderIO but it got rejected and said this was forges problem:
https://github.com/SleepyTrousers/EnderIO/issues/3993#issue-200827096

Quote from the github said by HenryLoenwind:
Quote
Please report this to Forge, we are just asking the block to rotate itself, the rotation code for vanilla blocks is added by Forge.

---------------------------------------------------

This also works for 1.11.2, i tested it with a mod called Chisels & Bits. And using and item called Wooden Wrench, it can do the same thing.

Note: what my conclusion is that it works with anything that can rotate a block. as HenryLoenwind said, that it is only asking a block to rotate.

**Info:**
Forge Version: forge-13.20.0.2216
MCVersion: 1.11.2

Mod: Chisels & Bits by AlgorithmX2
Mod Version: 13.9

### PR DESCRIPTION
**Pull request by mezz**
See #3634 for more information.

### CODE REVIEW

File: patches/minecraft/net/minecraft/block/BlockBed.java.patch [hunk 1]
```diff
@@ -0,0 +1,13 @@
+--- ../src-base/minecraft/net/minecraft/block/BlockBed.java
++++ ../src-work/minecraft/net/minecraft/block/BlockBed.java
+@@ -329,4 +329,10 @@
+             return this.field_177036_c;
+         }
+     }
++
++    /* ======================================== FORGE START =====================================*/
++    public boolean rotateBlock(World world, BlockPos pos, EnumFacing axis)
```
Comment (LexManos) [inline patches/minecraft/net/minecraft/block/BlockBed.java.patch]: Rather then expand the number of patches we have, it's preferrible to add this type of stuff to the base Block class.

File: src/test/java/net/minecraftforge/debug/WrenchRotateDebug.java [hunk 2]
```diff
@@ -0,0 +1,106 @@
...
+import net.minecraft.util.ResourceLocation;
+import net.minecraft.util.math.BlockPos;
+import net.minecraft.world.World;
+import net.minecraftforge.client.model.ModelLoader;
+import net.minecraftforge.fml.common.Mod;
+import net.minecraftforge.fml.common.SidedProxy;
+import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
+import net.minecraftforge.fml.common.registry.GameRegistry;
+
+@Mod(modid = WrenchRotateDebug.modID, name = "Wrench Rotate Debug", version = "0.0.0", acceptableRemoteVersions = "*")
```
Comment (liach) [inline src/test/java/net/minecraftforge/debug/WrenchRotateDebug.java]: `acceptableRemoteVersions = "*"` seems wrong.

**Comment by mezz** [comment]
Added fixes for rotating comparators and repeaters, they were not updating their state when rotated before.

Added fixes for rotation order. Before it was pretty random (cycled the property).
Now the behavior is:
 * If block has only horizontal facings, rotate it clockwise
   * much more intuitive than cycling North, South, West, East
 * If block can be rotated on the face it was clicked, do so 
   * this is what the javadoc says the method does
 * Otherwise (block has weird allowed facings) just cycle the property
    * better than nothing, this is the current 1.11 behavior
