### PR TITLE
Double Bar Rendering fixed (#8806)

### LINKED ISSUE #8806: double bar rendering in MerchantScreen
**Minecraft Version:** 1.19

**Forge Version:** 41.0.61

**Logs:** those are not helpful

**Steps to Reproduce:**
 1. Create and register an item with following overriden methods:
-  isBarVisible returns true

 2. Create a `VillagerTrades.EmeraldForItems` listing with following parameters
 - the item registered in step 1
 - a number bigger than 1 (something like 20 works) as a cost
 - any amount of max uses
 - any amount of villagerXp
 3. Add it to a profession and an early stage using `VillagerTradesEvent`
 4. Go into a world
 5. Summon or find a villager
 6. give it a profession using the poi of the profession used in step 3
 7. get the hero of the village effect to reduce the price for the offer
 8. open the trading gui to see the offer

**Description of issue:**
The bar is rendered twice
image

**Cause of issue:**
To render the reduced price right from the item the `MerchantScreen` calls `ItemRenderer#renderGuiItemDecorations` twice in `renderAndDecorateCostA`

### PR DESCRIPTION
**Pull request by justliliandev**
This PR fixes #8806 by duplicating the count rendering in `ItemRenderer#renderGuiItemDecorations` and switching it out for the second `ItemRenderer#renderGuiItemDecorations` call in `MerchantScreen#renderAndDecorateCostA`

There should be no visible changes, except when replicating the test case.
I haven't added a test mod, but can add the one used for the issue creation, if wanted

### CODE REVIEW

File: patches/minecraft/net/minecraft/client/gui/screens/inventory/MerchantScreen.java.patch [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+@@ -240,7 +_,11 @@
+          this.f_96542_.m_115169_(this.f_96547_, p_99164_, p_99166_, p_99167_);
+       } else {
+          this.f_96542_.m_115174_(this.f_96547_, p_99165_, p_99166_, p_99167_, p_99165_.m_41613_() == 1 ? "1" : null);
+-         this.f_96542_.m_115174_(this.f_96547_, p_99164_, p_99166_ + 14, p_99167_, p_99164_.m_41613_() == 1 ? "1" : null);
++         PoseStack posestack = new PoseStack();
++         posestack.m_85837_(0.0D, 0.0D, (f_96542_.f_115093_ + 200.0F));
++         net.minecraft.client.renderer.MultiBufferSource.BufferSource bufferSource = net.minecraft.client.renderer.MultiBufferSource.m_109898_(com.mojang.blaze3d.vertex.Tesselator.m_85913_().m_85915_());
++         f_96547_.m_92811_(String.valueOf(p_99164_.m_41613_()), p_99166_ + 14 + 19 - 2 - f_96547_.m_92895_(String.valueOf(p_99164_.m_41613_())), p_99167_ + 6 + 3, 0xFFFFFF, true, posestack.m_85850_().m_85861_(), bufferSource, false, 0, 15728880);
++         bufferSource.m_109911_();
```
Comment (sciwhiz12) [inline patches/minecraft/net/minecraft/client/gui/screens/inventory/MerchantScreen.java.patch]: There should be a `// FORGE:` marker explaining that this count rendering code was taken from `ItemRenderer#renderGuiItemDecorations`, and linking to the issue for this bug.

File: patches/minecraft/net/minecraft/client/gui/screens/inventory/MerchantScreen.java.patch [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
++++ b/net/minecraft/client/gui/screens/inventory/MerchantScreen.java
+@@ -240,7 +_,11 @@
+          this.f_96542_.m_115169_(this.f_96547_, p_99164_, p_99166_, p_99167_);
+       } else {
+          this.f_96542_.m_115174_(this.f_96547_, p_99165_, p_99166_, p_99167_, p_99165_.m_41613_() == 1 ? "1" : null);
+-         this.f_96542_.m_115174_(this.f_96547_, p_99164_, p_99166_ + 14, p_99167_, p_99164_.m_41613_() == 1 ? "1" : null);
++         PoseStack posestack = new PoseStack();
++         posestack.m_85837_(0.0D, 0.0D, (f_96542_.f_115093_ + 200.0F));
++         net.minecraft.client.renderer.MultiBufferSource.BufferSource bufferSource = net.minecraft.client.renderer.MultiBufferSource.m_109898_(com.mojang.blaze3d.vertex.Tesselator.m_85913_().m_85915_());
++         f_96547_.m_92811_(String.valueOf(p_99164_.m_41613_()), p_99166_ + 14 + 19 - 2 - f_96547_.m_92895_(String.valueOf(p_99164_.m_41613_())), p_99167_ + 6 + 3, 0xFFFFFF, true, posestack.m_85850_().m_85861_(), bufferSource, false, 0, 15728880);
```
Comment (sciwhiz12) [inline patches/minecraft/net/minecraft/client/gui/screens/inventory/MerchantScreen.java.patch]: Just to make it a bit clearer, the `p_99166_ + 14` should be in parentheses.
```suggestion
+         f_96547_.m_92811_(String.valueOf(p_99164_.m_41613_()), (p_99166_ + 14) + 19 - 2 - f_96547_.m_92895_(String.valueOf(p_99164_.m_41613_())), p_99167_ + 6 + 3, 0xFFFFFF, true, posestack.m_85850_().m_85861_(), bufferSource, false, 0, 15728880);
```

**Review by sciwhiz12 — CHANGES_REQUESTED** [review]

**Review by sciwhiz12 — APPROVED** [review]
