### PR TITLE
[1.19.3] fix inconsistent vaporization in BucketItem & FluidType

### LINKED ISSUE #9261: [1.19.2] Inconsistent vaporization in BucketItem & FluidType
**Minecraft Version:** 1.19.2

**Forge Version:** 43.2.1

**Description of issue:**

I found an inconsistency between the "vanilla" `BucketItem` and the `FluidType` class (or the `FluidUtil`). It lies in the default vaporization behaviour of fluids.

The `BucketItem` checks if the dimension is "ultrawarm" and the fluid has the `FluidTags.WATER` **tag**:

`BucketItem::emptyContents` (line 126)
```
} else if (p_150717_.dimensionType().ultraWarm() && this.content.is(FluidTags.WATER)) {
```

The [`FluidUtil::tryPlaceFluid`](https://github.com/MinecraftForge/MinecraftForge/blob/1.19.2/src/main/java/net/minecraftforge/fluids/FluidUtil.java#L574) method uses the [`FluidType::isVaporizedOnPlacement`](https://github.com/MinecraftForge/MinecraftForge/blob/1.19.2/src/main/java/net/minecraftforge/fluids/FluidType.java#L829) method to check,  if the fluid should vaporize:

```
    public boolean isVaporizedOnPlacement(Level level, BlockPos pos, FluidStack stack)
    {
        if (level.dimensionType().ultraWarm())
        {
            BlockState state = this.getBlockForFluidState(level, pos, this.getStateForPlacement(level, pos, stack));
            return state != null && state.getMaterial() == Material.WATER;
        }
        return false;
    }
```

Here, however, it is checked whether the **material** is `Material.WATER`. That doesn't match the BucketItem implementation.

That could lead to incompatibilities between mods. For example my BucketLib mod act differently to the bucket item of fluids that are generated KubeJS, because they are using the BucketItem implementation and my buckets are using the `FluidUtil` compatibility class. https://github.com/cech12/WoodenBucket/issues/7

This inconsistency seems to be for a while and can also be found in 1.19.3.

My question is, what is the best way to fix that? Should the BucketItem be changed to check the material instead of the tag or should the FluidType check the tag instead of the material?
Or is it intended to work like this?

Thanks for your help. I would open a PR if a decision is found. :)

### PR DESCRIPTION
**Pull request by cech12**
This PR fixes #9261 by adding an additional check for the `FluidType::isVaporizedOnPlacement` to the `BucketItem::emptyContents` method.

Additionally it changes the `FluidType::isVaporizedOnPlacement` method to check the fluid type instead of the material. (reverted for a future major version)

After this PR is merged I will create a backport PR for 1.18.2/1.19.2.

When I missed something please let me know. :)

### CODE REVIEW

File: patches/minecraft/net/minecraft/world/item/BucketItem.java.patch [hunk 1]
```diff
@@ -47,6 +47,16 @@
                 if (this.m_142073_(p_40704_, p_40703_, blockpos2, blockhitresult)) {
                    this.m_142131_(p_40704_, p_40703_, itemstack, blockpos2);
                    if (p_40704_ instanceof ServerPlayer) {
+@@ -109,6 +_,9 @@
+          boolean flag1 = blockstate.m_60795_() || flag || block instanceof LiquidBlockContainer && ((LiquidBlockContainer)block).m_6044_(p_150717_, p_150718_, blockstate, this.f_40687_);
+          if (!flag1) {
+             return p_150719_ != null && this.m_142073_(p_150716_, p_150717_, p_150719_.m_82425_().m_121945_(p_150719_.m_82434_()), (BlockHitResult)null);
++         } else if (this.f_40687_.getFluidType().isVaporizedOnPlacement(p_150717_, p_150718_, new net.minecraftforge.fluids.FluidStack(this.f_40687_, net.minecraftforge.fluids.FluidType.BUCKET_VOLUME))) {
++            this.f_40687_.getFluidType().onVaporize(p_150716_, p_150717_, p_150718_, new net.minecraftforge.fluids.FluidStack(this.f_40687_, net.minecraftforge.fluids.FluidType.BUCKET_VOLUME));
```
Comment (ChampionAsh5357) [inline patches/minecraft/net/minecraft/world/item/BucketItem.java.patch]: Don't create a raw fluid stack, grab it from the capability on the bucket.

**Review by ChampionAsh5357 — CHANGES_REQUESTED** [review]

File: patches/minecraft/net/minecraft/world/item/BucketItem.java.patch (hunk 1 above)
Comment (cech12) [reply patches/minecraft/net/minecraft/world/item/BucketItem.java.patch]: Unfortunately, there is no access to the involved itemstack or the players hand in the `BucketItem::emptyContents` method  and I don't want to change too much there.

File: src/main/java/net/minecraftforge/fluids/FluidType.java [hunk 2]
```diff
@@ -823,12 +822,7 @@ public final boolean isLighterThanAir()
      */
     public boolean isVaporizedOnPlacement(Level level, BlockPos pos, FluidStack stack)
     {
-        if (level.dimensionType().ultraWarm())
-        {
-            BlockState state = this.getBlockForFluidState(level, pos, this.getStateForPlacement(level, pos, stack));
-            return state != null && state.getMaterial() == Material.WATER;
-        }
-        return false;
+        return level.dimensionType().ultraWarm() && stack.getFluid().getFluidType() == ForgeMod.WATER_TYPE.get();
```
Comment (ChampionAsh5357) [inline src/main/java/net/minecraftforge/fluids/FluidType.java]: For right now, revert this change. This is a logic break which will probably screw up mods which already use the material water to implement it. If we decide to add to this or modify it later, it'll probably be on a future major version where such a logic change is more acceptable along with other changes to the Fluid API.

File: patches/minecraft/net/minecraft/world/item/BucketItem.java.patch (hunk 1 above)
Comment (cech12) [reply patches/minecraft/net/minecraft/world/item/BucketItem.java.patch]: @ChampionAsh5357 What should I do with this?

File: src/main/java/net/minecraftforge/fluids/FluidType.java (hunk 2 above)
Comment (cech12) [reply src/main/java/net/minecraftforge/fluids/FluidType.java]: Okay, I will revert this change :)

Comment (cech12) [reply src/main/java/net/minecraftforge/fluids/FluidType.java]: reverted

File: patches/minecraft/net/minecraft/world/item/BucketItem.java.patch (hunk 1 above)
Comment (ChampionAsh5357) [reply patches/minecraft/net/minecraft/world/item/BucketItem.java.patch]: Sorry for the late response, we should probably expand the method to take in the ItemStack and then deprecate the old one.

Comment (cech12) [reply patches/minecraft/net/minecraft/world/item/BucketItem.java.patch]: Thanks for your answer. I am working on that and I noticed, that this method is also used in the vanilla interface `DispensibleContainerItem`. It is called by the dispenser and the `SolidBucketItem` implements that interface, too. Should I change also this interface and add the method with the item stack?

Comment (ChampionAsh5357) [reply patches/minecraft/net/minecraft/world/item/BucketItem.java.patch]: Just redirect the call to the one with the itemstack yeah.

Comment (cech12) [reply patches/minecraft/net/minecraft/world/item/BucketItem.java.patch]: I hope the actual commit conatins the changes you described here. :)

File: patches/minecraft/net/minecraft/world/item/DispensibleContainerItem.java.patch [hunk 3]
```diff
@@ -0,0 +1,11 @@
+--- a/net/minecraft/world/item/DispensibleContainerItem.java
++++ b/net/minecraft/world/item/DispensibleContainerItem.java
+@@ -10,5 +_,8 @@
+    default void m_142131_(@Nullable Player p_150817_, Level p_150818_, ItemStack p_150819_, BlockPos p_150820_) {
+    }
+ 
++   @Deprecated //Forge: use the ItemStack sensitive version
+    boolean m_142073_(@Nullable Player p_150821_, Level p_150822_, BlockPos p_150823_, @Nullable BlockHitResult p_150824_);
++
++   boolean emptyContents(@Nullable Player p_150821_, Level p_150822_, BlockPos p_150823_, @Nullable BlockHitResult p_150824_, ItemStack itemStack);
```
Comment (ChampionAsh5357) [inline patches/minecraft/net/minecraft/world/item/DispensibleContainerItem.java.patch]: This should be in an extension interface with defaults to the original version.

File: patches/minecraft/net/minecraft/world/item/BucketItem.java.patch [hunk 4]
```diff
@@ -38,15 +38,44 @@
...
                    this.m_142131_(p_40704_, p_40703_, itemstack, blockpos2);
                    if (p_40704_ instanceof ServerPlayer) {
+                      CriteriaTriggers.f_10591_.m_59469_((ServerPlayer)p_40704_, blockpos2, itemstack);
+@@ -98,7 +_,12 @@
+    public void m_142131_(@Nullable Player p_150711_, Level p_150712_, ItemStack p_150713_, BlockPos p_150714_) {
+    }
+ 
++   @Deprecated //Forge: use the ItemStack sensitive version
+    public boolean m_142073_(@Nullable Player p_150716_, Level p_150717_, BlockPos p_150718_, @Nullable BlockHitResult p_150719_) {
++      return this.emptyContents(p_150716_, p_150717_, p_150718_, p_150719_, new ItemStack(this));
```
Comment (ChampionAsh5357) [inline patches/minecraft/net/minecraft/world/item/BucketItem.java.patch]: Don't create itemstacks out of thin air. If you look at the implementations, you can see it is obtained from the player's hand. However, since we want to support vanilla behavior and not assume anything, this should be nullable.

File: patches/minecraft/net/minecraft/world/item/BucketItem.java.patch [hunk 5]
```diff
@@ -38,15 +38,44 @@
...
++
++   public boolean emptyContents(@Nullable Player p_150716_, Level p_150717_, BlockPos p_150718_, @Nullable BlockHitResult p_150719_, ItemStack itemStack) {
+       if (!(this.f_40687_ instanceof FlowingFluid)) {
+          return false;
+       } else {
+@@ -107,8 +_,12 @@
+          Material material = blockstate.m_60767_();
+          boolean flag = blockstate.m_60722_(this.f_40687_);
+          boolean flag1 = blockstate.m_60795_() || flag || block instanceof LiquidBlockContainer && ((LiquidBlockContainer)block).m_6044_(p_150717_, p_150718_, blockstate, this.f_40687_);
++         java.util.Optional<net.minecraftforge.fluids.FluidStack> fluidStack = net.minecraftforge.fluids.FluidUtil.getFluidContained(itemStack);
```
Comment (ChampionAsh5357) [inline patches/minecraft/net/minecraft/world/item/BucketItem.java.patch]: create the nullable optional and then flatmap to `#getFluidContained`.

File: patches/minecraft/net/minecraft/world/item/DispensibleContainerItem.java.patch (hunk 3 above)
Comment (ChampionAsh5357) [inline patches/minecraft/net/minecraft/world/item/DispensibleContainerItem.java.patch]: Can we name the stack parameter something useful like `container`?

File: patches/minecraft/net/minecraft/world/item/SolidBucketItem.java.patch [hunk 6]
```diff
@@ -0,0 +1,15 @@
...
+@@ -41,7 +_,12 @@
+       return this.f_151185_;
+    }
+ 
++   @Deprecated //Forge: use the ItemStack sensitive version
+    public boolean m_142073_(@Nullable Player p_151192_, Level p_151193_, BlockPos p_151194_, @Nullable BlockHitResult p_151195_) {
++      return emptyContents(p_151192_, p_151193_, p_151194_, p_151195_, new ItemStack(this));
++   }
++
++   public boolean emptyContents(@Nullable Player p_151192_, Level p_151193_, BlockPos p_151194_, @Nullable BlockHitResult p_151195_, ItemStack itemStack) {
```
Comment (ChampionAsh5357) [inline patches/minecraft/net/minecraft/world/item/SolidBucketItem.java.patch]: This is unnecessary with the extension interface method.

File: src/main/java/net/minecraftforge/fluids/FluidType.java [hunk 7]
```diff
@@ -819,7 +819,7 @@ public final boolean isLighterThanAir()
      * @param stack the stack holding the fluid being placed
      * @return {@code true} if this fluid should be vaporized on placement, {@code false} otherwise
      *
-     * @see BucketItem#emptyContents(Player, Level, BlockPos, BlockHitResult)
+     * @see BucketItem#emptyContents(Player, Level, BlockPos, BlockHitResult, ItemStack)
```
Comment (ChampionAsh5357) [inline src/main/java/net/minecraftforge/fluids/FluidType.java]: No, it's modeled after the vanilla method, do not use a Forge method here.

File: src/main/java/net/minecraftforge/fluids/FluidType.java [hunk 8]
```diff
@@ -841,7 +841,7 @@ public boolean isVaporizedOnPlacement(Level level, BlockPos pos, FluidStack stac
      * @param pos the position the fluid is vaporized at
      * @param stack the stack holding the fluid being vaporized
      *
-     * @see BucketItem#emptyContents(Player, Level, BlockPos, BlockHitResult)
+     * @see BucketItem#emptyContents(Player, Level, BlockPos, BlockHitResult, ItemStack)
```
Comment (ChampionAsh5357) [inline src/main/java/net/minecraftforge/fluids/FluidType.java]: No, it's modeled after the vanilla method, do not use a Forge method here.

File: src/main/java/net/minecraftforge/fluids/FluidUtil.java [hunk 9]
```diff
@@ -530,7 +530,7 @@ public static FluidActionResult tryPlaceFluid(@Nullable Player player, Level lev
      * Honors the amount of fluid contained by the used container.
      * Checks if water-like fluids should vaporize like in the nether.
      *
-     * Modeled after {@link BucketItem#emptyContents(Player, Level, BlockPos, BlockHitResult)}
+     * Modeled after {@link BucketItem#emptyContents(Player, Level, BlockPos, BlockHitResult, ItemStack)}
```
Comment (ChampionAsh5357) [inline src/main/java/net/minecraftforge/fluids/FluidUtil.java]: No, it's modeled after the vanilla method, do not use a Forge method here.

File: src/main/java/net/minecraftforge/fluids/FluidUtil.java [hunk 10]
```diff
@@ -617,7 +617,7 @@ private static IFluidHandler getFluidBlockHandler(Fluid fluid, Level level, Bloc
 
     /**
      * Destroys a block when a fluid is placed in the same position.
-     * Modeled after {@link BucketItem#emptyContents(Player, Level, BlockPos, BlockHitResult)}
+     * Modeled after {@link BucketItem#emptyContents(Player, Level, BlockPos, BlockHitResult, ItemStack)}
```
Comment (ChampionAsh5357) [inline src/main/java/net/minecraftforge/fluids/FluidUtil.java]: No, it's modeled after the vanilla method, do not use a Forge method here.

**Review by ChampionAsh5357 — CHANGES_REQUESTED** [review]
You're also missing a `forge.exc` entry to map the parameter names correctly in the associated userdev mapping set.

File: src/main/java/net/minecraftforge/fluids/FluidUtil.java (hunk 10 above)
Comment (cech12) [reply src/main/java/net/minecraftforge/fluids/FluidUtil.java]: reverted

File: src/main/java/net/minecraftforge/fluids/FluidUtil.java (hunk 9 above)
Comment (cech12) [reply src/main/java/net/minecraftforge/fluids/FluidUtil.java]: reverted

File: src/main/java/net/minecraftforge/fluids/FluidType.java (hunk 8 above)
Comment (cech12) [reply src/main/java/net/minecraftforge/fluids/FluidType.java]: reverted

File: src/main/java/net/minecraftforge/fluids/FluidType.java (hunk 7 above)
Comment (cech12) [reply src/main/java/net/minecraftforge/fluids/FluidType.java]: reverted

File: patches/minecraft/net/minecraft/world/item/SolidBucketItem.java.patch (hunk 6 above)
Comment (cech12) [reply patches/minecraft/net/minecraft/world/item/SolidBucketItem.java.patch]: reverted

File: patches/minecraft/net/minecraft/world/item/DispensibleContainerItem.java.patch (hunk 3 above)
Comment (cech12) [reply patches/minecraft/net/minecraft/world/item/DispensibleContainerItem.java.patch]: Good idea, done :)

File: patches/minecraft/net/minecraft/world/item/BucketItem.java.patch (hunk 5 above)
Comment (cech12) [reply patches/minecraft/net/minecraft/world/item/BucketItem.java.patch]: done

File: patches/minecraft/net/minecraft/world/item/BucketItem.java.patch (hunk 4 above)
Comment (cech12) [reply patches/minecraft/net/minecraft/world/item/BucketItem.java.patch]: Ok :)

File: patches/minecraft/net/minecraft/world/item/DispensibleContainerItem.java.patch (hunk 3 above)
Comment (cech12) [reply patches/minecraft/net/minecraft/world/item/DispensibleContainerItem.java.patch]: I hope, I did that right :)

File: src/main/java/net/minecraftforge/common/extensions/IForgeDispensibleContainerItem.java [hunk 11]
```diff
@@ -0,0 +1,22 @@
...
+import net.minecraft.world.item.ItemStack;
+import net.minecraft.world.level.Level;
+import net.minecraft.world.phys.BlockHitResult;
+import org.jetbrains.annotations.Nullable;
+
+public interface IForgeDispensibleContainerItem
+{
+    default boolean emptyContents(@Nullable Player player, Level level, BlockPos blockPos, @Nullable BlockHitResult blockHitResult, @Nullable ItemStack container)
+    {
+        return ((DispensibleContainerItem)this).emptyContents(player, level, blockPos, blockHitResult);
```
Comment (ChampionAsh5357) [inline src/main/java/net/minecraftforge/common/extensions/IForgeDispensibleContainerItem.java]: Please look at how other extension interfaces cast things.

File: src/main/java/net/minecraftforge/common/extensions/IForgeDispensibleContainerItem.java [hunk 12]
```diff
@@ -0,0 +1,22 @@
...
+import net.minecraft.world.entity.player.Player;
+import net.minecraft.world.item.DispensibleContainerItem;
+import net.minecraft.world.item.ItemStack;
+import net.minecraft.world.level.Level;
+import net.minecraft.world.phys.BlockHitResult;
+import org.jetbrains.annotations.Nullable;
+
+public interface IForgeDispensibleContainerItem
+{
+    default boolean emptyContents(@Nullable Player player, Level level, BlockPos blockPos, @Nullable BlockHitResult blockHitResult, @Nullable ItemStack container)
```
Comment (ChampionAsh5357) [inline src/main/java/net/minecraftforge/common/extensions/IForgeDispensibleContainerItem.java]: `BlockPos` can be shortened to `pos` and `BlockHitResult` to `hitResult`. Stating the class name is not the best solution. Also, this is missing documentation.

**Review by ChampionAsh5357 — CHANGES_REQUESTED** [review]

File: src/main/java/net/minecraftforge/common/extensions/IForgeDispensibleContainerItem.java (hunk 11 above)
Comment (cech12) [reply src/main/java/net/minecraftforge/common/extensions/IForgeDispensibleContainerItem.java]: Thanks for your hint. :)

File: src/main/java/net/minecraftforge/common/extensions/IForgeDispensibleContainerItem.java (hunk 12 above)
Comment (cech12) [reply src/main/java/net/minecraftforge/common/extensions/IForgeDispensibleContainerItem.java]: reworked

File: src/main/java/net/minecraftforge/common/extensions/IForgeDispensibleContainerItem.java [hunk 13]
```diff
@@ -0,0 +1,38 @@
...
+
+public interface IForgeDispensibleContainerItem
+{
+    private DispensibleContainerItem self()
+    {
+        return (DispensibleContainerItem)this;
+    }
+
+    /**
+     * ItemStack sensitive version of {@link DispensibleContainerItem#emptyContents(Player, Level, BlockPos, BlockHitResult)}
```
Comment (ChampionAsh5357) [inline src/main/java/net/minecraftforge/common/extensions/IForgeDispensibleContainerItem.java]: This line is unnecessary.

File: src/main/java/net/minecraftforge/common/extensions/IForgeDispensibleContainerItem.java [hunk 14]
```diff
@@ -0,0 +1,38 @@
...
+     * Tries to place the content of the container into the level as a block.
```
Comment (ChampionAsh5357) [inline src/main/java/net/minecraftforge/common/extensions/IForgeDispensibleContainerItem.java]: That's just the current usecase by vanilla. As evident by the name of the method, all it does it attempt to empty the contents of the container and returns whether it was successful. The position of the block is provided; however, that could still mean the contents were emptied into another block.

File: src/main/java/net/minecraftforge/common/extensions/IForgeDispensibleContainerItem.java [hunk 15]
```diff
@@ -0,0 +1,38 @@
...
+     *
+     * @param player    Player who places the fluid. May be null for blocks like dispensers.
+     * @param level     Level to place the content in
+     * @param pos       The position in the level to place the content
+     * @param hitResult Hit result of the interaction. May be null for blocks like dispensers.
+     * @param container ItemStack of the container. May be null for backwards compatibility.
+     * @return true if the placement was successful, false otherwise
```
Comment (ChampionAsh5357) [inline src/main/java/net/minecraftforge/common/extensions/IForgeDispensibleContainerItem.java]: Same thing here, frame it as emptying the contents of the container and not placing the contents in the level.

**Review by ChampionAsh5357 — CHANGES_REQUESTED** [review]

File: src/main/java/net/minecraftforge/common/extensions/IForgeDispensibleContainerItem.java (hunk 13 above)
Comment (cech12) [reply src/main/java/net/minecraftforge/common/extensions/IForgeDispensibleContainerItem.java]: reverted

File: src/main/java/net/minecraftforge/common/extensions/IForgeDispensibleContainerItem.java (hunk 14 above)
Comment (cech12) [reply src/main/java/net/minecraftforge/common/extensions/IForgeDispensibleContainerItem.java]: done

File: src/main/java/net/minecraftforge/common/extensions/IForgeDispensibleContainerItem.java (hunk 15 above)
Comment (cech12) [reply src/main/java/net/minecraftforge/common/extensions/IForgeDispensibleContainerItem.java]: done

**Comment by ChampionAsh5357** [comment]
You need to pull the latest of the branch to fix the compatibility check fail since certain things were removed between your PR and the latest version.

**Comment by cech12** [comment]
Rebased. :) I hope everthing is fine now :)

**Comment by sciwhiz12** [comment]
You did not properly rebase your PR on the main branch, as evidenced by the GitHub commit log showing many commits from the main branch being committed under your name and showing after your own commits.

You will have to revert the rebase and either merge the main branch using `git merge`, or rebase your PR branch on the main branch using `git rebase` and force-push to your remote PR branch with `git push --force-push`.

---

You can revert the rebase by doing `git reset --hard d8709536228c577125435ddfa136285da23ef42c` while your PR branch is checked out (`git switch feature/1.19.3-vaporization-fix`), which will reset the branch to the commit before your ill-fated rebase (https://github.com/MinecraftForge/MinecraftForge/pull/9269/commits/d8709536228c577125435ddfa136285da23ef42c).

After reverting the rebase and ensuring that your local main branch is up-to-date with the upstream main branch, you may either:
- Merge the main branch using `git merge 1.19.x`, and pushing the resulting merge commit; or
- Rebase your PR branch on the main branch using `git rebase 1.19.x`, and force-pushing the resulting rebased commits to your fork using `git push --force-with-lease feature/1.19.3-vaporization-fix`. (See [this StackOverflow answer](https://stackoverflow.com/questions/52823692/git-push-force-with-lease-vs-force) on the difference between `--force` and `--force-with-lease`).

Note that rebasing can be more difficult depending on the amount of commits on your PR branch and the amount of conflicts between your PR branch and the main branch. Because rebasing entails re-applying changes of your commits on top of the main branch, if the main branch modifies a patch which you touch, each commit that touches that patch will require manual conflict resolution. 

However, rebasing leaves a _linear_ history, rather than the converging history from a merge commit, which may be more desirable as a cleaner commit history in your PR.

**Comment by cech12** [comment]
@sciwhiz12 thanks for your detailed explanation! :) I missed to use `force` while pushing my rebased branch. :) I hope everything is fine now. :)

**Review by ChampionAsh5357 — APPROVED** [review]
Think this is fine from my testing. Probably should test again just in case I missed something.

File: patches/minecraft/net/minecraft/world/item/BucketItem.java.patch [hunk 16]
```diff
@@ -38,15 +38,44 @@
...
++
++   public boolean emptyContents(@Nullable Player p_150716_, Level p_150717_, BlockPos p_150718_, @Nullable BlockHitResult p_150719_, @Nullable ItemStack container) {
+       if (!(this.f_40687_ instanceof FlowingFluid)) {
+          return false;
+       } else {
+@@ -107,8 +_,12 @@
+          Material material = blockstate.m_60767_();
+          boolean flag = blockstate.m_60722_(this.f_40687_);
+          boolean flag1 = blockstate.m_60795_() || flag || block instanceof LiquidBlockContainer && ((LiquidBlockContainer)block).m_6044_(p_150717_, p_150718_, blockstate, this.f_40687_);
++         java.util.Optional<net.minecraftforge.fluids.FluidStack> containedFluidStack = java.util.Optional.ofNullable(container).flatMap(net.minecraftforge.fluids.FluidUtil::getFluidContained);
```
Comment (LexManos) [inline patches/minecraft/net/minecraft/world/item/BucketItem.java.patch:69]: For future reference, we can use var now that we're in J17
