### PR TITLE
Fix comment for permission handler config setting 

### LINKED ISSUE #8465: Invalid Permission Handler config comment
**Minecraft Version:** 1.18.1

**Forge Version:** 39.0.79

**Steps to Reproduce:**
 1. Start the game in dev
 2. Look at the log

**Description of issue:**

During startup in dev forge always prints out this warning now:
> Null comment for config option server, this is invalid and may be disallowed in the future.

It is due to [this check](https://github.com/MinecraftForge/MinecraftForge/blob/bc24487d0e6b822578399521363f77fed55697b5/src/main/java/net/minecraftforge/common/ForgeConfigSpec.java#L549-L557) and [this invalid comment declaration](https://github.com/MinecraftForge/MinecraftForge/blob/bc24487d0e6b822578399521363f77fed55697b5/src/main/java/net/minecraftforge/common/ForgeConfig.java#L88).

### PR DESCRIPTION
**Pull request by sciwhiz12**
This PR fixed #8465 by setting a proper comment for the `server.permissionHandler` config setting in Forge's config. This also improves the invalid comment check, by moving it to a place where it has access to the actual config path for the setting being defined, rather than having only access to the current path (the category in which the setting will be under).

### CODE REVIEW

File: src/main/java/net/minecraftforge/common/ForgeConfigSpec.java [hunk 1]
```diff
@@ -546,28 +548,20 @@ public LongValue defineInRange(List<String> path, Supplier<Long> defaultSupplier
...
-                }
             }
             context.setComment(comment);
             return this;
         }
         public Builder comment(String... comment)
         {
-            if(comment == null || comment.length < 1 || (comment.length == 1 && comment[0].isEmpty()))
+            hasInvalidComment = comment == null || comment.length < 1 || (comment.length == 1 && comment[0].isEmpty());
+            if(hasInvalidComment)
```
Comment (pupnewfster) [inline src/main/java/net/minecraftforge/common/ForgeConfigSpec.java]: Missing space between if and parenthesis.

File: src/main/java/net/minecraftforge/common/ForgeConfigSpec.java [hunk 2]
```diff
@@ -546,28 +548,20 @@ public LongValue defineInRange(List<String> path, Supplier<Long> defaultSupplier
 
         public Builder comment(String comment)
         {
-            if(comment == null || comment.isEmpty())
+            hasInvalidComment = comment == null || comment.isEmpty();
+            if(hasInvalidComment)
```
Comment (pupnewfster) [inline src/main/java/net/minecraftforge/common/ForgeConfigSpec.java]: Missing space between if and parenthesis.

File: src/main/java/net/minecraftforge/common/ForgeConfigSpec.java [hunk 3]
```diff
@@ -629,6 +623,19 @@ public ForgeConfigSpec build()
             return ret;
         }
 
+        private void checkComment(List<String> path)
+        {
+            if (hasInvalidComment)
+            {
+                hasInvalidComment = false;
+                if(!FMLEnvironment.production)
```
Comment (pupnewfster) [inline src/main/java/net/minecraftforge/common/ForgeConfigSpec.java]: Missing space between if and parenthesis.

**Comment by pupnewfster** [comment]
License headers also need the years updated.

**Review by pupnewfster — APPROVED** [review]
