### PR TITLE
[1.19.3] Fix models nested in custom geometries not resolving parents

### LINKED ISSUE #9193: [1.19.3] Separate perspectives no longer work
**Minecraft Version:** 1.19.3
**Forge Version:** 44.0.1

**Steps to Reproduce:**
 1. Give you the item with the id `new_model_loader_test:separate_perspective`
 2. Watch the result

**Description of issue:**
Separate perspectives no longer work. No model or texture is loaded (screenshot from the Forge test mod)

### PR DESCRIPTION
**Pull request by XFactHD**
This PR fixes models nested in custom geometries (any model which is loaded in the loader from a JSON object nested in the JSON that specifies the custom loader) not resolving parents. See https://discord.com/channels/313125603924639766/852298000042164244/1051155496746365050 for more details.

This is intentionally a breaking change to make sure implementors do not miss that parents must be resolved for nested models to work properly.

Fixes #9193.

### CODE REVIEW

File: src/main/java/net/minecraftforge/client/model/geometry/IUnbakedGeometry.java [hunk 1]
```diff
@@ -28,6 +30,13 @@
 {
     BakedModel bake(IGeometryBakingContext context, ModelBaker baker, Function<Material, TextureAtlasSprite> spriteGetter, ModelState modelState, ItemOverrides overrides, ResourceLocation modelLocation);
 
+    /**
+     * Resolve parents of nested {@link BlockModel}s which are later used in
+     * {@link IUnbakedGeometry#bake(IGeometryBakingContext, ModelBaker, Function, ModelState, ItemOverrides, ResourceLocation)}
+     * via {@link BlockModel#resolveParents(Function)}
+     */
+    void resolveParents(Function<ResourceLocation, UnbakedModel> modelGetter);
```
Comment (marchermans) [inline src/main/java/net/minecraftforge/client/model/geometry/IUnbakedGeometry.java]: Make this a default NO-OP method.
Since this is what is the most used implementation.

**Review by marchermans — CHANGES_REQUESTED** [review]

**Comment by KnightMiner** [comment]
I may be missing something, but where is that new method called? I don't see any patches, and all the non-patches in this PR just declare or implement the method

**Comment by XFactHD** [comment]
Welp, I'm an idiot and forgot to gen patches...

File: src/main/java/net/minecraftforge/client/model/geometry/IUnbakedGeometry.java (hunk 1 above)
Comment (XFactHD) [reply src/main/java/net/minecraftforge/client/model/geometry/IUnbakedGeometry.java]: In Forge itself, yes, but in most mods it'll very likely be the other way around.
My main concern is the discoverability of this for existing implementations since this issue is anything but obvious. If you deem this an acceptable risk, I'll change it to a default.

**Review by marchermans — APPROVED** [review]

**Review by Matyrobbrt — APPROVED** [review]
