### PR TITLE
[1.19.x] Fix NPE when feeding wolves and cats

### LINKED ISSUE #9035: [1.19.2] Feeding wolves in survival causes NPE
**Minecraft Version:** 1.19.2

**Forge Version:** 43.1.25 (but also likely 40.0.47 and higher. See #8477.)

### Logs

This is the relevant stack trace:
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.food.FoodProperties.m_38744_()" because the return value of "net.minecraft.world.item.ItemStack.getFoodProperties(net.minecraft.world.entity.LivingEntity)" is null
	at net.minecraft.world.entity.animal.Wolf.m_6071_(Wolf.java:332) ~[client-1.19.2-20220805.130853-srg.jar%23142!/:?]
	at net.minecraft.world.entity.Mob.m_6096_(Mob.java:1061) ~[client-1.19.2-20220805.130853-srg.jar%23142!/:?]
	at net.minecraft.world.entity.player.Player.m_36157_(Player.java:996) ~[client-1.19.2-20220805.130853-srg.jar%23142!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl$1.m_143678_(ServerGamePacketListenerImpl.java:1550) ~[client-1.19.2-20220805.130853-srg.jar%23142!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl$1.m_142299_(ServerGamePacketListenerImpl.java:1562) ~[client-1.19.2-20220805.130853-srg.jar%23142!/:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAction.m_142457_(ServerboundInteractPacket.java:116) ~[client-1.19.2-20220805.130853-srg.jar%23142!/:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.m_179617_(ServerboundInteractPacket.java:66) ~[client-1.19.2-20220805.130853-srg.jar%23142!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6946_(ServerGamePacketListenerImpl.java:1546) ~[client-1.19.2-20220805.130853-srg.jar%23142!/:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.m_5797_(ServerboundInteractPacket.java:53) ~[client-1.19.2-20220805.130853-srg.jar%23142!/:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.m_5797_(ServerboundInteractPacket.java:13) ~[client-1.19.2-20220805.130853-srg.jar%23142!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.19.2-20220805.130853-srg.jar%23142!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.19.2-20220805.130853-srg.jar%23142!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23142!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19.2-20220805.130853-srg.jar%23142!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:763) ~[client-1.19.2-20220805.130853-srg.jar%23142!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23142!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.19.2-20220805.130853-srg.jar%23142!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:746) ~[client-1.19.2-20220805.130853-srg.jar%23142!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740) ~[client-1.19.2-20220805.130853-srg.jar%23142!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[client-1.19.2-20220805.130853-srg.jar%23142!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:726) ~[client-1.19.2-20220805.130853-srg.jar%23142!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658) ~[client-1.19.2-20220805.130853-srg.jar%23142!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23142!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

### Steps to Reproduce

1. Spawn a wolf, tame it, and damage it.
2. Obtain a single food item that wolves can eat (such as a steak.)
3. Go into survival.
4. Try to feed the wolf.
5. Notice the item disappears, the wolf's health doesn't change, and this stack trace shows up.

### Description

Feeding a wolf a single food item in survival causes the above exception to be thrown.
This cannot be reproduced in creative mode, nor can it be reproduced with more than one food item in the stack.

I believe this issue also affects cats, as the code path looks similar.
I have not tested them though, so I could be wrong.
Testing the cats is left up as an exercise for the reader (have fun.)

This is the relevant code snippet in `Wolf` (see also [the patch](https://github.com/MinecraftForge/MinecraftForge/blob/b0caea8e204a7f026646396558d6d58a02bff9d6/patches/minecraft/net/minecraft/world/entity/animal/Wolf.java.patch#L8)):
```java
// in mobInteract(Player, InteractionHand)
if (!player.getAbilities().instabuild) {
  itemstack.shrink(1);
}

this.heal(itemstack.getFoodProperties(this).getNutrition());
```

The problem here is that the item is shrunk *before* `getFoodProperties()` is called.
This allows for the `ItemStack` to become empty, causing `getItem()` to return `Items.AIR`.
This results in `getNutrition()` throwing an NPE (because air isn't exactly edible.)

### PR DESCRIPTION
**Pull request by MagnusHJensen**
This PR fixes #9035
Where a NPE could occur if you weren't creative and had exactly one item in your food stack, and were feeding a wolf or a cat, due to the stack being consumed first, then returning null on the following `getFoodProperties` call.

### CODE REVIEW

File: patches/minecraft/net/minecraft/world/entity/animal/Wolf.java.patch [hunk 1]
```diff
@@ -1,11 +1,16 @@
 --- a/net/minecraft/world/entity/animal/Wolf.java
 +++ b/net/minecraft/world/entity/animal/Wolf.java
-@@ -329,7 +_,8 @@
+@@ -325,11 +_,13 @@
+       } else {
+          if (this.m_21824_()) {
+             if (this.m_6898_(itemstack) && this.m_21223_() < this.m_21233_()) {
++               this.m_5634_((float)itemstack.getFoodProperties(this).m_38744_());
++
```
Comment (Matyrobbrt) [inline patches/minecraft/net/minecraft/world/entity/animal/Wolf.java.patch]: Unnecessary patched-in blank line.

**Review by Matyrobbrt — APPROVED** [review]
After testing, I can confirm this PR fixes the NPE. I am however uncertain as to whether the nutrition should be calculated from a copy of the stack with the size of 1, as that's what the wolf / cat actually eats.

**Comment by MagnusHJensen** [comment]
> After testing, I can confirm this PR fixes the NPE. I am however uncertain as to whether the nutrition should be calculated from a copy of the stack with the size of 1, as that's what the wolf / cat actually eats.

The nutrition does not care about itemstack size.
It's taken from the FoodProperties.

**Comment by Matyrobbrt** [comment]
> It's taken from the FoodProperties.

Properties which *can* be different based on the stack size.

The JavaDocs of `IForgeItem#getFoodProperties` specify that the stack is `The ItemStack the entity wants to eat.`, animals eating only one item from the stack. However, such change of behaviour could be considered breaking.
