### PR TITLE
Fix missing serializers when deserializing global loot modifiers

### LINKED ISSUE #7497: NPE when GLM has a `EntityHasProperty` as it condition
**Minecraft Version:** 1.16.4

**Forge Version:** 35.0.18

**Logs:** https://gist.github.com/Unbekannt1998/e78d39370425e16f7fb2c610d20182c8

**Steps to Reproduce:**
 1. create a GlobalLootModifier with a `EntityHasProperty` as it condition 
 2. start the game and wait
 3. game crashes with a NPE

When you have a GLM with an `EntityHasProperty` as it condition  you get a NPE at some point in game without any interaction.
After some debugging with @diesieben07 on the Discord, he discovered there was a is a missing serializer for the `[GSON_INSTANCE](https://github.com/MinecraftForge/MinecraftForge/blob/517bbc8b5ba282076dab9bdd8b8b86f28238080f/src/main/java/net/minecraftforge/common/loot/LootModifierManager.java#L59)`, which results in Gson falling back to the default enum serializer for EntityTarget. He said there should be `LootSerializers.func_237388_c_().create()` or `LootSerializers.func_237386_a_().create()`. I would investigate this further but i don't have the time for it rn.

### PR DESCRIPTION
**Pull request by diesieben07**
Fixes https://github.com/MinecraftForge/MinecraftForge/issues/7497.

### CODE REVIEW

File: src/main/java/net/minecraftforge/common/loot/LootModifierManager.java [hunk 1]
```diff
@@ -56,7 +53,7 @@
 
 public class LootModifierManager extends JsonReloadListener {
     public static final Logger LOGGER = LogManager.getLogger();
-    private static final Gson GSON_INSTANCE = (new GsonBuilder()).registerTypeHierarchyAdapter(ILootFunction.class, LootFunctionManager.func_237450_a_()).registerTypeHierarchyAdapter(ILootCondition.class, LootConditionManager.func_237474_a_()).create();
+    private static final Gson GSON_INSTANCE = LootSerializers.func_237387_b_().create();
```
Comment (ichttt) [inline src/main/java/net/minecraftforge/common/loot/LootModifierManager.java:56]: The `GsonBuilder` returned by `LootSerializers.func_237387_b_` does not have a hierarchy adapter for `ILootCondition`. Is this a problem?

Comment (diesieben07) [reply src/main/java/net/minecraftforge/common/loot/LootModifierManager.java:56]: Yes, it does, notice how `func_237387_b_` first calls `func_237386_a_`

Comment (ichttt) [reply src/main/java/net/minecraftforge/common/loot/LootModifierManager.java:56]: You are right
